using System.Collections.Generic;
using WrathCombo.Combos.PvE;
using WrathCombo.Combos.PvP;
using WrathCombo.Extensions;

namespace WrathCombo.Resources.Dictionary.Chinese.Description
{
    public static class ASTSkills
    {
        public static IEnumerable<KeyValuePair<string, string>> GetSkills()
        {
            return
            [
                // Generated by the String Extraction and Translation Tool  
                // Model: DeepSeek v3  
                // Temperature: 0.1  
                // Generation Time: 2025-03-13 18:45:21  
                #region AST
                // DPS
                KeyValuePair.Create("Malefic IV", AST.Malefic4.ActionName()),
                KeyValuePair.Create("Malefic III", AST.Malefic3.ActionName()),
                KeyValuePair.Create("Malefic II", AST.Malefic2.ActionName()),
                KeyValuePair.Create("Malefic", AST.Malefic.ActionName()),
                KeyValuePair.Create("Fall Malefic", AST.FallMalefic.ActionName()),
                KeyValuePair.Create("Gravity II", AST.Gravity2.ActionName()),
                KeyValuePair.Create("Gravity", AST.Gravity.ActionName()),
                KeyValuePair.Create("Oracle", AST.Oracle.ActionName()),
                KeyValuePair.Create("Earthly Star", AST.EarthlyStar.ActionName()),
                KeyValuePair.Create("Stellar Detonation", AST.StellarDetonation.ActionName()),
                
                // Cards
                KeyValuePair.Create("Astral Draw", AST.AstralDraw.ActionName()),
                KeyValuePair.Create("Umbral Draw", AST.UmbralDraw.ActionName()),
                KeyValuePair.Create("Play 1", AST.Play1.ActionName()),
                KeyValuePair.Create("Play 2", AST.Play2.ActionName()),
                KeyValuePair.Create("Play 3", AST.Play3.ActionName()),
                KeyValuePair.Create("The Arrow", AST.Arrow.ActionName()),
                // KeyValuePair.Create("The Balance", AST.Balance.ActionName()),
                KeyValuePair.Create("The Bole", AST.Bole.ActionName()),
                KeyValuePair.Create("The Ewer", AST.Ewer.ActionName()),
                KeyValuePair.Create("The Spear", AST.Spear.ActionName()),
                KeyValuePair.Create("The Spire", AST.Spire.ActionName()),
                KeyValuePair.Create("Minor Arcana", AST.MinorArcana.ActionName()),
                KeyValuePair.Create("Lord of Crowns", AST.LordOfCrowns.ActionName()),
                KeyValuePair.Create("Lady of Crowns", AST.LadyOfCrown.ActionName()),
                KeyValuePair.Create("Lazy Lady", AST.LadyOfCrown.ActionName()),
                KeyValuePair.Create("Lady Option", $"{AST.LadyOfCrown.ActionName()}選項"),
                // "Turns Fall Malefic into an all-in-one damage button." lives in
                // ASTDescriptions.cs (Description layer, processed before this Skill-layer
                // file) -- a duplicate key here would always lose the key de-dup and never
                // fire, so it was removed rather than kept as dead weight.

                // Utility
                KeyValuePair.Create("Divination", AST.Divination.ActionName()),
                KeyValuePair.Create("Lightspeed", AST.Lightspeed.ActionName()),
                
                // DoT
                KeyValuePair.Create("Combust III", AST.Combust3.ActionName()),
                KeyValuePair.Create("Combust II", AST.Combust2.ActionName()),
                KeyValuePair.Create("Combust", AST.Combust.ActionName()),
                
                // Healing
                KeyValuePair.Create("Aspected Benefic", AST.AspectedBenefic.ActionName()),
                KeyValuePair.Create("Benefic 2", AST.Benefic2.ActionName()),
                KeyValuePair.Create("Benefic", AST.Benefic.ActionName()),
                KeyValuePair.Create("Aspected Helios", AST.AspectedHelios.ActionName()),
                KeyValuePair.Create("Helios Conjunction", AST.HeliosConjuction.ActionName()),
                KeyValuePair.Create("Helios", AST.Helios.ActionName()),
                KeyValuePair.Create("Ascend", AST.Ascend.ActionName()),
                KeyValuePair.Create("Essential Dignity", AST.EssentialDignity.ActionName()),
                KeyValuePair.Create("Celestial Opposition", AST.CelestialOpposition.ActionName()),
                KeyValuePair.Create("Celestial Intersection", AST.CelestialIntersection.ActionName()),
                KeyValuePair.Create("Horoscope Heal", AST.HoroscopeHeal.ActionName()),
                KeyValuePair.Create("Horoscope", AST.Horoscope.ActionName()),
                KeyValuePair.Create("Exaltation", AST.Exaltation.ActionName()),
                KeyValuePair.Create("Macrocosmos", AST.Macrocosmos.ActionName()),
                KeyValuePair.Create("Synastry", AST.Synastry.ActionName()),
                KeyValuePair.Create("Collective Unconscious", AST.CollectiveUnconscious.ActionName()),

                // PvP
                KeyValuePair.Create("Epicycle", ASTPvP.Epicycle.ActionName()),
                #endregion
            ];
        }
    }
}
