using System;
using System.Collections.Generic;
using WrathCombo.Combos.PvE;
using WrathCombo.Combos.PvP;
using WrathCombo.Extensions;

namespace WrathCombo.Resources.Dictionary.Chinese.Description
{
    public static class BLMSkills
    {
        public static IEnumerable<KeyValuePair<string, string>> GetSkills()
        {
            return
            [
                // Generated by the String Extraction and Translation Tool  
                // Model: DeepSeek v3  
                // Temperature: 0.1  
                // Generation Time: 2025-03-13 18:45:21  
                #region BLM
                // DPS
                KeyValuePair.Create("Wreath of Fire", BLMPvP.Buffs.WreathOfFire.StatusName()),
                KeyValuePair.Create("Fire IV", BLM.Fire4.ActionName()),
                KeyValuePair.Create("Fire III", BLM.Fire3.ActionName()),
                KeyValuePair.Create("High Fire II", BLM.HighFire2.ActionName()),
                KeyValuePair.Create("Fire II", BLM.Fire2.ActionName()),
                KeyValuePair.Create("Fire", BLM.Fire.ActionName()),
                KeyValuePair.Create("Transpose", BLM.Transpose.ActionName()),
                KeyValuePair.Create("Aetherial Manipulation", BLM.AetherialManipulation.ActionName()),
                KeyValuePair.Create("Scathe", BLM.Scathe.ActionName()),
                KeyValuePair.Create("Manafont", BLM.Manafont.ActionName()),
                KeyValuePair.Create("Freeze", BLM.Freeze.ActionName()),
                KeyValuePair.Create("Flare Star", BLM.FlareStar.ActionName()),
                KeyValuePair.Create("Flare", BLM.Flare.ActionName()),
                KeyValuePair.Create("Leylines", BLM.LeyLines.ActionName()),
                KeyValuePair.Create("Triplecast", BLM.Triplecast.ActionName()),
                KeyValuePair.Create("Foul", BLM.Foul.ActionName()),
                KeyValuePair.Create("Thunder IV", BLM.Thunder4.ActionName()),
                KeyValuePair.Create("Thunder III", BLM.Thunder3.ActionName()),
                KeyValuePair.Create("High Thunder II", BLM.HighThunder2.ActionName()),
                KeyValuePair.Create("Thunder II", BLM.Thunder2.ActionName()),
                KeyValuePair.Create("Thunderclap", MNK.Thunderclap.ActionName()),
                KeyValuePair.Create("High Thunder", BLM.HighThunder.ActionName()),
                KeyValuePair.Create("Thunder", BLM.Thunder.ActionName()),
                KeyValuePair.Create("Despair", BLM.Despair.ActionName()),
                KeyValuePair.Create("Umbral Soul", BLM.UmbralSoul.ActionName()),
                KeyValuePair.Create("Xenoglossy", BLM.Xenoglossy.ActionName()),
                KeyValuePair.Create("Amplifier", BLM.Amplifier.ActionName()),
                KeyValuePair.Create("Paradox", BLM.Paradox.ActionName()),
                KeyValuePair.Create("High Blizzard II", BLM.HighBlizzard2.ActionName()),
                KeyValuePair.Create("Blizzard IV", BLM.Blizzard4.ActionName()),
                KeyValuePair.Create("Blizzard III", BLM.Blizzard3.ActionName()),
                KeyValuePair.Create("Blizzard II", BLM.Blizzard2.ActionName()),
                KeyValuePair.Create("Blizzard", BLM.Blizzard.ActionName()),
                KeyValuePair.Create("Between the Lines", BLM.BetweenTheLines.ActionName()),
                #endregion
                
                #region BLMPvP
                KeyValuePair.Create("Lethargy", BLMPvP.Lethargy.ActionName()),
                KeyValuePair.Create("Elemental Star", BLMPvP.Buffs.ElementalStar.StatusName()),
                #endregion
            ];
        }
    }
}
