using System;
using System.Collections.Generic;
using WrathCombo.Combos.PvE;
using WrathCombo.Combos.PvP;
using WrathCombo.Extensions;

namespace WrathCombo.Resources.Dictionary.Chinese.Description
{
    public static class BLUSkills
    {
        public static IEnumerable<KeyValuePair<string, string>> GetSkills()
        {
            return
            [
                // Generated by the String Extraction and Translation Tool  
                // Model: DeepSeek v3  
                // Temperature: 0.1  
                // Generation Time: 2025-03-13 18:45:21  
                #region BLU
                KeyValuePair.Create("Rose of Destruction", BLU.RoseOfDestruction.ActionName()),
                KeyValuePair.Create("Shock Strike", BLU.ShockStrike.ActionName()),
                KeyValuePair.Create("Feather Rain", BLU.FeatherRain.ActionName()),
                KeyValuePair.Create("J Kick", BLU.JKick.ActionName()),
                KeyValuePair.Create("Eruption", BLU.Eruption.ActionName()),
                KeyValuePair.Create("Sharpened Knife", BLU.SharpenedKnife.ActionName()),
                KeyValuePair.Create("SharpenedKnife", BLU.SharpenedKnife.ActionName()),
                KeyValuePair.Create("Glass Dance", BLU.GlassDance.ActionName()),
                KeyValuePair.Create("Sonic Boom", BLU.SonicBoom.ActionName()),
                KeyValuePair.Create("Surpanakha", BLU.Surpanakha.ActionName()),
                KeyValuePair.Create("Nightbloom", BLU.Nightbloom.ActionName()),
                KeyValuePair.Create("Moon Flute", BLU.MoonFlute.ActionName()),
                KeyValuePair.Create("Whistle", BLU.Whistle.ActionName()),
                KeyValuePair.Create("Tingle", BLU.Tingle.ActionName()),
                KeyValuePair.Create("Triple Trident", BLU.TripleTrident.ActionName()),
                KeyValuePair.Create("Matra Magic", BLU.MatraMagic.ActionName()),
                KeyValuePair.Create("Final Sting", BLU.FinalSting.ActionName()),
                KeyValuePair.Create("Bristle", BLU.Bristle.ActionName()),
                KeyValuePair.Create("Phantom Flurry", BLU.PhantomFlurry.ActionName()),
                KeyValuePair.Create("Perpetual Ray", BLU.PerpetualRay.ActionName()),
                KeyValuePair.Create("PerpetualRay", BLU.PerpetualRay.ActionName()),
                KeyValuePair.Create("Angel Whisper", BLU.AngelWhisper.ActionName()),
                KeyValuePair.Create("Song of Torment", BLU.SongOfTorment.ActionName()),
                KeyValuePair.Create("Ram's Voice", BLU.RamsVoice.ActionName()),
                KeyValuePair.Create("Ultravibration", BLU.Ultravibration.ActionName()),
                KeyValuePair.Create("Devour", BLU.Devour.ActionName()),
                KeyValuePair.Create("Off-guard", BLU.Offguard.ActionName()),
                KeyValuePair.Create("Bad Breath", BLU.BadBreath.ActionName()),
                KeyValuePair.Create("Magic Hammer", BLU.MagicHammer.ActionName()),
                KeyValuePair.Create("Addle & Magic Hammer Debuff", $"{RoleActions.Caster.Addle.ActionName()}與{BLU.MagicHammer.ActionName()}"),
                KeyValuePair.Create("Turns Magic Hammer into Addle when off cooldown.", $"{BLU.MagicHammer.ActionName()}不在冷卻中時，切換為{RoleActions.Caster.Addle.ActionName()}。"),
                KeyValuePair.Create("White Knight's Tour", BLU.WhiteKnightsTour.ActionName()),
                KeyValuePair.Create("Black Knight's Tour", BLU.BlackKnightsTour.ActionName()),
                KeyValuePair.Create("Knight's Tour", "騎士之旅"),
                KeyValuePair.Create("Peripheral Synthesis", BLU.PeripheralSynthesis.ActionName()),
                KeyValuePair.Create("Basic Instinct", BLU.BasicInstinct.ActionName()),
                KeyValuePair.Create("Hydro Pull", BLU.HydroPull.ActionName()),
                KeyValuePair.Create("Mustard Bomb", BLU.MustardBomb.ActionName()),
                KeyValuePair.Create("Winged Reprobation", BLU.WingedReprobation.ActionName()),
                KeyValuePair.Create("Winged Reprobration", BLU.WingedReprobation.ActionName()),
                KeyValuePair.Create("Sea Shanty", BLU.SeaShanty.ActionName()),
                KeyValuePair.Create("Being Mortal", BLU.BeingMortal.ActionName()),
                KeyValuePair.Create("Breath of Magic", BLU.BreathOfMagic.ActionName()),
                KeyValuePair.Create("Mortal Flame", BLU.MortalFlame.ActionName()),
                KeyValuePair.Create("Peat Pelt", BLU.PeatPelt.ActionName()),
                KeyValuePair.Create("Deep Clean", BLU.DeepClean.ActionName()),
                // Debuffs
                KeyValuePair.Create("Lightheaded", BLU.Debuffs.Lightheaded.StatusName()),
                KeyValuePair.Create("Begrimed", BLU.Debuffs.Begrimed.StatusName()),
                #endregion
            ];
        }
    }
}
