using System;
using System.Collections.Generic;
using System.Text.RegularExpressions;
using WrathCombo.Combos.PvE;
using WrathCombo.Combos.PvE.Content;
using WrathCombo.Combos.PvP;
using WrathCombo.Extensions;

namespace WrathCombo.Resources.Dictionary.Chinese.Description
{
    public static class BozjaSkills
    {
        public static IEnumerable<KeyValuePair<string, string>> GetSkills()
        {
            return
            [
                // Generated by the String Extraction and Translation Tool
                // Model: DeepSeek v3
                // Temperature: 0.1
                // Generation Time: 2025-03-13 18:45:21
                // Cross-file dictionary-concatenation-order dead code fixes
                // (2026-08-08 full-repo sweep, see commit message for the full
                // triage). Relocated here (the earliest file this layer loads)
                // so each entry fires before whatever was shadowing it. Sorted by
                // descending key length so this block does not shadow itself.
                KeyValuePair.Create("Turns Magic Hammer into Addle when off cooldown.", $"{BLU.MagicHammer.ActionName()}不在冷卻中時，切換為{RoleActions.Caster.Addle.ActionName()}。"),
                KeyValuePair.Create("Addle & Magic Hammer Debuff", $"{RoleActions.Caster.Addle.ActionName()}與{BLU.MagicHammer.ActionName()}"),
                KeyValuePair.Create("Thunder II in Magenta", PCT.ThunderIIinMagenta.ActionName()),
                KeyValuePair.Create("Release Royal Guard", GNB.ReleaseRoyalGuard.ActionName()),
                KeyValuePair.Create("Blizzard II in Cyan", PCT.BlizzardIIinCyan.ActionName()),
                KeyValuePair.Create("Thunder in Magenta", PCT.ThunderinMagenta.ActionName()),
                KeyValuePair.Create("Blizzard in Cyan", PCT.BlizzardinCyan.ActionName()),
                KeyValuePair.Create("Fountain of Fire", SMN.FountainOfFire.ActionName()), // Single target Phoenix GCD
                KeyValuePair.Create("Circle of Scorn", PLD.CircleOfScorn.ActionName()),
                KeyValuePair.Create("Riddle of Fire", MNK.RiddleOfFire.ActionName()),
                KeyValuePair.Create("Fire II in Red", PCT.FireIIinRed.ActionName()),
                KeyValuePair.Create("Lance Barrage", DRG.LanceBarrage.ActionName()),
                KeyValuePair.Create("Fire's Reply", MNK.FiresReply.ActionName()),
                KeyValuePair.Create("Astral Flare", SMN.AstralFlare.ActionName()),   // AoE Bahamut GCD
                KeyValuePair.Create("Umbral Flare", SMN.UmbralFlare.ActionName()),       // AoE Solar Bahamut GCD
                KeyValuePair.Create("Royal Guard", GNB.RoyalGuard.ActionName()),
                KeyValuePair.Create("Fire in Red", PCT.FireInRed.ActionName()),

                // Offensive
                KeyValuePair.Create("Lost Paralyze III", Bozja.LostParalyze3.ActionName()),
                KeyValuePair.Create("Lost Focus", Bozja.LostFocus.ActionName()),
                KeyValuePair.Create("Lost Font Of Power", Bozja.LostFontOfPower.ActionName()),
                KeyValuePair.Create("Lost Font of Power", Bozja.LostFontOfPower.ActionName()),
                KeyValuePair.Create("Lost Slash", Bozja.LostSlash.ActionName()),
                KeyValuePair.Create("Lost Death", Bozja.LostDeath.ActionName()),
                KeyValuePair.Create("Banner Of Noble Ends", Bozja.BannerOfNobleEnds.ActionName()),
                KeyValuePair.Create("Banner Of Honored Sacrifice", Bozja.BannerOfHonoredSacrifice.ActionName()),
                KeyValuePair.Create("Banner Of Honed Acuity", Bozja.BannerOfHonedAcuity.ActionName()),
                KeyValuePair.Create("Lost Fair Trade", Bozja.LostFairTrade.ActionName()),
                KeyValuePair.Create("Lost Assassination", Bozja.LostAssassination.ActionName()),
                KeyValuePair.Create("Lost Manawall", Bozja.LostManawall.ActionName()),
                KeyValuePair.Create("Banner Of Tireless Conviction", Bozja.BannerOfTirelessConviction.ActionName()),
                KeyValuePair.Create("Lost Blood Rage", Bozja.LostBloodRage.ActionName()),
                KeyValuePair.Create("Banner Of Solemn Clarity", Bozja.BannerOfSolemnClarity.ActionName()),
                KeyValuePair.Create("Lost Cure IV", Bozja.LostCure4.ActionName()),
                KeyValuePair.Create("Lost Cure III", Bozja.LostCure3.ActionName()),
                KeyValuePair.Create("Lost Cure II", Bozja.LostCure2.ActionName()),
                KeyValuePair.Create("Lost Cure", Bozja.LostCure.ActionName()),
                KeyValuePair.Create("Lost Arise", Bozja.LostArise.ActionName()),
                KeyValuePair.Create("Lost Sacrifice", Bozja.LostSacrifice.ActionName()),
                KeyValuePair.Create("Lost Reraise", Bozja.LostReraise.ActionName()),
                KeyValuePair.Create("Lost Spellforge", Bozja.LostSpellforge.ActionName()),
                KeyValuePair.Create("Lost Steel Sting", Bozja.LostSteelsting.ActionName()),
                KeyValuePair.Create("Lost Protect II", Bozja.LostProtect2.ActionName()),
                KeyValuePair.Create("Lost Protect", Bozja.LostProtect.ActionName()),
                KeyValuePair.Create("Lost Shell II", Bozja.LostShell2.ActionName()),
                KeyValuePair.Create("Lost Shell", Bozja.LostShell.ActionName()),
                KeyValuePair.Create("Lost Reflect", Bozja.LostReflect.ActionName()),
                KeyValuePair.Create("Lost Bravery", Bozja.LostBravery.ActionName()),
                KeyValuePair.Create("Lost Aethershield", Bozja.LostAethershield.ActionName()),
                KeyValuePair.Create("Lost Bubble", Bozja.LostBubble.ActionName()),
                KeyValuePair.Create("Lost Stealth", Bozja.LostStealth.ActionName()),
                KeyValuePair.Create("Lost Swift", Bozja.LostSwift.ActionName()),
                KeyValuePair.Create("Lost Font Of Skill", Bozja.LostFontOfSkill.ActionName()),
                KeyValuePair.Create("Lost Impetus", Bozja.LostImpetus.ActionName()),
                KeyValuePair.Create("Lost Rampage", Bozja.LostRampage.ActionName()),
            ];
        }
    }
}