using System;
using System.Collections.Generic;
using WrathCombo.Combos.PvE;
using WrathCombo.Combos.PvP;
using WrathCombo.Extensions;

namespace WrathCombo.Resources.Dictionary.Chinese.Description
{
    public static class BRDSkills
    {
        public static IEnumerable<KeyValuePair<string, string>> GetSkills()
        {
            return
            [
                // Generated by the String Extraction and Translation Tool  
                // Model: DeepSeek v3  
                // Temperature: 0.1  
                // Generation Time: 2025-03-13 18:45:21  
                #region BRD
                KeyValuePair.Create("Heavy Shot", BRD.HeavyShot.ActionName()),
                KeyValuePair.Create("Straight Shot", BRD.StraightShot.ActionName()),
                KeyValuePair.Create("Venomous Bite", BRD.VenomousBite.ActionName()),
                KeyValuePair.Create("Raging Strikes", BRD.RagingStrikes.ActionName()),
                KeyValuePair.Create("Quick Nock", BRD.QuickNock.ActionName()),
                KeyValuePair.Create("Barrage", BRD.Barrage.ActionName()),
                KeyValuePair.Create("Bloodletter", BRD.Bloodletter.ActionName()),
                KeyValuePair.Create("Windbite", BRD.Windbite.ActionName()),
                KeyValuePair.Create("Mage's Ballad", BRD.MagesBallad.ActionName()),
                KeyValuePair.Create("Army's Paeon", BRD.ArmysPaeon.ActionName()),
                KeyValuePair.Create("Rain of Death", BRD.RainOfDeath.ActionName()),
                KeyValuePair.Create("Battle Voice", BRD.BattleVoice.ActionName()),
                KeyValuePair.Create("Empyreal Arrow", BRD.EmpyrealArrow.ActionName()),
                KeyValuePair.Create("Wanderer's Minuet", BRD.WanderersMinuet.ActionName()),
                KeyValuePair.Create("Iron Jaws", BRD.IronJaws.ActionName()),
                KeyValuePair.Create("The Warden's Paeon", BRD.TheWardensPaeon.ActionName()),
                KeyValuePair.Create("Wardens Paeon", BRD.TheWardensPaeon.ActionName()),
                KeyValuePair.Create("Sidewinder", BRD.Sidewinder.ActionName()),
                KeyValuePair.Create("Pitch Perfect", BRD.PitchPerfect.ActionName()),
                KeyValuePair.Create("Troubadour", BRD.Troubadour.ActionName()),
                KeyValuePair.Create("Caustic Bite", BRD.CausticBite.ActionName()),
                KeyValuePair.Create("Stormbite", BRD.Stormbite.ActionName()),
                KeyValuePair.Create("Refulgent Arrow", BRD.RefulgentArrow.ActionName()),
                KeyValuePair.Create("Burst Shot", BRD.BurstShot.ActionName()),
                KeyValuePair.Create("Shadowbite", BRD.Shadowbite.ActionName()),
                KeyValuePair.Create("Ladon's Bite", BRD.Ladonsbite.ActionName()),
                KeyValuePair.Create("Ladonsbite", BRD.Ladonsbite.ActionName()),
                KeyValuePair.Create("Blast Arrow", BRD.BlastArrow.ActionName()),
                KeyValuePair.Create("Radiant Finale", BRD.RadiantFinale.ActionName()),
                KeyValuePair.Create("Wide Volley", BRD.WideVolley.ActionName()),
                KeyValuePair.Create("Heartbreak Shot", BRD.HeartbreakShot.ActionName()),
                KeyValuePair.Create("Heartbreakshot", BRD.HeartbreakShot.ActionName()),
                KeyValuePair.Create("Resonant Arrow", BRD.ResonantArrow.ActionName()),
                KeyValuePair.Create("Apex Arrow", BRD.ApexArrow.ActionName()),
                KeyValuePair.Create("Radiant Encore", BRD.RadiantEncore.ActionName()),
                #endregion
                                
                #region BRDPvP
                KeyValuePair.Create("Silent Nocturne", BRDPvP.SilentNocturne.ActionName()),
                KeyValuePair.Create("Harmonic Arrow", BRDPvP.HarmonicArrow.ActionName()),
                // Manually added
                KeyValuePair.Create("Encore of Light", "英雄的返場餘音"),
                #endregion
            ];
        }
    }
}
