using System;
using System.Collections.Generic;
using WrathCombo.Combos.PvE;
using WrathCombo.Combos.PvE.Content;
using WrathCombo.Combos.PvP;
using WrathCombo.Extensions;

namespace WrathCombo.Resources.Dictionary.Chinese.Skill
{
    public static class CommonSkills
    {
        public static IEnumerable<KeyValuePair<string, string>> GetSkills()
        {
            return
            [
                // Generated by the String Extraction and Translation Tool  
                // Model: DeepSeek v3  
                // Temperature: 0.1  
                // Generation Time: 2025-03-13 18:45:21  
                #region PVE
                // Tank
                KeyValuePair.Create("Shield Wall", RoleActions.Tank.ShieldWall.ActionName()),
                KeyValuePair.Create("Stronghold", RoleActions.Tank.Stronghold.ActionName()),
                KeyValuePair.Create("Rampart", RoleActions.Tank.Rampart.ActionName()),
                KeyValuePair.Create("Low Blow", RoleActions.Tank.LowBlow.ActionName()),
                KeyValuePair.Create("Provoke", RoleActions.Tank.Provoke.ActionName()),
                KeyValuePair.Create("Interject", RoleActions.Tank.Interject.ActionName()),
                KeyValuePair.Create("Reprisal", RoleActions.Tank.Reprisal.ActionName()),
                KeyValuePair.Create("Shirk", RoleActions.Tank.Shirk.ActionName()),
                // Tank Descriptions
                KeyValuePair.Create("one-button mitigation.", "一鍵減傷。"),
                KeyValuePair.Create("when your target's cast is interruptible.", "(目標的施法可被打斷時)。"),
                KeyValuePair.Create("when your target's casting, interruptible or not.", "(目標正在施法時，無論是否可被打斷。)。"),
                KeyValuePair.Create("when your target is casting, interruptible or not.", "(目標正在施法時，無論是否可被打斷。)。"),

                // Healer
                KeyValuePair.Create("Healing Wind", RoleActions.Healer.HealingWind.ActionName()),
                KeyValuePair.Create("Breath of the Earth", RoleActions.Healer.BreathOfTheEarth.ActionName()),
                KeyValuePair.Create("Repose", RoleActions.Healer.Repose.ActionName()),
                KeyValuePair.Create("Esuna", RoleActions.Healer.Esuna.ActionName()),
                KeyValuePair.Create("Rescue", RoleActions.Healer.Rescue.ActionName()),

                // Melee
                KeyValuePair.Create("Braver", RoleActions.Melee.Braver.ActionName()),
                KeyValuePair.Create("Bladedance", RoleActions.Melee.Bladedance.ActionName()),
                KeyValuePair.Create("Leg Sweep", RoleActions.Melee.LegSweep.ActionName()),
                KeyValuePair.Create("Bloodbath", RoleActions.Melee.Bloodbath.ActionName()),
                KeyValuePair.Create("Feint", RoleActions.Melee.Feint.ActionName()),
                KeyValuePair.Create("True North", RoleActions.Melee.TrueNorth.ActionName()),

                // PhysRanged
                KeyValuePair.Create("Big Shot", RoleActions.PhysRanged.BigShot.ActionName()),
                KeyValuePair.Create("Desperado", RoleActions.PhysRanged.Desperado.ActionName()),
                KeyValuePair.Create("Leg Graze", RoleActions.PhysRanged.LegGraze.ActionName()),
                KeyValuePair.Create("Foot Graze", RoleActions.PhysRanged.FootGraze.ActionName()),
                KeyValuePair.Create("Peloton", RoleActions.PhysRanged.Peloton.ActionName()),
                KeyValuePair.Create("Head Graze", RoleActions.PhysRanged.HeadGraze.ActionName()),

                // Caster
                KeyValuePair.Create("Skyshard", RoleActions.Caster.Skyshard.ActionName()),
                KeyValuePair.Create("Starstorm", RoleActions.Caster.Starstorm.ActionName()),
                KeyValuePair.Create("Addle", RoleActions.Caster.Addle.ActionName()),
                KeyValuePair.Create("Sleep", RoleActions.Caster.Sleep.ActionName()),

                // Multi-role actions
                KeyValuePair.Create("Second Wind", "內丹"),
                KeyValuePair.Create("Lucid Dreaming", "醒夢"),
                KeyValuePair.Create("Swiftcast", "即刻詠唱"),
                KeyValuePair.Create("Arm's Length", RoleActions.Physical.ArmsLength.ActionName()),
                KeyValuePair.Create("Arms Length", RoleActions.Physical.ArmsLength.ActionName()),
                KeyValuePair.Create("Surecast", RoleActions.Magic.Surecast.ActionName()),

                // Misc
                KeyValuePair.Create("Resurrection", "復生"),
                KeyValuePair.Create("Raise", "復活"),
                KeyValuePair.Create("Solid Reason", DOL.SolidReason.ActionName()),
                KeyValuePair.Create("Ageless Words", DOL.AgelessWords.ActionName()),

                // Common config option labels/descriptions (2026-08-07 sweep: these are
                // generic combo-option strings shared across many jobs' *_Config.cs and
                // CustomComboInfo attributes, routed through ReplaceWithChinese() same as
                // everything else above).
                KeyValuePair.Create("Rampart Option", $"{RoleActions.Tank.Rampart.ActionName()}選項"),
                KeyValuePair.Create("Reprisal Option", $"{RoleActions.Tank.Reprisal.ActionName()}選項"),
                KeyValuePair.Create("Interrupt Option", "打斷選項"),
                KeyValuePair.Create("Interrupt with Stun Option", "暈眩打斷選項"),
                KeyValuePair.Create("Arm's Length Option", $"{RoleActions.Physical.ArmsLength.ActionName()}選項"),
                KeyValuePair.Create("Second Wind Option", "內丹選項"),
                KeyValuePair.Create("Lucid Dreaming Option", "醒夢選項"),
                KeyValuePair.Create("Lucid Dreaming Weave Option", "醒夢插入選項"),
                KeyValuePair.Create("Swiftcast Option", "即刻詠唱選項"),
                KeyValuePair.Create("Esuna Option", $"{RoleActions.Healer.Esuna.ActionName()}選項"),
                KeyValuePair.Create("Mitigation Options", "減傷選項"),
                KeyValuePair.Create("Combo Heals Option", "連段自療選項"),
                KeyValuePair.Create("Not on Bosses", "不對首領使用"),
                KeyValuePair.Create("Only Weave", "僅插入使用"),
                KeyValuePair.Create("Hidden Options", "隱藏選項"),
                KeyValuePair.Create("Will only weave this action.", "此動作僅會插入使用。"),
                KeyValuePair.Create("Will not use on ST in Boss encounters.", "首領戰中不會對單體目標使用。"),
                KeyValuePair.Create("Collection of Mitigations to add to the rotation.", "加入循環的減傷技能集合。"),
                KeyValuePair.Create("Collection of Mitigation features.", "減傷功能集合。"),
                KeyValuePair.Create("Uses interrupt during the rotation if applicable.", "適用時會在循環中使用打斷技能。"),
                KeyValuePair.Create("Uses Second Wind when below set HP percentage.", "血量低於設定百分比時使用內丹。"),
                KeyValuePair.Create("Output Combat Log", "輸出戰鬥紀錄"),
                KeyValuePair.Create("Include Mitigations", "包含減傷"),
                KeyValuePair.Create("Exclude Mitigations", "排除減傷"),
                KeyValuePair.Create("Enables the use of mitigations in Simple Mode.", "在簡易模式中啟用減傷技能。"),
                KeyValuePair.Create("Disables the use of mitigations in Simple Mode.", "在簡易模式中停用減傷技能。"),
                KeyValuePair.Create("Non-boss Encounters Only", "僅非Boss遭遇戰"),
                KeyValuePair.Create("Buffs Option", "增益選項"),
                KeyValuePair.Create("Buffs AoE Option", "AoE增益選項"),
                KeyValuePair.Create("Normal Opener", "一般起手式"),
                KeyValuePair.Create("Early Opener", "提前起手式"),
                KeyValuePair.Create("Opener (Level 100)", "起手式(100級)"),
                #endregion

                #region PVP
                KeyValuePair.Create("Recuperate", PvPCommon.Recuperate.ActionName()),
                KeyValuePair.Create("Purify", PvPCommon.Purify.ActionName()),
                KeyValuePair.Create("Guard", PvPCommon.Guard.ActionName()),
                #endregion
            ];
        }
    }
}
