using System;
using System.Collections.Generic;
using WrathCombo.Combos.PvE;
using WrathCombo.Combos.PvP;
using WrathCombo.Extensions;

namespace WrathCombo.Resources.Dictionary.Chinese.Description
{
    public static class DNCSkills
    {
        public static IEnumerable<KeyValuePair<string, string>> GetSkills()
        {
            return
            [
                // Generated by the String Extraction and Translation Tool  
                // Model: DeepSeek v3  
                // Temperature: 0.1  
                // Generation Time: 2025-03-13 18:45:21  
                #region DNC
                // Single Target
                KeyValuePair.Create("Reverse Cascade", DNC.ReverseCascade.ActionName()),
                KeyValuePair.Create("Cascade", DNC.Cascade.ActionName()),
                KeyValuePair.Create("Fountain", DNC.Fountain.ActionName()),
                KeyValuePair.Create("Fountainfall", DNC.Fountainfall.ActionName()),
                KeyValuePair.Create("Starfall Dance", DNC.StarfallDance.ActionName()),

                // AoE
                KeyValuePair.Create("Rising Windmill", DNC.RisingWindmill.ActionName()),
                KeyValuePair.Create("Windmill", DNC.Windmill.ActionName()),
                KeyValuePair.Create("Bladeshower", DNC.Bladeshower.ActionName()),
                KeyValuePair.Create("Bloodshower", DNC.Bloodshower.ActionName()),
                KeyValuePair.Create("Tillana", DNC.Tillana.ActionName()),

                // Dancing
                KeyValuePair.Create("Standard Step", DNC.StandardStep.ActionName()),
                KeyValuePair.Create("Technical Step", DNC.TechnicalStep.ActionName()),
                KeyValuePair.Create("Standard Finish 0", DNC.StandardFinish0.ActionName()),
                KeyValuePair.Create("Standard Finish 1", DNC.StandardFinish1.ActionName()),
                KeyValuePair.Create("Standard Finish 2", DNC.StandardFinish2.ActionName()),
                KeyValuePair.Create("Technical Finish 0", DNC.TechnicalFinish0.ActionName()),
                KeyValuePair.Create("Technical Finish 1", DNC.TechnicalFinish1.ActionName()),
                KeyValuePair.Create("Technical Finish 2", DNC.TechnicalFinish2.ActionName()),
                KeyValuePair.Create("Technical Finish 3", DNC.TechnicalFinish3.ActionName()),
                KeyValuePair.Create("Technical Finish 4", DNC.TechnicalFinish4.ActionName()),
                KeyValuePair.Create("Emboite", DNC.Emboite.ActionName()),
                KeyValuePair.Create("Entrechat", DNC.Entrechat.ActionName()),
                KeyValuePair.Create("Jete", DNC.Jete.ActionName()),
                KeyValuePair.Create("Pirouette", DNC.Pirouette.ActionName()),

                // Fan Dances
                KeyValuePair.Create("Fan Dance 1", DNC.FanDance1.ActionName()),
                KeyValuePair.Create("Fan Dance 2", DNC.FanDance2.ActionName()),
                KeyValuePair.Create("Fan Dance 3", DNC.FanDance3.ActionName()),
                KeyValuePair.Create("Fan Dance 4", DNC.FanDance4.ActionName()),

                // Other
                KeyValuePair.Create("Saber Dance", DNC.SaberDance.ActionName()),
                KeyValuePair.Create("Closed Position", DNC.ClosedPosition.ActionName()),
                KeyValuePair.Create("Ending", DNC.Ending.ActionName()),
                KeyValuePair.Create("En Avant", DNC.EnAvant.ActionName()),
                KeyValuePair.Create("Devilment", DNC.Devilment.ActionName()),
                KeyValuePair.Create("Shield Samba", DNC.ShieldSamba.ActionName()),
                KeyValuePair.Create("Flourish", DNC.Flourish.ActionName()),
                KeyValuePair.Create("Improvisation", DNC.Improvisation.ActionName()),
                KeyValuePair.Create("Curing Waltz", DNC.CuringWaltz.ActionName()),
                KeyValuePair.Create("Last Dance", DNC.LastDance.ActionName()),
                KeyValuePair.Create("Finishing Move", DNC.FinishingMove.ActionName()),
                KeyValuePair.Create("Dance of the Dawn", DNC.DanceOfTheDawn.ActionName()),
                #endregion
                
                #region DNCPvP
                KeyValuePair.Create("Honing Dance", DNCPvP.HoningDance.ActionName()),
                KeyValuePair.Create("Honing Ovation", DNCPvP.HoningOvation.ActionName()),
                #endregion
            ];
        }
    }
}
