using System;
using System.Collections.Generic;
using WrathCombo.Combos.PvE;
using WrathCombo.Combos.PvP;
using WrathCombo.Extensions;

namespace WrathCombo.Resources.Dictionary.Chinese.Description
{
    public static class DRGSkills
    {
        public static IEnumerable<KeyValuePair<string, string>> GetSkills()
        {
            return
            [
                // Generated by the String Extraction and Translation Tool  
                // Model: DeepSeek v3  
                // Temperature: 0.1  
                // Generation Time: 2025-03-13 18:45:21  
                #region DRG
                // General
                KeyValuePair.Create("Piercing Talon", DRG.PiercingTalon.ActionName()),
                KeyValuePair.Create("Elusive Jump", DRG.ElusiveJump.ActionName()),
                KeyValuePair.Create("Lance Charge", DRG.LanceCharge.ActionName()),
                KeyValuePair.Create("Battle Litany", DRG.BattleLitany.ActionName()),
                KeyValuePair.Create("High Jump", DRG.HighJump.ActionName()),
                KeyValuePair.Create("Jump", DRG.Jump.ActionName()),
                KeyValuePair.Create("Life Surge", DRG.LifeSurge.ActionName()),
                KeyValuePair.Create("Mirage Dive", DRG.MirageDive.ActionName()),
                KeyValuePair.Create("Blood of the Dragon", DRG.BloodOfTheDragon.ActionName()),

                // Dragoon Attacks
                KeyValuePair.Create("Stardiver", DRG.Stardiver.ActionName()),
                KeyValuePair.Create("Coerthan Torment", DRG.CoerthanTorment.ActionName()),
                KeyValuePair.Create("Doom Spike", DRG.DoomSpike.ActionName()),
                KeyValuePair.Create("Doomspike", DRG.DoomSpike.ActionName()),
                KeyValuePair.Create("Sonic Thrust", DRG.SonicThrust.ActionName()),
                KeyValuePair.Create("Chaos Thrust", DRG.ChaosThrust.ActionName()),
                KeyValuePair.Create("Raiden Thrust", DRG.RaidenThrust.ActionName()),
                KeyValuePair.Create("True Thrust", DRG.TrueThrust.ActionName()),
                KeyValuePair.Create("Disembowel", DRG.Disembowel.ActionName()),
                KeyValuePair.Create("Fang And Claw", DRG.FangAndClaw.ActionName()),
                KeyValuePair.Create("Wheeling Thrust", DRG.WheelingThrust.ActionName()),
                KeyValuePair.Create("Full Thrust", DRG.FullThrust.ActionName()),
                KeyValuePair.Create("FullThrust", DRG.FullThrust.ActionName()),
                KeyValuePair.Create("Vorpal Thrust", DRG.VorpalThrust.ActionName()),
                KeyValuePair.Create("Wyrmwind Thrust", DRG.WyrmwindThrust.ActionName()),
                KeyValuePair.Create("Draconian Fury", DRG.DraconianFury.ActionName()),
                KeyValuePair.Create("Chaotic Spring", DRG.ChaoticSpring.ActionName()),
                KeyValuePair.Create("Chaotic Combo", $"{DRG.ChaoticSpring.ActionName()}連擊"),

                // Dragon Abilities
                KeyValuePair.Create("Dragonfire Dive", DRG.DragonfireDive.ActionName()),
                KeyValuePair.Create("Geirskogul", DRG.Geirskogul.ActionName()),
                KeyValuePair.Create("Nastrond", DRG.Nastrond.ActionName()),
                KeyValuePair.Create("Heaven's Thrust", DRG.HeavensThrust.ActionName()),
                KeyValuePair.Create("Heavens' Thrust", DRG.HeavensThrust.ActionName()),

                // Final Attacks
                KeyValuePair.Create("Drakesbane", DRG.Drakesbane.ActionName()),
                KeyValuePair.Create("Rise of the Dragon", DRG.RiseOfTheDragon.ActionName()),
                KeyValuePair.Create("Spiral Blow", DRG.SpiralBlow.ActionName()),
                KeyValuePair.Create("Starcross", DRG.Starcross.ActionName()),

                // PvP
                KeyValuePair.Create("Horrid Roar", DRGPvP.HorridRoar.ActionName()),
                #endregion
            ];
        }
    }
}
