using System;
using System.Collections.Generic;
using WrathCombo.Combos.PvE;
using WrathCombo.Combos.PvP;
using WrathCombo.Extensions;

namespace WrathCombo.Resources.Dictionary.Chinese.Description
{
    public static class DRKSkills
    {
        public static IEnumerable<KeyValuePair<string, string>> GetSkills()
        {
            return
            [
                // Generated by the String Extraction and Translation Tool  
                // Model: DeepSeek v3  
                // Temperature: 0.1  
                // Generation Time: 2025-03-13 18:45:21  
                #region DRK
                // Offensive
                KeyValuePair.Create("Hard Slash", DRK.HardSlash.ActionName()),
                KeyValuePair.Create("Syphon Strike", DRK.SyphonStrike.ActionName()),
                KeyValuePair.Create("Souleater", DRK.Souleater.ActionName()),
                KeyValuePair.Create("Unleash", DRK.Unleash.ActionName()),
                KeyValuePair.Create("Stalwart Soul", DRK.StalwartSoul.ActionName()),
                KeyValuePair.Create("Carve and Spit", DRK.CarveAndSpit.ActionName()),
                KeyValuePair.Create("Edge of Darkness", DRK.EdgeOfDarkness.ActionName()),
                KeyValuePair.Create("Edge of Shadow", DRK.EdgeOfShadow.ActionName()),
                KeyValuePair.Create("Bloodspiller", DRK.Bloodspiller.ActionName()),
                KeyValuePair.Create("Scarlet Delirium", DRK.ScarletDelirium.ActionName()),
                KeyValuePair.Create("Comeuppance", DRK.Comeuppance.ActionName()),
                KeyValuePair.Create("Torcleaver", DRK.Torcleaver.ActionName()),
                KeyValuePair.Create("Abyssal Drain", DRK.AbyssalDrain.ActionName()),
                KeyValuePair.Create("Flood of Darkness", DRK.FloodOfDarkness.ActionName()),
                KeyValuePair.Create("Flood of Shadow", DRK.FloodOfShadow.ActionName()),
                KeyValuePair.Create("Quietus", DRK.Quietus.ActionName()),
                KeyValuePair.Create("Salted Earth", DRK.SaltedEarth.ActionName()),
                KeyValuePair.Create("Salt and Darkness", DRK.SaltAndDarkness.ActionName()),
                KeyValuePair.Create("Impalement", DRK.Impalement.ActionName()),
                KeyValuePair.Create("Blood Weapon", DRK.BloodWeapon.ActionName()),
                KeyValuePair.Create("Delirium", DRK.Delirium.ActionName()),
                KeyValuePair.Create("Living Shadow", DRK.LivingShadow.ActionName()),
                KeyValuePair.Create("Shadowbringer", DRK.Shadowbringer.ActionName()),
                KeyValuePair.Create("Disesteem", DRK.Disesteem.ActionName()),
                KeyValuePair.Create("Unmend", DRK.Unmend.ActionName()),
                
                // Defensive
                KeyValuePair.Create("Grit", DRK.Grit.ActionName()),
                KeyValuePair.Create("Release Grit", DRK.ReleaseGrit.ActionName()),
                KeyValuePair.Create("Shadow Wall", DRK.ShadowWall.ActionName()),
                KeyValuePair.Create("Dark Mind", DRK.DarkMind.ActionName()),
                KeyValuePair.Create("Living Dead", DRK.LivingDead.ActionName()),
                KeyValuePair.Create("Dark Missionary", DRK.DarkMissionary.ActionName()),
                KeyValuePair.Create("The Blackest Night", DRK.BlackestNight.ActionName()),
                KeyValuePair.Create("Oblation", DRK.Oblation.ActionName()),
                KeyValuePair.Create("Shadowed Vigil", DRK.ShadowedVigil.ActionName()),
                KeyValuePair.Create("Vigil", DRK.ShadowedVigil.ActionName()),
                KeyValuePair.Create("Walking Dead", "行屍走肉"),
                KeyValuePair.Create("Blackest Night Shield", "至黑之夜護盾"),
                KeyValuePair.Create("Blackest Night", "至黑之夜護盾"),

                // Buffs
                KeyValuePair.Create("Darkside", DRK.Buffs.Darkside.StatusName()),
                KeyValuePair.Create("Blood Gauge", "暗血"),

                // PVP
                KeyValuePair.Create("Plunge", DRKPvP.Plunge.ActionName()),
                KeyValuePair.Create("Scorn", DRKPvP.Buffs.Scorn.StatusName()),
                KeyValuePair.Create("Dark Arts", DRKPvP.Buffs.DarkArts.StatusName()),
                #endregion
            ];
        }
    }
}
