using System;
using System.Collections.Generic;
using WrathCombo.Combos.PvE;
using WrathCombo.Combos.PvP;
using WrathCombo.Extensions;

namespace WrathCombo.Resources.Dictionary.Chinese.Description
{
    public static class GNBSkills
    {
        public static IEnumerable<KeyValuePair<string, string>> GetSkills()
        {
            return
            [
                // Generated by the String Extraction and Translation Tool  
                // Model: DeepSeek v3  
                // Temperature: 0.1  
                // Generation Time: 2025-03-13 18:45:21  
                #region GNB

                // Offensive
                KeyValuePair.Create("Keen Edge", GNB.KeenEdge.ActionName()),
                KeyValuePair.Create("No Mercy", GNB.NoMercy.ActionName()),
                KeyValuePair.Create("Brutal Shell", GNB.BrutalShell.ActionName()),
                KeyValuePair.Create("Demon Slice", GNB.DemonSlice.ActionName()),
                KeyValuePair.Create("Lightning Shot", GNB.LightningShot.ActionName()),
                KeyValuePair.Create("Danger Zone", GNB.DangerZone.ActionName()),
                KeyValuePair.Create("Solid Barrel", GNB.SolidBarrel.ActionName()),
                KeyValuePair.Create("Burst Strike", GNB.BurstStrike.ActionName()),
                KeyValuePair.Create("Demon Slaughter", GNB.DemonSlaughter.ActionName()),
                KeyValuePair.Create("Sonic Break", GNB.SonicBreak.ActionName()),
                KeyValuePair.Create("Gnashing Fang", GNB.GnashingFang.ActionName()),
                KeyValuePair.Create("Savage Claw", GNB.SavageClaw.ActionName()),
                KeyValuePair.Create("Wicked Talon", GNB.WickedTalon.ActionName()),
                KeyValuePair.Create("Bow Shock", GNB.BowShock.ActionName()),
                KeyValuePair.Create("Abdomen Tear", GNB.AbdomenTear.ActionName()),
                KeyValuePair.Create("Jugular Rip", GNB.JugularRip.ActionName()),
                KeyValuePair.Create("Eye Gouge", GNB.EyeGouge.ActionName()),
                KeyValuePair.Create("Continuation", GNB.Continuation.ActionName()),
                KeyValuePair.Create("Fated Circle", GNB.FatedCircle.ActionName()),
                KeyValuePair.Create("Bloodfest", GNB.Bloodfest.ActionName()),
                KeyValuePair.Create("Hypervelocity", GNB.Hypervelocity.ActionName()),
                KeyValuePair.Create("Double Down", GNB.DoubleDown.ActionName()),
                KeyValuePair.Create("Fated Brand", GNB.FatedBrand.ActionName()),
                KeyValuePair.Create("Reign Of Beasts", GNB.ReignOfBeasts.ActionName()),
                KeyValuePair.Create("Noble Blood", GNB.NobleBlood.ActionName()),
                KeyValuePair.Create("Lion Heart", GNB.LionHeart.ActionName()),
                KeyValuePair.Create("Reign/Noble/Lionheart", $"{GNB.ReignOfBeasts.ActionName()}/{GNB.NobleBlood.ActionName()}/{GNB.LionHeart.ActionName()}"),
                KeyValuePair.Create("Reign/Noble/LionHeart", $"{GNB.ReignOfBeasts.ActionName()}/{GNB.NobleBlood.ActionName()}/{GNB.LionHeart.ActionName()}"),
                KeyValuePair.Create("Danger / Blasting Zone", $"{GNB.DangerZone.ActionName()}/{GNB.BlastingZone.ActionName()}"),
                KeyValuePair.Create("Danger/Blasting Zone", $"{GNB.DangerZone.ActionName()}/{GNB.BlastingZone.ActionName()}"),
                KeyValuePair.Create("Blasting Zone", GNB.BlastingZone.ActionName()),
                KeyValuePair.Create("Reign Combo", $"{GNB.ReignOfBeasts.ActionName()}連擊"),
                KeyValuePair.Create("Reign combo", $"{GNB.ReignOfBeasts.ActionName()}連擊"),
                KeyValuePair.Create("Reign", GNB.ReignOfBeasts.ActionName()),
                KeyValuePair.Create("Danger/Blasting", $"{GNB.DangerZone.ActionName()}/{GNB.BlastingZone.ActionName()}"),
                KeyValuePair.Create("Ammo Overcap", "彈藥溢位"),
                KeyValuePair.Create("Zone", "領域"),

                // Defensive
                KeyValuePair.Create("Camouflage", GNB.Camouflage.ActionName()),
                KeyValuePair.Create("Royal Guard", GNB.RoyalGuard.ActionName()),
                KeyValuePair.Create("Release Royal Guard", GNB.ReleaseRoyalGuard.ActionName()),
                KeyValuePair.Create("Nebula", GNB.Nebula.ActionName()),
                KeyValuePair.Create("Aurora", GNB.Aurora.ActionName()),
                KeyValuePair.Create("Superbolide", GNB.Superbolide.ActionName()),
                KeyValuePair.Create("Heart of Light", GNB.HeartOfLight.ActionName()),
                KeyValuePair.Create("Heart Of Light", GNB.HeartOfLight.ActionName()),
                KeyValuePair.Create("Heart of Stone", GNB.HeartOfStone.ActionName()),
                KeyValuePair.Create("Trajectory", GNB.Trajectory.ActionName()),
                KeyValuePair.Create("Heart of Corundum", GNB.HeartOfCorundum.ActionName()),
                KeyValuePair.Create("Corundum", GNB.HeartOfCorundum.ActionName()),
                KeyValuePair.Create("Great Nebula", GNB.GreatNebula.ActionName()),

                // GNB PvP
                KeyValuePair.Create("Rough Divide", GNBPvP.RoughDivide.ActionName()),
                #endregion
            ];
        }
    }
}
