using System;
using System.Collections.Generic;
using WrathCombo.Combos.PvE;
using WrathCombo.Combos.PvP;
using WrathCombo.Extensions;

namespace WrathCombo.Resources.Dictionary.Chinese.Description
{
    public static class MCHSkills
    {
        public static IEnumerable<KeyValuePair<string, string>> GetSkills()
        {
            return
            [
                // Generated by the String Extraction and Translation Tool  
                // Model: DeepSeek v3  
                // Temperature: 0.1  
                // Generation Time: 2025-03-13 18:45:21  
                #region MCH
                // Basic Shots
                KeyValuePair.Create("Heated Clean Shot", MCH.HeatedCleanShot.ActionName()),
                KeyValuePair.Create("Clean Shot", MCH.CleanShot.ActionName()),
                KeyValuePair.Create("Heated Split Shot", MCH.HeatedSplitShot.ActionName()),
                KeyValuePair.Create("Split Shot", MCH.SplitShot.ActionName()),
                KeyValuePair.Create("Heated Slug Shot", MCH.HeatedSlugShot.ActionName()),
                KeyValuePair.Create("Slug Shot", MCH.SlugShot.ActionName()),
                KeyValuePair.Create("Gauss Round", MCH.GaussRound.ActionName()),
                KeyValuePair.Create("Ricochet", MCH.Ricochet.ActionName()),

                // Reassemble and Drill
                KeyValuePair.Create("Reassemble", MCH.Reassemble.ActionName()),
                KeyValuePair.Create("Drill", MCH.Drill.ActionName()),

                // Hot Shots
                KeyValuePair.Create("Hot Shot", MCH.HotShot.ActionName()),
                KeyValuePair.Create("Air Anchor", MCH.AirAnchor.ActionName()),

                // Hypercharge and Heatblast
                KeyValuePair.Create("Hypercharge", MCH.Hypercharge.ActionName()),
                KeyValuePair.Create("Heat Blast", MCH.Heatblast.ActionName()),

                // AOE Shots
                KeyValuePair.Create("Spreadshot", MCH.SpreadShot.ActionName()),
                KeyValuePair.Create("Scattergun", MCH.Scattergun.ActionName()),

                // Turrets and Automaton
                KeyValuePair.Create("Auto Crossbow", MCH.AutoCrossbow.ActionName()),
                KeyValuePair.Create("Crossbow", MCH.AutoCrossbow.ActionName()),
                KeyValuePair.Create("Rook Autoturret", MCH.RookAutoturret.ActionName()),
                KeyValuePair.Create("Rook Overdrive", MCH.RookOverdrive.ActionName()),
                KeyValuePair.Create("Automaton Queen", MCH.AutomatonQueen.ActionName()),
                KeyValuePair.Create("Queen Overdrive", MCH.QueenOverdrive.ActionName()),

                // Support and Damage Buffs
                KeyValuePair.Create("Tactician", MCH.Tactician.ActionName()),
                KeyValuePair.Create("Chain Saw", MCH.Chainsaw.ActionName()),
                KeyValuePair.Create("Chainsaw", MCH.Chainsaw.ActionName()),
                KeyValuePair.Create("Bioblaster", MCH.BioBlaster.ActionName()),
                KeyValuePair.Create("BioBlaster", MCH.BioBlaster.ActionName()),
                KeyValuePair.Create("Barrel Stabilizer", MCH.BarrelStabilizer.ActionName()),

                // Wildfire and Dismantle
                KeyValuePair.Create("Wildfire", MCH.Wildfire.ActionName()),
                KeyValuePair.Create("Dismantle", MCH.Dismantle.ActionName()),

                // Flamethrower and Final Abilities
                KeyValuePair.Create("Flamethrower", MCH.Flamethrower.ActionName()),
                KeyValuePair.Create("Blazing Shot", MCH.BlazingShot.ActionName()),
                KeyValuePair.Create("Double Check", MCH.DoubleCheck.ActionName()),
                KeyValuePair.Create("Checkmate", MCH.CheckMate.ActionName()),
                KeyValuePair.Create("Excavator", MCH.Excavator.ActionName()),
                KeyValuePair.Create("Full Metal Field", MCH.FullMetalField.ActionName()),
                #endregion

                #region MCHPvP
                KeyValuePair.Create("Analysis", MCHPvP.Analysis.ActionName()),
                KeyValuePair.Create("Marksman Spite", MCHPvP.MarksmanSpite.ActionName()),
                KeyValuePair.Create("Marksmans Spite", MCHPvP.MarksmanSpite.ActionName()),
                #endregion
            ];
        }
    }
}
