using System;
using System.Collections.Generic;
using WrathCombo.Combos.PvE;
using WrathCombo.Combos.PvP;
using WrathCombo.Extensions;

namespace WrathCombo.Resources.Dictionary.Chinese.Description
{
    public static class MNKSkills
    {
        public static IEnumerable<KeyValuePair<string, string>> GetSkills()
        {
            return
            [
                // Generated by the String Extraction and Translation Tool  
                // Model: DeepSeek v3  
                // Temperature: 0.1  
                // Generation Time: 2025-03-13 18:45:21  
                #region MNK
                // Basic Attacks
                KeyValuePair.Create("Bootshine", MNK.Bootshine.ActionName()),
                KeyValuePair.Create("True Strike", MNK.TrueStrike.ActionName()),
                KeyValuePair.Create("Snap Punch", MNK.SnapPunch.ActionName()),

                // Meditation and Steel
                KeyValuePair.Create("Steeled Meditation", MNK.SteeledMeditation.ActionName()),
                KeyValuePair.Create("Steel Peak", MNK.SteelPeak.ActionName()),

                // Twin Snakes and Arm
                KeyValuePair.Create("Twin Snakes", MNK.TwinSnakes.ActionName()),
                KeyValuePair.Create("Arm of the Destroyer", MNK.ArmOfTheDestroyer.ActionName()),
                KeyValuePair.Create("Arms of the Destroyer", MNK.ArmOfTheDestroyer.ActionName()),

                // Damage and AOE
                KeyValuePair.Create("Demolish", MNK.Demolish.ActionName()),
                KeyValuePair.Create("Mantra", MNK.Mantra.ActionName()),
                KeyValuePair.Create("Dragon Kick", MNK.DragonKick.ActionName()),
                KeyValuePair.Create("Rockbreaker", MNK.Rockbreaker.ActionName()),

                // Riddle and Meditation Forms
                KeyValuePair.Create("Howling Fist", MNK.HowlingFist.ActionName()),
                KeyValuePair.Create("Four Point Fury", MNK.FourPointFury.ActionName()),
                KeyValuePair.Create("Perfect Balance", MNK.PerfectBalance.ActionName()),
                KeyValuePair.Create("Form Shift", MNK.FormShift.ActionName()),

                // Chakra and Mastery
                KeyValuePair.Create("The Forbidden Chakra", MNK.TheForbiddenChakra.ActionName()),
                KeyValuePair.Create("Masterful Blitz", MNK.MasterfulBlitz.ActionName()),

                // Riddles and Replies
                KeyValuePair.Create("Riddle of Earth", MNK.RiddleOfEarth.ActionName()),
                KeyValuePair.Create("Earth's Reply", MNK.EarthsReply.ActionName()),
                KeyValuePair.Create("Brotherhood", MNK.Brotherhood.ActionName()),
                KeyValuePair.Create("Riddle of Wind", MNK.RiddleOfWind.ActionName()),

                // Meditation Forms
                KeyValuePair.Create("Inspirited Meditation", MNK.InspiritedMeditation.ActionName()),
                KeyValuePair.Create("Enlightened Meditation", MNK.EnlightenedMeditation.ActionName()),
                KeyValuePair.Create("Enlightenment", MNK.Enlightenment.ActionName()),

                // Special Attacks
                KeyValuePair.Create("Six Sided Star", MNK.SixSidedStar.ActionName()),
                KeyValuePair.Create("Shadow of the Destroyer", MNK.ShadowOfTheDestroyer.ActionName()),
                KeyValuePair.Create("Rising Phoenix", MNK.RisingPhoenix.ActionName()),

                // Reply and Forbidden Meditation
                KeyValuePair.Create("Wind's Reply", MNK.WindsReply.ActionName()),
                KeyValuePair.Create("Forbidden Meditation", MNK.ForbiddenMeditation.ActionName()),

                // Animal Shifts
                KeyValuePair.Create("Leaping Opo", MNK.LeapingOpo.ActionName()),
                KeyValuePair.Create("Rising Raptor", MNK.RisingRaptor.ActionName()),
                KeyValuePair.Create("Pouncing Coeurl", MNK.PouncingCoeurl.ActionName()),

                // Other Special Abilities
                KeyValuePair.Create("Elixir Burst", MNK.ElixirBurst.ActionName()),
                #endregion
                
                #region MNKPvP
                KeyValuePair.Create("Phantom Rush", MNKPvP.PhantomRush.ActionName()),
                KeyValuePair.Create("Meteordrive", MNKPvP.Meteordrive.ActionName()),
                KeyValuePair.Create("Meteodrive", MNKPvP.Meteordrive.ActionName()),
                KeyValuePair.Create("Flint's Reply", MNKPvP.FlintsReply.ActionName()),
                KeyValuePair.Create("Flints Reply", MNKPvP.FlintsReply.ActionName()),
                #endregion
            ];
        }
    }
}
