using System;
using System.Collections.Generic;
using WrathCombo.Combos.PvE;
using WrathCombo.Combos.PvP;
using WrathCombo.Extensions;

namespace WrathCombo.Resources.Dictionary.Chinese.Description
{
    public static class PCTSkills
    {
        public static IEnumerable<KeyValuePair<string, string>> GetSkills()
        {
            return
            [
                // Generated by the String Extraction and Translation Tool  
                // Model: DeepSeek v3  
                // Temperature: 0.1  
                // Generation Time: 2025-03-13 18:45:21  
                #region PCT
                KeyValuePair.Create("Holy in White", PCTPvP.HolyInWhite.ActionName()),
                KeyValuePair.Create("Stone in Yellow", PCT.StoneinYellow.ActionName()),
                KeyValuePair.Create("Claw Motif", PCT.ClawMotif.ActionName()),
                KeyValuePair.Create("Clawed Muse", PCT.ClawedMuse.ActionName()),
                KeyValuePair.Create("Comet in Black", PCT.CometinBlack.ActionName()),
                KeyValuePair.Create("Creature Motif", PCT.CreatureMotif.ActionName()),
                KeyValuePair.Create("Aero in Green", PCT.AeroInGreen.ActionName()),
                KeyValuePair.Create("Water in Blue", PCT.WaterInBlue.ActionName()),
                KeyValuePair.Create("Aero II in Green", PCT.AeroIIinGreen.ActionName()),
                KeyValuePair.Create("Hammer Motif", PCT.HammerMotif.ActionName()),
                KeyValuePair.Create("Winged Muse", PCT.WingedMuse.ActionName()),
                KeyValuePair.Create("Striking Muse", PCT.StrikingMuse.ActionName()),
                KeyValuePair.Create("Starry Muse", PCT.StarryMuse.ActionName()),
                KeyValuePair.Create("Hammer Stamp", PCT.HammerStamp.ActionName()),
                KeyValuePair.Create("Hammer Brush", PCT.HammerBrush.ActionName()),
                KeyValuePair.Create("Polishing Hammer", PCT.PolishingHammer.ActionName()),
                KeyValuePair.Create("Starry Sky Motif", PCT.StarrySkyMotif.ActionName()),
                KeyValuePair.Create("Landscape Motif", PCT.LandscapeMotif.ActionName()),
                KeyValuePair.Create("Living Muse", PCT.LivingMuse.ActionName()),
                KeyValuePair.Create("Maw Motif", PCT.MawMotif.ActionName()),
                KeyValuePair.Create("Mog of the Ages", PCT.MogoftheAges.ActionName()),
                KeyValuePair.Create("Pom Motif", PCT.PomMotif.ActionName()),
                KeyValuePair.Create("Pom Muse", PCT.PomMuse.ActionName()),
                KeyValuePair.Create("Rainbow Drip", PCT.RainbowDrip.ActionName()),
                KeyValuePair.Create("Retribution of the Madeen", PCT.RetributionoftheMadeen.ActionName()),
                KeyValuePair.Create("Scenic Muse", PCT.ScenicMuse.ActionName()),
                KeyValuePair.Create("Smudge", PCT.Smudge.ActionName()),
                KeyValuePair.Create("Star Prism", PCT.StarPrism.ActionName()),
                KeyValuePair.Create("Steel Muse", PCT.SteelMuse.ActionName()),
                KeyValuePair.Create("Subtractive Palette", PCT.SubtractivePalette.ActionName()),
                KeyValuePair.Create("Stone II in Yellow", PCT.StoneIIinYellow.ActionName()),
                KeyValuePair.Create("Weapon Motif", PCT.WeaponMotif.ActionName()),
                KeyValuePair.Create("Wing Motif", PCT.WingMotif.ActionName()),
                #endregion
                                
                #region PCTPvP
                KeyValuePair.Create("Tempera Coat", PCTPvP.TemperaCoat.ActionName()),
                KeyValuePair.Create("Mog Of The Ages", PCTPvP.MogOfTheAges.ActionName()),
                #endregion
            ];
        }
    }
}
