using System;
using System.Collections.Generic;
using WrathCombo.Combos.PvE;
using WrathCombo.Combos.PvP;
using WrathCombo.Extensions;

namespace WrathCombo.Resources.Dictionary.Chinese.Description
{
    public static class PLDSkills
    {
        public static IEnumerable<KeyValuePair<string, string>> GetSkills()
        {
            return
            [
                // Generated by the String Extraction and Translation Tool  
                // Model: DeepSeek v3  
                // Temperature: 0.1  
                // Generation Time: 2025-03-13 18:45:21  
                #region PLD
                KeyValuePair.Create("Fast Blade", PLD.FastBlade.ActionName()),
                KeyValuePair.Create("Riot Blade", PLD.RiotBlade.ActionName()),
                KeyValuePair.Create("Shield Bash", PLD.ShieldBash.ActionName()),
                KeyValuePair.Create("Sentinel", PLD.Sentinel.ActionName()),
                KeyValuePair.Create("Rage of Halone", PLD.RageOfHalone.ActionName()),
                KeyValuePair.Create("Bulwark", PLD.Bulwark.ActionName()),
                KeyValuePair.Create("Shield Lob", PLD.ShieldLob.ActionName()),
                KeyValuePair.Create("Iron Will", PLD.IronWill.ActionName()),
                KeyValuePair.Create("Spirits Within", PLD.SpiritsWithin.ActionName()),
                KeyValuePair.Create("Hallowed Ground", PLD.HallowedGround.ActionName()),
                KeyValuePair.Create("Goring Blade", PLD.GoringBlade.ActionName()),
                KeyValuePair.Create("Divine Veil", PLD.DivineVeil.ActionName()),
                KeyValuePair.Create("Royal Authority", PLD.RoyalAuthority.ActionName()),
                KeyValuePair.Create("Total Eclipse", PLD.TotalEclipse.ActionName()),
                KeyValuePair.Create("Intervention", PLD.Intervention.ActionName()),
                KeyValuePair.Create("Requiescat", PLD.Requiescat.ActionName()),
                KeyValuePair.Create("Imperator", PLD.Imperator.ActionName()),
                KeyValuePair.Create("Holy Spirit", PLD.HolySpirit.ActionName()),
                KeyValuePair.Create("Prominence", PLD.Prominence.ActionName()),
                KeyValuePair.Create("Holy Circle", PLD.HolyCircle.ActionName()),
                KeyValuePair.Create("Confiteor", PLD.Confiteor.ActionName()),
                KeyValuePair.Create("Expiacion", PLD.Expiacion.ActionName()),
                KeyValuePair.Create("Blade of Faith", PLD.BladeOfFaith.ActionName()),
                KeyValuePair.Create("Blade of Truth", PLD.BladeOfTruth.ActionName()),
                KeyValuePair.Create("Blade of Valor", PLD.BladeOfValor.ActionName()),
                KeyValuePair.Create("Fight or Flight", PLD.FightOrFlight.ActionName()),
                KeyValuePair.Create("Atonement", PLD.Atonement.ActionName()),
                KeyValuePair.Create("Supplication", PLD.Supplication.ActionName()), // Second Atonement
                KeyValuePair.Create("Sepulchre", PLD.Sepulchre.ActionName()), // Third Atonement
                KeyValuePair.Create("Intervene", PLD.Intervene.ActionName()),
                KeyValuePair.Create("Blade of Honor", PLD.BladeOfHonor.ActionName()),
                KeyValuePair.Create("Sheltron", PLD.Sheltron.ActionName()),
                KeyValuePair.Create("Clemency", PLD.Clemency.ActionName()),

                // Buffs
                KeyValuePair.Create("Divine Might", PLD.Buffs.DivineMight.StatusName()),
                
                #endregion

                #region PLDPvP
                KeyValuePair.Create("Shield Smite", PLDPvP.ShieldSmite.ActionName()),
                KeyValuePair.Create("Phalanx", PLDPvP.Phalanx.ActionName()),
                #endregion
            ];
        }
    }
}
