using System;
using System.Collections.Generic;
using WrathCombo.Combos.PvE;
using WrathCombo.Combos.PvP;
using WrathCombo.Extensions;

namespace WrathCombo.Resources.Dictionary.Chinese.Description
{
    public static class RDMSkills
    {
        public static IEnumerable<KeyValuePair<string, string>> GetSkills()
        {
            return
            [
                // Generated by the String Extraction and Translation Tool  
                // Model: DeepSeek v3  
                // Temperature: 0.1  
                // Generation Time: 2025-03-13 18:45:21  
                #region RDM
                // "Balance Standard Opener" / "GapClosing Adjusted Standard Opener" moved to
                // GenesisDescriptions.cs: BRDDescriptions.cs's bare "Standard Opener" fragment
                // (processed earlier, Description layer) was shadowing these full-sentence
                // keys here in the Skill layer, making them dead code.
                KeyValuePair.Create("Shifts the melee a little bit to put a gapcloser in", "些微調整近戰段落以插入位移技能"),
                KeyValuePair.Create("Veraero III", RDM.Veraero3.ActionName()),
                KeyValuePair.Create("Veraero II", RDM.Veraero2.ActionName()),
                KeyValuePair.Create("Veraero", RDM.Veraero.ActionName()),
                KeyValuePair.Create("Verthunder III", RDM.Verthunder3.ActionName()),
                KeyValuePair.Create("Verthunder II", RDM.Verthunder2.ActionName()),
                KeyValuePair.Create("Verthunder", RDM.Verthunder.ActionName()),
                KeyValuePair.Create("Enchanted Redoublement", RDM.EnchantedRedoublement.ActionName()),
                KeyValuePair.Create("Redoublement", RDM.Redoublement.ActionName()),
                KeyValuePair.Create("Enchanted Zwerchhau", RDM.EnchantedZwerchhau.ActionName()),
                KeyValuePair.Create("Zwerchhau", RDM.Zwerchhau.ActionName()),
                KeyValuePair.Create("Enchanted Riposte", RDM.EnchantedRiposte.ActionName()),
                KeyValuePair.Create("Riposte", RDM.Riposte.ActionName()),
                KeyValuePair.Create("Scatter", RDM.Scatter.ActionName()),
                KeyValuePair.Create("Verstone", RDM.Verstone.ActionName()),
                KeyValuePair.Create("Verfire", RDM.Verfire.ActionName()),
                KeyValuePair.Create("Vercure", RDM.Vercure.ActionName()),
                KeyValuePair.Create("Jolt III", RDM.Jolt3.ActionName()),
                KeyValuePair.Create("Jolt II", RDM.Jolt2.ActionName()),
                // 複數形（"Replaces Jolts."）加上詞界比對後需要自己的條目。
                KeyValuePair.Create("Jolts", RDM.Jolt.ActionName()),
                KeyValuePair.Create("Jolt", RDM.Jolt.ActionName()),
                KeyValuePair.Create("Verholy", RDM.Verholy.ActionName()),
                KeyValuePair.Create("Verflare", RDM.Verflare.ActionName()),
                KeyValuePair.Create("Fleche", RDM.Fleche.ActionName()),
                KeyValuePair.Create("Contre Sixte", RDM.ContreSixte.ActionName()),
                KeyValuePair.Create("Engagement", RDM.Engagement.ActionName()),
                KeyValuePair.Create("Verraise", RDM.Verraise.ActionName()),
                KeyValuePair.Create("Scorch", RDM.Scorch.ActionName()),
                KeyValuePair.Create("Resolution", RDM.Resolution.ActionName()),
                KeyValuePair.Create("Enchanted Moulinet Trois", RDM.EnchantedMoulinetTrois.ActionName()),
                KeyValuePair.Create("Enchanted Moulinet Deux", RDM.EnchantedMoulinetDeux.ActionName()),
                KeyValuePair.Create("Enchanted Moulinet", RDM.EnchantedMoulinet.ActionName()),
                KeyValuePair.Create("Moulinet", RDM.Moulinet.ActionName()),
                KeyValuePair.Create("Corps-a-corps", RDM.Corpsacorps.ActionName()),
                KeyValuePair.Create("Corps a Corps", RDM.Corpsacorps.ActionName()),
                KeyValuePair.Create("Displacement", RDM.Displacement.ActionName()),
                KeyValuePair.Create("Reprise", RDM.Reprise.ActionName()),
                KeyValuePair.Create("Vice of Thorns", RDM.ViceOfThorns.ActionName()),
                KeyValuePair.Create("Grand Impact", RDM.GrandImpact.ActionName()),
                KeyValuePair.Create("Prefulgence", RDM.Prefulgence.ActionName()),

                // Buffs
                KeyValuePair.Create("Acceleration", RDM.Acceleration.ActionName()),
                KeyValuePair.Create("Manafication", RDM.Manafication.ActionName()),
                KeyValuePair.Create("Embolden", RDM.Embolden.ActionName()),
                KeyValuePair.Create("Magick Barrier", RDM.MagickBarrier.ActionName()),
                #endregion

                #region RDMPvP
                KeyValuePair.Create("Forte", RDMPvP.Forte.ActionName()),
                #endregion
            ];
        }
    }
}
