using System;
using System.Collections.Generic;
using WrathCombo.Combos.PvE;
using WrathCombo.Combos.PvP;
using WrathCombo.Extensions;

namespace WrathCombo.Resources.Dictionary.Chinese.Description
{
    public static class RPRSkills
    {
        public static IEnumerable<KeyValuePair<string, string>> GetSkills()
        {
            return
            [
                // Generated by the String Extraction and Translation Tool  
                // Model: DeepSeek v3  
                // Temperature: 0.1  
                // Generation Time: 2025-03-13 18:45:21  
                #region RPR
                // Single Target
                //KeyValuePair.Create("Lemures Slice", RPR.LemuresSlice.ActionName()),
                KeyValuePair.Create("Lemure's Slice", RPR.LemuresSlice.ActionName()),
                KeyValuePair.Create("Soul Slice", RPR.SoulSlice.ActionName()),
                KeyValuePair.Create("Infernal Slice", RPR.InfernalSlice.ActionName()),
                KeyValuePair.Create("Waxing Slice", RPR.WaxingSlice.ActionName()),
                KeyValuePair.Create("Slice", RPR.Slice.ActionName()),
                KeyValuePair.Create("Shadow of Death", RPR.ShadowOfDeath.ActionName()),
                KeyValuePair.Create("Shadow Of Death", RPR.ShadowOfDeath.ActionName()),

                // AoE
                KeyValuePair.Create("Spinning Scythe", RPR.SpinningScythe.ActionName()),
                KeyValuePair.Create("Nightmare Scythe", RPR.NightmareScythe.ActionName()),
                KeyValuePair.Create("Whorl of Death", RPR.WhorlOfDeath.ActionName()),
                KeyValuePair.Create("Whorl Of Death", RPR.WhorlOfDeath.ActionName()),
                KeyValuePair.Create("Soul Scythe", RPR.SoulScythe.ActionName()),
                                
                // Enshroud
                KeyValuePair.Create("Enshroud", RPR.Enshroud.ActionName()),
                KeyValuePair.Create("Communio", RPR.Communio.ActionName()),
                KeyValuePair.Create("Lemure's Scythe", RPR.LemuresScythe.ActionName()),
                KeyValuePair.Create("Void Reaping", RPR.VoidReaping.ActionName()),
                KeyValuePair.Create("Cross Reaping", RPR.CrossReaping.ActionName()),
                KeyValuePair.Create("Grim Reaping", RPR.GrimReaping.ActionName()),
                KeyValuePair.Create("Sacrificium", RPR.Sacrificium.ActionName()),
                KeyValuePair.Create("Perfectio", RPR.Perfectio.ActionName()),

                // Unveiled
                KeyValuePair.Create("Unveiled Gibbet", RPR.UnveiledGibbet.ActionName()),
                KeyValuePair.Create("Unveiled Gallows", RPR.UnveiledGallows.ActionName()),
                KeyValuePair.Create("Executioner's Gibbet", RPR.ExecutionersGibbet.ActionName()),
                KeyValuePair.Create("Executioner's Gallows", RPR.ExecutionersGallows.ActionName()),
                KeyValuePair.Create("Executioner's Guillotine", RPR.ExecutionersGuillotine.ActionName()),
                KeyValuePair.Create("Gibbet", RPR.Gibbet.ActionName()),
                KeyValuePair.Create("Gallows", RPR.Gallows.ActionName()),
                KeyValuePair.Create("Guillotine", RPR.Guillotine.ActionName()),

                // Reaver
                KeyValuePair.Create("Blood Stalk", RPR.BloodStalk.ActionName()),
                KeyValuePair.Create("Bloodstalk", RPR.BloodStalk.ActionName()),
                KeyValuePair.Create("Grim Swathe", RPR.GrimSwathe.ActionName()),
                KeyValuePair.Create("Gluttony", RPR.Gluttony.ActionName()),

                // Sacrifice
                KeyValuePair.Create("Arcane Circle", RPR.ArcaneCircle.ActionName()),
                KeyValuePair.Create("Plentiful Harvest", RPR.PlentifulHarvest.ActionName()),

                // Miscellaneous
                KeyValuePair.Create("Hell's Ingress", RPR.HellsIngress.ActionName()),
                KeyValuePair.Create("Hell's Egress", RPR.HellsEgress.ActionName()),
                KeyValuePair.Create("Regress", RPR.Regress.ActionName()),
                KeyValuePair.Create("Harpe", RPR.Harpe.ActionName()),
                KeyValuePair.Create("Soulsow", RPR.Soulsow.ActionName()),
                KeyValuePair.Create("Harvest Moon", RPR.HarvestMoon.ActionName()),

                // Buffs
                KeyValuePair.Create("Immortal Sacrifice", RPR.Buffs.ImmortalSacrifice.StatusName()),
                KeyValuePair.Create("Threshold", RPR.Buffs.Threshold.StatusName()),
                KeyValuePair.Create("Soul Reaver", RPR.Buffs.SoulReaver.StatusName()),
                #endregion

                #region RPRPvP
                KeyValuePair.Create("Death Warrant", RPRPvP.DeathWarrant.ActionName()),
                KeyValuePair.Create("Arcane Crest", RPRPvP.ArcaneCrest.ActionName()),
                #endregion
            ];
        }
    }
}
