using System;
using System.Collections.Generic;
using WrathCombo.Combos.PvE;
using WrathCombo.Combos.PvP;
using WrathCombo.Extensions;

namespace WrathCombo.Resources.Dictionary.Chinese.Description
{
    public static class SAMSkills
    {
        public static IEnumerable<KeyValuePair<string, string>> GetSkills()
        {
            return
            [
                // Generated by the String Extraction and Translation Tool  
                // Model: DeepSeek v3  
                // Temperature: 0.1  
                // Generation Time: 2025-03-13 18:45:21  
                #region SAM
                // Samurai Actions
                KeyValuePair.Create("Hakaze", SAM.Hakaze.ActionName()),
                KeyValuePair.Create("Yukikaze", SAM.Yukikaze.ActionName()),
                KeyValuePair.Create("Gekko", SAM.Gekko.ActionName()),
                KeyValuePair.Create("Enpi", SAM.Enpi.ActionName()),
                KeyValuePair.Create("Jinpu", SAM.Jinpu.ActionName()),
                KeyValuePair.Create("Kasha", SAM.Kasha.ActionName()),
                KeyValuePair.Create("Shifu", SAM.Shifu.ActionName()),
                KeyValuePair.Create("Mangetsu", SAM.Mangetsu.ActionName()),
                KeyValuePair.Create("Fuga", SAM.Fuga.ActionName()),
                KeyValuePair.Create("Oka", SAM.Oka.ActionName()),
                KeyValuePair.Create("Kaeshi Higanbana", SAM.KaeshiHiganbana.ActionName()),
                KeyValuePair.Create("Higanbana", SAM.Higanbana.ActionName()),
                KeyValuePair.Create("Tenka Goken", SAM.TenkaGoken.ActionName()),
                KeyValuePair.Create("Midare: Setsugekka", SAM.MidareSetsugekka.ActionName()),
                KeyValuePair.Create("Hissatsu: Shinten", SAM.Shinten.ActionName()),
                KeyValuePair.Create("Shinten", SAM.Shinten.ActionName()),
                KeyValuePair.Create("Hissatsu: Kyuten", SAM.Kyuten.ActionName()),
                KeyValuePair.Create("Kyuten", SAM.Kyuten.ActionName()),
                KeyValuePair.Create("Hagakure", SAM.Hagakure.ActionName()),
                KeyValuePair.Create("Guren", SAM.Guren.ActionName()),
                KeyValuePair.Create("Senei", SAM.Senei.ActionName()),
                KeyValuePair.Create("Meikyo Shisui", SAM.MeikyoShisui.ActionName()),
                KeyValuePair.Create("Seigan", SAM.Seigan.ActionName()),
                KeyValuePair.Create("Third Eye", SAM.ThirdEye.ActionName()),
                KeyValuePair.Create("Iaijutsu", SAM.Iaijutsu.ActionName()),
                KeyValuePair.Create("Iajutsu", SAM.Iaijutsu.ActionName()),
                KeyValuePair.Create("Tsubame-gaeshi", SAM.TsubameGaeshi.ActionName()),
                KeyValuePair.Create("Tsubame-Gaeshi", SAM.TsubameGaeshi.ActionName()),
                KeyValuePair.Create("Shoha", SAM.Shoha.ActionName()),
                KeyValuePair.Create("Ikishoten", SAM.Ikishoten.ActionName()),
                KeyValuePair.Create("Fuko", SAM.Fuko.ActionName()),
                KeyValuePair.Create("Ogi Namikiri", SAM.OgiNamikiri.ActionName()),
                KeyValuePair.Create("Kaeshi Namikiri", SAM.KaeshiNamikiri.ActionName()),
                KeyValuePair.Create("Kaeshi: Namikiri", SAM.KaeshiNamikiri.ActionName()),
                KeyValuePair.Create("Kaeshi:Namikiri", SAM.KaeshiNamikiri.ActionName()),
                KeyValuePair.Create("Yaten", SAM.Yaten.ActionName()),
                KeyValuePair.Create("Hissatsu: Gyoten", SAM.Gyoten.ActionName()),
                KeyValuePair.Create("Gyoten", SAM.Gyoten.ActionName()),
                KeyValuePair.Create("Kaeshi: Setsugekka", SAM.KaeshiSetsugekka.ActionName()),
                KeyValuePair.Create("Tendo Goken", SAM.TendoGoken.ActionName()),
                KeyValuePair.Create("Tendo Kaeshi Setsugekka", SAM.TendoKaeshiSetsugekka.ActionName()),
                KeyValuePair.Create("Kaeshi Setsugekka", SAM.KaeshiSetsugekka.ActionName()),
                KeyValuePair.Create("Zanshin", SAM.Zanshin.ActionName()),
                KeyValuePair.Create("Tendo Setsugekka", SAM.TendoSetsugekka.ActionName()),
                KeyValuePair.Create("Tengentsu", SAM.Tengentsu.ActionName()),
                KeyValuePair.Create("Gyofu", SAM.Gyofu.ActionName()),
                KeyValuePair.Create("Kaeshi: Goken", "回返五劍"),
                KeyValuePair.Create("Namikiri", "斬浪"),
                #endregion

                #region SAMPvP
                KeyValuePair.Create("Chiten", SAMPvP.Chiten.ActionName()),
                KeyValuePair.Create("Mineuchi", SAMPvP.Mineuchi.ActionName()),
                KeyValuePair.Create("Soten", SAMPvP.Soten.ActionName()),
                KeyValuePair.Create("Zantetsuken", SAMPvP.Zantetsuken.ActionName()),
                KeyValuePair.Create("Kaiten", SAMPvP.Buffs.Kaiten.StatusName()),
                KeyValuePair.Create("Kuzushi", SAMPvP.Debuffs.Kuzushi.StatusName()),
                #endregion

            ];
        }
    }
}
