using System;
using System.Collections.Generic;
using WrathCombo.Combos.PvE;
using WrathCombo.Combos.PvP;
using WrathCombo.Extensions;

namespace WrathCombo.Resources.Dictionary.Chinese.Description
{
    public static class SGESkills
    {
        public static IEnumerable<KeyValuePair<string, string>> GetSkills()
        {
            return
            [
                // Generated by the String Extraction and Translation Tool  
                // Model: DeepSeek v3  
                // Temperature: 0.1  
                // Generation Time: 2025-03-13 18:45:21  
                #region SGE
                // Heals and Shields
                KeyValuePair.Create("Eukrasian Diagnosis", SGE.EukrasianDiagnosis.ActionName()),
                KeyValuePair.Create("Eukrasian Prognosis", SGE.EukrasianPrognosis.ActionName()),
                KeyValuePair.Create("Physis II", SGE.Physis2.ActionName()),
                KeyValuePair.Create("Diagnosis", SGE.Diagnosis.ActionName()),
                KeyValuePair.Create("Prognosis", SGE.Prognosis.ActionName()),
                KeyValuePair.Create("Physis", SGE.Physis.ActionName()),
                KeyValuePair.Create("Druochole", SGE.Druochole.ActionName()),
                KeyValuePair.Create("Kerachole", SGE.Kerachole.ActionName()),
                KeyValuePair.Create("Ixochole", SGE.Ixochole.ActionName()),
                KeyValuePair.Create("Pepsis", SGE.Pepsis.ActionName()),
                KeyValuePair.Create("Taurochole", SGE.Taurochole.ActionName()),
                KeyValuePair.Create("Haima", SGE.Haima.ActionName()),
                KeyValuePair.Create("Panhaima", SGE.Panhaima.ActionName()),
                KeyValuePair.Create("Holos", SGE.Holos.ActionName()),
                KeyValuePair.Create("Egeiro", SGE.Egeiro.ActionName()),

                // DPS
                KeyValuePair.Create("Eukrasian Dosis III", SGE.EukrasianDosis3.ActionName()),
                KeyValuePair.Create("Dosis III", SGE.Dosis3.ActionName()),
                KeyValuePair.Create("Eukrasian Dosis II", SGE.EukrasianDosis2.ActionName()),
                KeyValuePair.Create("Dosis II", SGE.Dosis2.ActionName()),
                KeyValuePair.Create("Eukrasian Dosis", SGE.EukrasianDosis.ActionName()),
                KeyValuePair.Create("Dosis", SGE.Dosis.ActionName()),
                KeyValuePair.Create("Eukrasian Dyskrasia", SGE.EukrasianDyskrasia.ActionName()),
                KeyValuePair.Create("Phlegma III", SGE.Phlegma3.ActionName()),
                KeyValuePair.Create("Phlegma II", SGE.Phlegma2.ActionName()),
                KeyValuePair.Create("Phlegma", SGE.Phlegma.ActionName()),
                KeyValuePair.Create("Dyskrasia II", SGE.Dyskrasia2.ActionName()),
                KeyValuePair.Create("Dyskrasia", SGE.Dyskrasia.ActionName()),
                KeyValuePair.Create("Toxikon II", SGE.Toxikon2.ActionName()),
                // Full-sentence entries placed BEFORE the bare "Toxikon"/"Pneuma" fragments
                // below -- otherwise those fire first (same array) and the exact-string
                // matches here become unreachable dead code.
                KeyValuePair.Create("Uses Toxikon opener", $"使用{SGE.Toxikon.ActionName()}起手式"),
                KeyValuePair.Create("Toxikon", SGE.Toxikon.ActionName()),
                KeyValuePair.Create("Uses Pneuma opener", $"使用{SGE.Pneuma.ActionName()}起手式"),
                KeyValuePair.Create("Pneuma", SGE.Pneuma.ActionName()),
                KeyValuePair.Create("Psyche", SGE.Psyche.ActionName()),

                // Buffs
                KeyValuePair.Create("Soteria", SGE.Soteria.ActionName()),
                KeyValuePair.Create("Zoe", SGE.Zoe.ActionName()),
                KeyValuePair.Create("Krasis", SGE.Krasis.ActionName()),
                KeyValuePair.Create("Philosophia", SGE.Philosophia.ActionName()),

                // Other
                KeyValuePair.Create("Kardia", SGE.Kardia.ActionName()),
                KeyValuePair.Create("Eukrasia", SGE.Eukrasia.ActionName()),
                KeyValuePair.Create("Rhizomata", SGE.Rhizomata.ActionName()),
                #endregion
            ];
        }
    }
}
