using System;
using System.Collections.Generic;
using WrathCombo.Combos.PvE;
using WrathCombo.Combos.PvP;
using WrathCombo.Extensions;

namespace WrathCombo.Resources.Dictionary.Chinese.Description
{
    public static class SMNSkills
    {
        public static IEnumerable<KeyValuePair<string, string>> GetSkills()
        {
            return
            [
                // Generated by the String Extraction and Translation Tool  
                // Model: DeepSeek v3  
                // Temperature: 0.1  
                // Generation Time: 2025-03-13 18:45:21  
                #region SMN
                // Traits
                KeyValuePair.Create("Ruin Mastery III", SMN.Traits.RuinMastery3.StatusName()),
                // Summons
                KeyValuePair.Create("Summon Ruby", SMN.SummonRuby.ActionName()),
                KeyValuePair.Create("Summon Topaz", SMN.SummonTopaz.ActionName()),
                KeyValuePair.Create("Summon Emerald", SMN.SummonEmerald.ActionName()),



                KeyValuePair.Create("Summon Carbuncle", SMN.SummonCarbuncle.ActionName()),

                // Summon abilities
                KeyValuePair.Create("Gemshine", SMN.Gemshine.ActionName()),
                KeyValuePair.Create("Precious Brilliance", SMN.PreciousBrilliance.ActionName()),
                KeyValuePair.Create("Dreadwyrm Trance", SMN.DreadwyrmTrance.ActionName()),

                // Summon Ruins
                KeyValuePair.Create("Ruby Ruin III", SMN.RubyRuin3.ActionName()),
                KeyValuePair.Create("Ruby Ruin II", SMN.RubyRuin2.ActionName()),
                KeyValuePair.Create("Ruby Ruin I", SMN.RubyRuin1.ActionName()),
                KeyValuePair.Create("Topaz Ruin III", SMN.TopazRuin3.ActionName()),
                KeyValuePair.Create("Topaz Ruin II", SMN.TopazRuin2.ActionName()),
                KeyValuePair.Create("Topaz Ruin I", SMN.TopazRuin1.ActionName()),
                KeyValuePair.Create("Emerald Ruin III", SMN.EmeralRuin3.ActionName()),
                KeyValuePair.Create("Emerald Ruin II", SMN.EmeralRuin2.ActionName()),
                KeyValuePair.Create("Emerald Ruin I", SMN.EmeralRuin1.ActionName()),

                // Summon Outbursts
                KeyValuePair.Create("Emerald Outburst", SMN.EmeraldOutburst.ActionName()),
                KeyValuePair.Create("Topaz Outburst", SMN.TopazOutburst.ActionName()),
                KeyValuePair.Create("Ruby Outburst", SMN.RubyOutburst.ActionName()),
                KeyValuePair.Create("Outburst", SMN.Outburst.ActionName()),

                // Summon single targets
                KeyValuePair.Create("Ruby Rite", SMN.RubyRite.ActionName()),
                KeyValuePair.Create("Topaz Rite", SMN.TopazRite.ActionName()),
                KeyValuePair.Create("Emerald Rite", SMN.EmeraldRite.ActionName()),

                // Summon AoEs
                KeyValuePair.Create("Ruby Cata", SMN.RubyCata.ActionName()),
                KeyValuePair.Create("Topaz Cata", SMN.TopazCata.ActionName()),
                KeyValuePair.Create("Emerald Cata", SMN.EmeraldCata.ActionName()),

                // Summon Astral Flows
                KeyValuePair.Create("Crimson Cyclone", SMN.CrimsonCyclone.ActionName()), // Dash
                KeyValuePair.Create("Crimson Strike", SMN.CrimsonStrike.ActionName()),  // Melee
                KeyValuePair.Create("Mountain Buster", SMN.MountainBuster.ActionName()),
                KeyValuePair.Create("Slipstream", SMN.Slipstream.ActionName()),

                // Demi summons
                KeyValuePair.Create("Summon Bahamut", SMN.SummonBahamut.ActionName()),
                KeyValuePair.Create("Summon Phoenix", SMN.SummonPhoenix.ActionName()),
                KeyValuePair.Create("Summon Solar Bahamut", SMN.SummonSolarBahamut.ActionName()),

                // Demi summon abilities
                KeyValuePair.Create("Astral Impulse", SMN.AstralImpulse.ActionName()), // Single target Bahamut GCD
                KeyValuePair.Create("Deathflare", SMN.Deathflare.ActionName()),     // Damage oGCD Bahamut
                KeyValuePair.Create("Enkindle Bahamut", SMN.EnkindleBahamut.ActionName()),

                KeyValuePair.Create("Brand of Purgatory", SMN.BrandOfPurgatory.ActionName()), // AoE Phoenix GCD
                KeyValuePair.Create("Rekindle", SMN.Rekindle.ActionName()),         // Healing oGCD Phoenix
                KeyValuePair.Create("Enkindle Phoenix", SMN.EnkindlePhoenix.ActionName()),

                KeyValuePair.Create("Umbral Impulse", SMN.UmbralImpulse.ActionName()),     // Single target Solar Bahamut GCD
                KeyValuePair.Create("Sunflare", SMN.Sunflare.ActionName()),           // Damage oGCD Solar Bahamut
                KeyValuePair.Create("Enkindle Solar Bahamut", SMN.EnkindleSolarBahamut.ActionName()),
                KeyValuePair.Create("Lux Solaris", SMN.LuxSolaris.ActionName()),        // Healing oGCD Solar Bahamut

                // Shared summon abilities
                KeyValuePair.Create("Astral Flow", SMN.AstralFlow.ActionName()),

                // Summoner GCDs
                KeyValuePair.Create("Ruin IV", SMN.Ruin4.ActionName()),
                KeyValuePair.Create("Ruin III", SMN.Ruin3.ActionName()),
                KeyValuePair.Create("Ruin II", SMN.Ruin2.ActionName()),
                KeyValuePair.Create("Ruin", SMN.Ruin.ActionName()),
                KeyValuePair.Create("Tridisaster", SMN.Tridisaster.ActionName()),

                // Summoner AoE
                KeyValuePair.Create("Ruby Disaster", SMN.RubyDisaster.ActionName()),
                KeyValuePair.Create("Topaz Disaster", SMN.TopazDisaster.ActionName()),
                KeyValuePair.Create("Emerald Disaster", SMN.EmeraldDisaster.ActionName()),

                // Summoner oGCDs
                KeyValuePair.Create("Energy Drain", SMN.EnergyDrain.ActionName()),
                KeyValuePair.Create("Fester", SMN.Fester.ActionName()),
                KeyValuePair.Create("Energy Siphon", SMN.EnergySiphon.ActionName()),
                KeyValuePair.Create("Painflare", SMN.Painflare.ActionName()),
                KeyValuePair.Create("Necrotize", SMN.Necrotize.ActionName()),
                KeyValuePair.Create("Searing Flash", SMN.SearingFlash.ActionName()),
                KeyValuePair.Create("Exodus", SMN.Exodus.ActionName()),

                // Buff 
                KeyValuePair.Create("Radiant Aegis", SMN.RadiantAegis.ActionName()),
                KeyValuePair.Create("Aethercharge", SMN.Aethercharge.ActionName()),
                KeyValuePair.Create("Searing Light", SMN.SearingLight.ActionName()),
                #endregion

                // Manually added
                KeyValuePair.Create("Solar Bahamut Burst", "烈日龍神迸發"),
                KeyValuePair.Create("Bahamut Burst", "龍神迸發"),

            ];
        }
    }
}
