using System;
using System.Collections.Generic;
using System.Text.RegularExpressions;
using WrathCombo.Combos.PvE;
using WrathCombo.Combos.PvP;
using WrathCombo.Extensions;

namespace WrathCombo.Resources.Dictionary.Chinese.Description
{
    public static class WHMSkills
    {
        public static IEnumerable<KeyValuePair<string, string>> GetSkills()
        {
            return
            [
                // Generated by the String Extraction and Translation Tool  
                // Model: DeepSeek v3  
                // Temperature: 0.1  
                // Generation Time: 2025-03-13 18:45:21  
                #region WHM                
                // Heals
                KeyValuePair.Create("Adds Cure 3 to Burst combo when the Cure 3 Ready buff is under 6 seconds", $"當{WHM.Cure3.ActionName()}預備buff剩餘時間低於6秒時，將{WHM.Cure3.ActionName()}加入爆發連段"),
                KeyValuePair.Create("Cure III", WHM.Cure3.ActionName()),
                KeyValuePair.Create("Cure II", WHM.Cure2.ActionName()),
                KeyValuePair.Create("Cure", WHM.Cure.ActionName()),
                KeyValuePair.Create("Regen", WHM.Regen.ActionName()),
                KeyValuePair.Create("Afflatus Solace", WHM.AfflatusSolace.ActionName()),
                KeyValuePair.Create("Afflatus Rapture", WHM.AfflatusRapture.ActionName()),
                KeyValuePair.Create("Benediction", WHM.Benediction.ActionName()),
                KeyValuePair.Create("Afflatus Misery", WHM.AfflatusMisery.ActionName()),
                KeyValuePair.Create("Medica III", WHM.Medica3.ActionName()),
                KeyValuePair.Create("Medica II", WHM.Medica2.ActionName()),
                KeyValuePair.Create("Medica", WHM.Medica1.ActionName()),
                KeyValuePair.Create("Tetragrammaton", WHM.Tetragrammaton.ActionName()),
                KeyValuePair.Create("Divine Benison", WHM.DivineBenison.ActionName()),
                KeyValuePair.Create("Aquaveil", WHM.Aquaveil.ActionName()),
                KeyValuePair.Create("Divine Caress", WHM.DivineCaress.ActionName()),

                // DPS
                //KeyValuePair.Create("Glare1", WHM.Glare1.ActionName()),
                //KeyValuePair.Create("Glare3", WHM.Glare3.ActionName()),
                KeyValuePair.Create("Glare IV", WHM.Glare4.ActionName()),
                // 複數形（"Glares/Stones/Aeros/Dia"、"Apply options to all Stones and Glares."）
                // 需要自己的條目，否則加上詞界後就不再被翻譯。
                KeyValuePair.Create("Glares", WHM.Glare1.ActionName()),
                KeyValuePair.Create("Glare", WHM.Glare1.ActionName()),
                KeyValuePair.Create("Stones", WHM.Stone1.ActionName()),
                KeyValuePair.Create("Stone", WHM.Stone1.ActionName()),
                KeyValuePair.Create("Stone1", WHM.Stone1.ActionName()),
                KeyValuePair.Create("Stone2", WHM.Stone2.ActionName()),
                KeyValuePair.Create("Stone3", WHM.Stone3.ActionName()),
                KeyValuePair.Create("Stone4", WHM.Stone4.ActionName()),
                KeyValuePair.Create("Assize", WHM.Assize.ActionName()),
                KeyValuePair.Create("Holy III", WHM.Holy3.ActionName()),
                KeyValuePair.Create("Holy", WHM.Holy.ActionName()),

                // DoT
                KeyValuePair.Create("Aeros", WHM.Aero.ActionName()),
                KeyValuePair.Create("Aero", WHM.Aero.ActionName()),
                KeyValuePair.Create("Aero2", WHM.Aero2.ActionName()),
                KeyValuePair.Create("Dia", WHM.Dia.ActionName()),

                // Buffs
                KeyValuePair.Create("Thin Air", WHM.ThinAir.ActionName()),
                KeyValuePair.Create("Presence of Mind", WHM.PresenceOfMind.ActionName()),
                KeyValuePair.Create("Plenary Indulgence", WHM.PlenaryIndulgence.ActionName()),
                KeyValuePair.Create("Sacred Sight", WHM.Buffs.SacredSight.StatusName()),
                #endregion

                #region WHMPvP
                KeyValuePair.Create("Miracle of Nature", WHMPvP.MiracleOfNature.ActionName()),
                KeyValuePair.Create("Seraph Strike", WHMPvP.SeraphStrike.ActionName()),
                KeyValuePair.Create("Afflatus Purgation", WHMPvP.AfflatusPurgation.ActionName()),
                #endregion

                // Name
                KeyValuePair.Create("Rapture into Misery", "狂喜苦難"),
                KeyValuePair.Create("Solace into Misery", "安慰苦難"),
                KeyValuePair.Create("Misery", WHM.AfflatusMisery.ActionName()),
                KeyValuePair.Create("Asylum", WHM.Asylum.ActionName()),
                KeyValuePair.Create("Liturgy of the Bell", WHM.LiturgyOfTheBell.ActionName()),
                KeyValuePair.Create("LiturgyOfTheBell", WHM.LiturgyOfTheBell.ActionName()),
            ];
        }
    }
}
