using System.Collections.Generic;
using WrathCombo.Combos.PvE;
using WrathCombo.Combos.PvP;
using WrathCombo.Extensions;

namespace WrathCombo.Resources.Dictionary.Chinese.Description
{
    public static class ASTDesc
    {
        public static IEnumerable<KeyValuePair<string, string>> GetDescriptions()
        {
            return
            [
                // Generated by the String Extraction and Translation Tool  
                // Model: DeepSeek v3  
                // Temperature: 0.1  
                // Generation Time: 2025-03-13 18:14:55  
                #region AST                
                KeyValuePair.Create("Replaces Malefic or Combust with options below", "用下方選項替換Malefic或Combust"),
                KeyValuePair.Create("Adds Combust to the DPS feature if it's not present on current target, or is about to expire.", "如果當前目標沒有Combust或即將失效，則將其新增到DPS功能中。"),
                KeyValuePair.Create("Adds Lightspeed when moving", "移動時新增Lightspeed"),
                KeyValuePair.Create("Adds Lucid Dreaming when MP drops below slider value", "當MP低於滑塊值時新增Lucid Dreaming"),
                KeyValuePair.Create("Adds Divination", "新增Divination"),
                KeyValuePair.Create("Draws your cards", "抽卡"),
                KeyValuePair.Create("Weaves your Balance or Spear card (best used with Quick Target Cards)", "插入你的太陽神之衡或放浪神之箭卡（最好與快速目標髮卡一起使用）"),
                KeyValuePair.Create("Adds Lord Of Crowns", "新增Lord of Crowns"),
                KeyValuePair.Create("Adds Oracle after Divination", "在Divination後新增Oracle"),
                KeyValuePair.Create("Replaces Gravity with options below", "用下方選項替換Gravity"),
                KeyValuePair.Create("Replaces Benefic II with a one button healing replacement.", "用一個按鈕的治療替換Benefic II。"),
                KeyValuePair.Create("Essential Dignity will be added when the target is at or below the value set", "當目標處於或低於設定值時新增Essential Dignity"),
                KeyValuePair.Create("Adds Celestial Intersection.", "新增Celestial Intersection。"),
                KeyValuePair.Create("Adds Aspected Benefic & refreshes it if needed.", "新增Aspected Benefic並在需要時重新整理它。"),
                KeyValuePair.Create("Adds Exaltation.", "新增Exaltation。"),
                KeyValuePair.Create("Adds The Spire (Shield) when the card has been drawn", "當抽到The Spire（護盾）時新增"),
                KeyValuePair.Create("Adds The Ewer (Heal over time) when the card has been drawn", "當抽到The Ewer（持續治療）時新增"),
                KeyValuePair.Create("Adds The Arrow (increased healing)  when the card has been drawn", "當抽到The Arrow（增加治療）時新增"),
                KeyValuePair.Create("Adds The Bole (Reduced Damage) when the card has been drawn", "當抽到The Bole（減少傷害）時新增"),
                KeyValuePair.Create("Replaces Aspected Helios/Helios Conjunction or Helios with a one button healing replacement.", "用一個按鈕的治療替換Aspected Helios/Helios Conjunction或Helios。"),
                KeyValuePair.Create("Adds Celestial Opposition", "新增Celestial Opposition"),
                KeyValuePair.Create("Adds Lady of Crowns, if the card is drawn", "如果抽到Lady of Crowns，則新增"),
                KeyValuePair.Create("Adds Horoscope.", "新增Horoscope。"),
                KeyValuePair.Create("Changes Benefic 2 to Benefic when Benefic 2 is not unlocked or available.", "當Benefic 2未解鎖或不可用時，將Benefic 2更改為Benefic。"),
                KeyValuePair.Create("Changes Swiftcast to Ascend", "將Swiftcast更改為Ascend"),
                KeyValuePair.Create("When you play the Balance or Spear, this will automatically apply the buff to a party member. It will look at DPS that suit the card first, if none found or they have buffs already, will look at the other DPS instead.", "當你使用太陽神之衡或放浪神之箭時，自動將卡發給一名隊員。它將首先考慮發給適合該卡的進攻職業，如果沒有找到或他們已經擁有進攻卡，則會發給其他進攻職業。"),
                KeyValuePair.Create("Targets a tank or healer if no DPS remain for quick target selection", "如果沒有剩餘的DPS用於快速目標選擇，則選擇坦克或治療者"),
                // This full-sentence match fires before ASTSkills.cs's bare "Malefic"
                // fragment (Skill layer, processed after all Description files), so it must
                // supply the resolved action name itself rather than leave "Fall Malefic" as
                // a literal for a later fragment to catch -- "Malefic" alone would otherwise
                // match first and strand the "Fall " prefix untranslated.
                KeyValuePair.Create("Turns Fall Malefic into an all-in-one damage button.", $"將{AST.FallMalefic.ActionName()}變成一個全能傷害按鈕。"),
                KeyValuePair.Create("Adds Drawing Cards to Burst Mode.", "將抽卡新增到爆發模式。"),
                KeyValuePair.Create("Adds Playing Cards to Burst Mode.", "將使用卡新增到爆發模式。"),
                KeyValuePair.Create("Adds Double Cast to Aspected Benefic.", "為Aspected Benefic新增雙重施法。"),
                KeyValuePair.Create("Adds Double Malefic Cast to Burst Mode.", "將雙重Malefic施法新增到爆發模式。"),
                KeyValuePair.Create("Adds Double Gravity Cast to Burst Mode.", "將雙重Gravity施法新增到爆發模式。"),
                KeyValuePair.Create("Adds Gravity Cast to Burst Mode.", "將Gravity施法新增到爆發模式。"),
                KeyValuePair.Create("Adds Macrocosmos to Burst Mode. ", "將Macrocosmos新增到爆發模式。"),
                KeyValuePair.Create(" If Double Gravity is enabled, it will hold Macrocosmos for the double gravity burst.", "如果啟用了雙重Gravity，它將保留Macrocosmos用於雙重Gravity爆發。"),
                KeyValuePair.Create("Turns Epicycle into burst combo.", "將Epicycle轉變為爆發連擊。"),
                KeyValuePair.Create("Card Draw", "抽卡"),
                KeyValuePair.Create("Card Play", "出卡"),
                KeyValuePair.Create("Quick Target Damage Cards", "傷害卡快速目標發放"),
                KeyValuePair.Create("Add Tanks/Healers to Auto-Target", "將防護職業和治療職業加入髮卡目標"),
                KeyValuePair.Create("No Override", "不覆蓋"),
                KeyValuePair.Create("Hard Target Override", "強制目標覆蓋"),
                KeyValuePair.Create("Overrides selection with hard target if you have one", "如果你選擇了可以髮卡的目標，則覆蓋髮卡"),
                KeyValuePair.Create("UI Mousover Override", "UI滑鼠懸停覆蓋"),
                KeyValuePair.Create("Overrides selection with UI mouseover target if you have one", "如果存在UI滑鼠懸停目標，為滑鼠懸停目標髮卡"),
                KeyValuePair.Create("Skip targets with a 傷害降低 debuff", "跳過有傷害降低debuff的目標"),
                KeyValuePair.Create("Skip targets with a 衰弱 or 瀕死 debuff", "跳過有衰弱或瀕死debuff的目標"),
                KeyValuePair.Create("Downgrade", "降級"),
                KeyValuePair.Create("In Helios mode: Will Cast Aspected Helios/Helios Conjunction when the HoT is missing on yourself.", "在Helios模式下：當你身上缺少HoT效果時，會根據情況自動施放Aspected Helios或Helios Conjunction。"),
                KeyValuePair.Create("In Aspected Helios mode: Is considered enabled regardless.", "在Aspected Helios下：無論條件如何，均視為啟用。"),
                KeyValuePair.Create("Alternative AOE Mode. Leaves Aspected Helios alone for manual HoTs", "替代AOE模式。保留Aspected Helios用於手動施放HoT效果"),
                KeyValuePair.Create("Alternative DPS Mode. Leaves 凶星 alone for pure DPS, becomes 凶星 when features are on cooldown", "替代DPS模式。保留凶星用於純DPS輸出，當技能處於冷卻時切換為凶星"),
                KeyValuePair.Create("Double Gravity Cast Option", "雙重重力"),
                KeyValuePair.Create("Overwrite Non-DPS Cards", "覆蓋非輸出卡牌"),
                KeyValuePair.Create("Will draw even if you have healing cards remaining.", "即使你仍有治療卡牌，也會抽取。"),
                KeyValuePair.Create("Set percentage value", "設定百分比值"),
                KeyValuePair.Create("Will only weave this action.", "僅會穿插此技能。"),
                #endregion

                #region ASTPvP
                KeyValuePair.Create("Lord and Lady card play", "領主和貴婦卡組合使用"),
                KeyValuePair.Create("Uses Lord and Lady of Crowns when available.", "當王冠之貴婦和王冠之領主可用時同時使用"),
                KeyValuePair.Create("Lord of Crowns card play", "僅使用王冠之領主卡"),
                KeyValuePair.Create("Only uses Lord of Crowns when available.", "僅當王冠之領主卡可用時使用"),
                KeyValuePair.Create("Lady of Crowns card play", "僅使用王冠之貴婦卡"),
                KeyValuePair.Create("Only uses Lady of Crowns when available.", "僅當王冠之貴婦卡可用時使用")
                #endregion
            ];
        }
    }
}
