using System;
using System.Collections.Generic;
using WrathCombo.Combos.PvE;
using WrathCombo.Combos.PvP;
using WrathCombo.Extensions;

namespace WrathCombo.Resources.Dictionary.Chinese.Description
{
    public static class BLMDesc
    {
        public static IEnumerable<KeyValuePair<string, string>> GetDescriptions()
        {
            return
            [
                // Generated by the String Extraction and Translation Tool  
                // Model: DeepSeek v3  
                // Temperature: 0.1  
                // Generation Time: 2025-03-13 18:14:55  
                #region BLMPvE
                KeyValuePair.Create("Replaces Fire with a full one-button single target rotation.", "用一鍵單體循環替換Fire。"),
                KeyValuePair.Create("Replaces Blizzard II with a full one-button AoE rotation.", "用一鍵AOE循環替換Blizzard II。"),
                KeyValuePair.Create("Need a GCD of 2.45 or lower to use.", "需要使用GCD為2.45或更低的技能。"),
                KeyValuePair.Create("Add Leylines to the rotation.", "將Leylines加入循環。"),
                KeyValuePair.Create("Add Amplifier to the rotation.", "將Amplifier加入循環。"),
                KeyValuePair.Create("Add Manafont to the rotation.", "將Manafont加入循環。"),
                KeyValuePair.Create("Add (High) Thunder to the rotation.", "將（高）雷電加入循環。"),
                KeyValuePair.Create("Add Despair to the rotation.", "將Despair加入循環。"),
                KeyValuePair.Create("Add Swiftcast to the rotation.", "將Swiftcast加入循環。"),
                KeyValuePair.Create("Add Triplecast to the rotation.", "將Triplecast加入循環。"),
                KeyValuePair.Create("Add Transpose to the rotation.", "將Transpose加入循環。"),
                KeyValuePair.Create("Add Foul/Xenoglossy to the rotation.", "將Foul/Xenoglossy加入循環。"),
                KeyValuePair.Create("Add Foul / Xenoglossy to the rotation as movement option.", "將Foul / Xenoglossy作為移動選項加入循環。"),
                KeyValuePair.Create("Add Flare to the rotation.", "將Flare加入循環。"),
                KeyValuePair.Create("Add Foul to the rotation.", "將Foul加入循環。"),
                KeyValuePair.Create("Add Foul to the rotation as movement option.", "將Foul作為移動選項加入循環。"),
                KeyValuePair.Create("Replaces Triplecast with Savage Blade when you already have triplecast active.", "當你已經啟用了Triplecast時，將Triplecast替換為Savage Blade。"),
                KeyValuePair.Create("Replaces Transpose with Umbral Soul when Umbral Soul is available.", "當Umbral Soul可用時，將Transpose替換為Umbral Soul。"),
                KeyValuePair.Create("Replaces Scathe with Xenoglossy when available.", "當Xenoglossy可用時，將Scathe替換為Xenoglossy。"),
                KeyValuePair.Create("Replaces Aetherial Manipulation with Between the Lines when you are out of active Ley Lines and standing still.", "當你不在啟用的黑魔紋範圍內且站立不動時，將乙太步替換為魔紋步。"),
                KeyValuePair.Create("(High) Thunder Option", "（高）雷電"),
                KeyValuePair.Create("Flare Star Option", "耀星"),
                KeyValuePair.Create("Add Flare Star to the rotation.", "將耀星新增到循環中。"),
                KeyValuePair.Create("Foul/Xenoglossy for Movement Option", "穢濁/異言移動選項"),
                KeyValuePair.Create("(High) Thunder II Option", "（高）中雷電"),
                KeyValuePair.Create("Add (High) Thunder II to the rotation.", "將（高）中雷電新增到循環中。"),
                KeyValuePair.Create("Fire I/III Feature", "火焰/大火焰"),
                KeyValuePair.Create("Replaces Fire I with Fire III outside of Astral Fire or when Firestarter is up.", "不在星極火狀態或觸發火苗時，將火焰替換為大火焰。"),
                KeyValuePair.Create("Blizzard I/III Feature", "暴雪/大暴雪"),
                KeyValuePair.Create("Replaces Blizzard I with Blizzard III when out of Umbral Ice.", "不在靈極冰狀態時，將暴雪替換為大暴雪。"),
                KeyValuePair.Create("Replaces Freeze with Blizzard II when synced below Lv.40.", "在同步等級低於 40 時，將中暴雪替換為冰寒。"),
                KeyValuePair.Create("Fire & Ice", "火與冰"),
                KeyValuePair.Create("Replaces Fire4 with Blizzard4 when in Umbral Ice.", "在靈極冰狀態下，將超火焰替換為超暴雪。"),
                KeyValuePair.Create("Between the Ley Lines Feature", "魔紋之間功能"),
                KeyValuePair.Create("Replaces Ley Lines with Between the Lines when Ley Lines is active.", "當黑魔紋啟用時，將黑魔紋替換為魔紋步。"),
                KeyValuePair.Create("Set the amount of time remaining on Triplecast charge before using.(Only when at threshold)", "設定在使用三重詠唱充能前的剩餘時間。（僅在達到閾值時）"),
                #endregion
                
                #region BLMPvP
                KeyValuePair.Create("Turns Fire into an all-in-one button.", "將Fire變為一個多功能按鈕。"),
                KeyValuePair.Create("- Uses Blizzard spells while moving (One Button Mode only).", "- 在移動時使用Blizzard法術（僅限一鍵模式）。"),
                KeyValuePair.Create("- Will use Paradox when appropriate.", "- 在適當時機使用Paradox。"),
                KeyValuePair.Create("Uses Burst when available.", "在可用時使用Burst。"),
                KeyValuePair.Create("- Requires target to be within range.", "- 需要目標在範圍內。"),
                KeyValuePair.Create("Uses Xenoglossy when available.", "在可用時使用Xenoglossy。"),
                KeyValuePair.Create("Uses Lethargy when available.", "在可用時使用Lethargy。"),
                KeyValuePair.Create("- Will not use against non-players.", "- 不會對非玩家使用。"),
                KeyValuePair.Create("Uses Wreath of Fire when available.", "在可用時使用Wreath of Fire。"),
                KeyValuePair.Create("- Requires player's HP to be at or above:", "- 需要玩家的生命值達到或高於："),
                KeyValuePair.Create("Elemental Weave Option", "元素天賦穿插"),
                KeyValuePair.Create("Uses Elemental Star when available.", "在可用時使用Elemental Star。"),
                KeyValuePair.Create("- Prioritizes Flare Star unless expiring.", "- 優先使用耀星，除非即將結束。"),
                KeyValuePair.Create("One Button Mode", "單按鈕模式"),
                KeyValuePair.Create("Combines Fire & Blizzard onto one button", "將火系與冰系技能合併到一個按鈕"),
                KeyValuePair.Create("Dual Button Mode", "雙按鈕模式"),
                KeyValuePair.Create("Puts the combo onto separate Fire & Blizzard buttons, which will only use that element.", "將連擊分配到獨立的火系和冰系按鈕，各按鈕僅使用對應元素技能"),
                KeyValuePair.Create("When under the effect of Astral Fire, must be moving this long before using Blizzard spells.", "處於星極火狀態時，必須移動指定時長才能使用冰系法術"),
                KeyValuePair.Create("Defensive Burst", "防禦性爆發"),
                KeyValuePair.Create("Also uses Burst when under 50% HP.", "50%血量以下時也會使用爆發"),
                // "%%" variants: same PvP sub-options, but this particular call site passes
                // the description through with an escaped "%%" (see SCHDescriptions.cs for
                // the same "%%" convention elsewhere in this dictionary).
                KeyValuePair.Create("Also uses Burst when under 50%% HP.", "50%%血量以下時也會使用爆發"),
                KeyValuePair.Create("Will not use outside combat.", "非戰鬥狀態下不使用"),
                KeyValuePair.Create("Defensive Xenoglossy", "防禦性異言"),
                KeyValuePair.Create("Also uses Xenoglossy when under 50% HP.", "50%血量以下時也會使用異言"),
                KeyValuePair.Create("Also uses Xenoglossy when under 50%% HP.", "50%%血量以下時也會使用異言"),
                KeyValuePair.Create("Defensive Lethargy", "防禦性昏沉"),
                KeyValuePair.Create("Also uses Lethargy when under 50% HP.", "50%血量以下時也會使用昏沉"),
                KeyValuePair.Create("Also uses Lethargy when under 50%% HP.", "50%%血量以下時也會使用昏沉"),
                KeyValuePair.Create("Uses only when targeted by enemy.", "僅在被敵人鎖定目標時使用"),
                KeyValuePair.Create("Defensive Elemental Weave", "防禦性元素天賦穿插"),
                KeyValuePair.Create("When under, uses Wreath of Ice instead.", "血量低下時改用寒冰環"),
                #endregion
            ];
        }
    }
}
