using System;
using System.Collections.Generic;
using WrathCombo.Combos.PvE;
using WrathCombo.Combos.PvP;
using WrathCombo.Extensions;

namespace WrathCombo.Resources.Dictionary.Chinese.Description
{
    public static class BLUDesc
    {
        public static IEnumerable<KeyValuePair<string, string>> GetDescriptions()
        {
            return
            [
                // Generated by the String Extraction and Translation Tool  
                // Model: DeepSeek v3  
                // Temperature: 0.1  
                // Generation Time: 2025-03-13 18:14:55  
                #region BLU
                KeyValuePair.Create("Turns Moon Flute into a full opener.", "將Moon Flute變為完整的起手技能。"),
                KeyValuePair.Create("Use the remaining 2 charges of Winged Reprobation before starting the opener again!", "在重新開始起手之前使用剩餘的2次Winged Reprobation！"),
                KeyValuePair.Create("Can be done with 2.50 spell speed", "可以在2.50詠唱速度下完成。"),
                KeyValuePair.Create("Changes the opener to apply either Mortal Flame or Breath of Magic instead of using Winged Reprobation.", "將起手技能改為施放Mortal Flame或Breath of Magic，而不是使用Winged Reprobation。"),
                KeyValuePair.Create("Requires 2.20 or faster spell speed", "需要2.20或更快的詠唱速度。"),
                KeyValuePair.Create("Here for historical value; level 80 opener is more potent.", "此功能為歷史遺留，80級的起手技能更為強力。"),
                KeyValuePair.Create("Turns Final Sting into the buff combo of: Moon Flute > Tingle > Whistle > Final Sting.", "將Final Sting變為以下增益組合：Moon Flute > Tingle > Whistle > Final Sting。"),
                KeyValuePair.Create("Adds Rose of Destruction, Feather Rain, Glass Dance, and J Kick to the combo.", "在組合中加入Rose of Destruction、Feather Rain、Glass Dance和J Kick。"),
                KeyValuePair.Create("Uses Basic Instinct if you're in an instance and on your own.", "如果你在副本中且獨自一人，則使用Basic Instinct。"),
                KeyValuePair.Create("Turns Ultravibration into Ram's Voice if Deep Freeze isn't on the target. Will swiftcast Ultravibration if available.", "如果目標沒有狀態凍結效果，則將Ultravibration變為Ram's Voice。如果有Swiftcast可用，則使用Swiftcast Ultravibration。"),
                KeyValuePair.Create("Uses Hydro Pull before using Ram's Voice.", "在使用Ram's Voice之前使用Hydro Pull。"),
                KeyValuePair.Create("Turns Feather Rain into Shock Strike, Rose of Destruction, and Glass Dance.", "將Feather Rain變為Shock Strike、Rose of Destruction和Glass Dance。"),
                KeyValuePair.Create("Will cause primals to desync from Moon Flute burst phases if used on cooldown.", "如果在冷卻時使用，會導致召喚獸與Moon Flute爆發階段不同步。"),
                KeyValuePair.Create("Holds spells if Moon Flute burst is about to occur and spells are off cooldown.", "如果Moon Flute爆發即將發生且技能不在冷卻中，則保留技能。"),
                KeyValuePair.Create("Adds J Kick to the combo.", "在組合中加入J Kick。"),
                KeyValuePair.Create("Adds Sea Shanty to the combo.", "在組合中加入Sea Shanty。"),
                KeyValuePair.Create("Adds Winged Reprobation to the combo.", "在組合中加入Winged Reprobation。"),
                KeyValuePair.Create("Adds Matra Magic to the combo.", "在組合中加入Matra Magic。"),
                KeyValuePair.Create("Adds Surpanakha to the combo.", "在組合中加入Surpanakha。"),
                KeyValuePair.Create("Adds Phantom Flurry to the combo.", "在組合中加入Phantom Flurry。"),
                KeyValuePair.Create("Adds Nightbloom to the combo.", "在組合中加入Nightbloom。"),
                KeyValuePair.Create("Turns Song of Torment into Bristle so Song of Torment is buffed.", "將Song of Torment變為Bristle，以便Song of Torment獲得增益。"),
                KeyValuePair.Create("Turns Peripheral Synthesis into Mustard Bomb when target is under the effect of Lightheaded.", "當目標處於Lightheaded效果下時，將Peripheral Synthesis變為Mustard Bomb。"),
                KeyValuePair.Create("Turns Sonic Boom into Sharpened Knife when in melee range.", "當在近戰範圍內時，將Sonic Boom變為Sharpened Knife。"),
                KeyValuePair.Create("Turns Black Knight's Tour or White Knight's Tour into its counterpart when the enemy is under the effect of the spell's debuff.", "當敵人處於技能減益效果下時，將Black Knight's Tour或White Knight's Tour變為其對應技能。"),
                KeyValuePair.Create("Puts Devour, Off-Guard, Lucid Dreaming, and Bad Breath into one button when under Tank Mimicry.", "在乙太複製：防護職業狀態下，將Devour、破防、Lucid Dreaming和Bad Breath合併為一個按鈕。"),
                KeyValuePair.Create("Changes Deep Clean to Peat Pelt if current target is not inflicted with Begrimed.", "如果當前目標沒有Begrimed效果，則將Deep Clean變為Peat Pelt。"),
                KeyValuePair.Create("Turns Perpetual Ray into Sharpened Knife when target is stunned and in melee range.", "當目標處於眩暈狀態且在近戰範圍內時，將PerpetualRay替換為SharpenedKnife"),
                KeyValuePair.Create("Perpetual Ray into Sharpened Knife", "Perpetual Ray轉為Sharpened Knife"),
                KeyValuePair.Create("Peripheral Synthesis into Mustard Bomb", "Peripheral Synthesis轉為Mustard Bomb"),
                KeyValuePair.Create("Buffed Song of Torment", "強化Song of Torment"),
                KeyValuePair.Create("Primal Feature", "蠻神特性"),
                KeyValuePair.Create("Hydro Pull Setup", "水力吸引"),
                KeyValuePair.Create("Vibe Combo", "振動連擊"),
                KeyValuePair.Create("Solo Mode", "單人模式"),
                KeyValuePair.Create("Off-cooldown Primal Additions", "補充已冷卻的蠻神技能"),
                KeyValuePair.Create("Peat Clean", "泥球掃除"),
                #endregion
            ];
        }
    }
}
