using System;
using System.Collections.Generic;
using WrathCombo.Combos.PvE;
using WrathCombo.Combos.PvP;
using WrathCombo.Extensions;

namespace WrathCombo.Resources.Dictionary.Chinese.Description
{
    public static class BRDDesc
    {
        public static IEnumerable<KeyValuePair<string, string>> GetDescriptions()
        {
            return
            [
                // Generated by the String Extraction and Translation Tool  
                // Model: DeepSeek v3  
                // Temperature: 0.1  
                // Generation Time: 2025-03-13 18:14:55  
                #region BRDPvE
                KeyValuePair.Create("Replaces Heavy Shot with a full one-button single target rotation.", "用一鍵單目標循環替換Heavy Shot。"),
                KeyValuePair.Create("Replaces Quick Nock with a full one-button AoE rotation.", "用一鍵AoE循環替換Quick Nock。"),
                KeyValuePair.Create("This option will make Bard apply DoTs if none are present on the target.", "此選項將使吟遊詩人在目標沒有DoT時施加DoT。"),
                KeyValuePair.Create("Enable the snapshotting of DoTs, within the remaining time of Raging Strikes below:", "在Raging Strikes剩餘時間內啟用DoT快照："),
                KeyValuePair.Create("This option adds the Bard's Songs to the Advanced Bard Feature.", "此選項將吟遊詩人的歌曲新增到高階吟遊詩人功能中。"),
                KeyValuePair.Create("Adds buffs onto the Advanced Bard feature.", "將增益效果新增到高階吟遊詩人功能中。"),
                KeyValuePair.Create("Adds Resonant Arrow to the Rotation after Barrage.", "在Barrage後新增Resonant Arrow到循環中。"),
                KeyValuePair.Create("Adds Radiant Encore to the Rotation after Finale.", "在光明神的最終樂章後新增Radiant Encore到循環中。"),
                KeyValuePair.Create("Adds Apex Arrow and Blast shot", "新增Apex Arrow。"),
                KeyValuePair.Create("Weave Sidewinder, Empyreal arrow, Rain of death, and Pitch perfect when available.", "在可用時插入Sidewinder、Empyreal Arrow、Rain of Death和Pitch Perfect。"),
                KeyValuePair.Create("84+ Pools Bloodletter charges to allow for optimum burst phases.", "84+時儲存Bloodletter充能以最佳化爆發階段。"),
                KeyValuePair.Create("Uses interrupt during the rotation if applicable.", "在循環中使用打斷技能（如果適用）。"),
                KeyValuePair.Create("Adds enemy health checking on mobs for buffs, DoTs and Songs.", "新增對怪物生命值的檢查以應用增益、DoT和歌曲。"),
                KeyValuePair.Create("They will not be reapplied if less than specified.", "如果低於指定值，則不會重新應用。"),
                KeyValuePair.Create("Uses Wardens Paeon when you have a cleansable debuff.", "當你有可清除的減益時使用Wardens Paeon。"),
                KeyValuePair.Create("Weave Songs on the Advanced AoE.", "在高階AoE中插入歌曲。"),
                KeyValuePair.Create("Adds buffs onto the Advance AoE Bard feature.", "將增益效果新增到高階AoE吟遊詩人功能中。"),
                KeyValuePair.Create("84+ Pools Rain of death charges to allow for optimum burst phases.", "84+時儲存Rain of Death充能以最佳化爆發階段。"),
                KeyValuePair.Create("Adds enemy health checking on targetted mob for songs.", "新增對目標怪物生命值的檢查以應用歌曲。"),
                KeyValuePair.Create("Replaces Heavy Shot/Burst Shot with Straight Shot/Refulgent Arrow when procced.", "在觸發時用Straight Shot/Refulgent Arrow替換Heavy Shot/Burst Shot。"),
                KeyValuePair.Create("Enabling this option will make Heavy Shot into Straight Shot refresh your DoTs on your current.", "啟用此選項將使Heavy Shot變為Straight Shot時重新整理當前目標的DoT。"),
                KeyValuePair.Create("Replaces Burst Shot with Apex Arrow when gauge is full and Blast Arrow when you are Blast Arrow ready.", "當量譜滿時用Apex Arrow替換Burst Shot，當Blast Arrow準備就緒時用Blast Arrow替換。"),
                KeyValuePair.Create("Iron Jaws is replaced with Caustic Bite/Stormbite if one or both are not up.", "如果Caustic Bite/Stormbite未生效，則用它們替換Iron Jaws。"),
                KeyValuePair.Create("Alternates between the two if Iron Jaws isn't available.", "如果Iron Jaws不可用，則在兩者之間交替使用。"),
                KeyValuePair.Create("Adds Apex and Blast Arrow to Iron Jaws when available.", "在可用時將Apex和Blast Arrow新增到Iron Jaws中。"),
                KeyValuePair.Create("Iron Jaws will only show up when debuffs are about to expire.", "Iron Jaws只會在減益即將結束時顯示。"),
                KeyValuePair.Create("Replaces Quick Nock/Ladonsbite with Shadowbite when ready.", "在準備就緒時用Shadowbite替換Quick Nock/Ladonsbite。"),
                KeyValuePair.Create("Replaces Ladonsbite and Quick Nock with Apex Arrow when gauge is full and Blast Arrow when you are Blast Arrow ready.", "當量譜滿時用Apex Arrow替換Ladonsbite和Quick Nock，當Blast Arrow準備就緒時用Blast Arrow替換。"),
                KeyValuePair.Create("All oGCD's on Bloodletter/Heartbreakshot", "所有能力技新增在Bloodletter/Heartbreakshot上。"),
                KeyValuePair.Create("Adds the songs to the oGCD feature. Wanderers > Mages > Armys", "將歌曲新增到能力技功能中。放浪神 > 賢者 > 軍神。"),
                KeyValuePair.Create("All AoE oGCD's on Rain of Death depending on their CD.", "所有AoE能力技根據冷卻時間新增在Rain of Death上。"),
                KeyValuePair.Create("Adds the songs to the AoE oGCD feature. Wanderers > Mages > Armys", "將歌曲新增到AoE能力技功能中。放浪神 > 賢者 > 軍神。"),
                KeyValuePair.Create("Adds Raging Strikes and Battle Voice onto Barrage.", "將Raging Strikes和Battle Voice新增到Barrage上。"),
                KeyValuePair.Create("Add Mage's Ballad and Army's Paeon to Wanderer's Minuet depending on cooldowns.", "根據冷卻時間將Mage's Ballad和Army's Paeon新增到Wanderer's Minuet中。"),
                KeyValuePair.Create("Adds Silent Nocturne to Burst Mode.", "將Silent Nocturne新增到爆發模式中。"),
                KeyValuePair.Create("Adds Apex Arrow to Burst Mode.", "將Apex Arrow新增到爆發模式中。"),
                KeyValuePair.Create("Adds Blast Arrow to Burst Mode.", "將Blast Arrow新增到爆發模式中。"),
                KeyValuePair.Create("Adds Harmonic Arrow to Burst Mode. Will use it at set number of charges AND when target is below the health threshold per charge for execute. ", "將Harmonic Arrow新增到爆發模式中。將在設定充能數時使用，並且當目標生命值低於每充能的執行閾值時使用。"),
                KeyValuePair.Create("Adds Encore of Light to Burst Mode.", "將Encore of Light新增到爆發模式中。"),
                KeyValuePair.Create("Auto Self cleanse of soft cc. ", "自動清除軟控制效果。"),
                KeyValuePair.Create(" Half Asleep, Heavy, and Bind", "催眠、加重和束縛。"),
                KeyValuePair.Create("Bard DoTs Option", "詩人DoT選項"),
                KeyValuePair.Create("Raging Jaws Option", "伶牙俐齒選項"),
                KeyValuePair.Create("Bard Songs Option", "詩人歌曲選項"),
                KeyValuePair.Create("Bard Song Option", "詩人歌曲選項"),
                KeyValuePair.Create("Resonant Option", "共鳴箭"),
                KeyValuePair.Create("Encore Option", "光明神的返場餘音"),
                KeyValuePair.Create("oGcd Option", "能力技選項"),
                KeyValuePair.Create("No Waste Option", "防止浪費選項"),
                KeyValuePair.Create("Self Cleanse Option", "自我淨化"),
                KeyValuePair.Create("AoE No Waste Option", "AoE防止浪費選項"),
                KeyValuePair.Create("Heavy Shot into Straight Shot Feature", "強力射擊 -> 直線射擊"),
                KeyValuePair.Create("Iron Jaws Alternate Feature", "伶牙俐齒替代"),
                KeyValuePair.Create("Quick song option", "快速唱歌"),
                KeyValuePair.Create("Bard Buffs Feature", "詩人Buff"),
                KeyValuePair.Create("One Button Songs Feature", "一鍵唱歌"),
                KeyValuePair.Create("2.48 Adjusted Standard Opener", "2.48調整標準起手"),
                KeyValuePair.Create("Standard Opener", "標準起手"),
                KeyValuePair.Create("2.49 Standard Comfy", "2.49標準舒適起手"),
                KeyValuePair.Create("Remaining time (In seconds). Recommended 5, increase little by little if refresh is outside of radiant window", "剩餘時間（秒）。推薦5，如果重新整理在光明神視窗期外，請逐步增加數值。"),
                KeyValuePair.Create("Remaining target HP percentage", "目標剩餘生命值百分比"),
                #endregion

                #region BRDPvP
                KeyValuePair.Create("Turns Powerful Shot into an all-in-one damage button.", "將強勁射擊變為一個全能傷害技能按鈕。"),
                KeyValuePair.Create("How many Charges to use it at", "使用多少充能次數"),
                KeyValuePair.Create("1 charge 8000 damage", "1次充能: 8000傷害"),
                KeyValuePair.Create("2 charge 12000 damage", "2次充能: 12000傷害"),
                KeyValuePair.Create("3 charge 15000 damage", "3次充能: 15000傷害"),
                KeyValuePair.Create("4 charge 17000 damage", "4次充能: 17000傷害")
                #endregion
            ];
        }
    }
}
