using System;
using System.Collections.Generic;
using WrathCombo.Combos.PvE;
using WrathCombo.Combos.PvP;
using WrathCombo.Extensions;

namespace WrathCombo.Resources.Dictionary.Chinese.Description
{
    public static class DOLDesc
    {
        public static IEnumerable<KeyValuePair<string, string>> GetDescriptions()
        {
            return
            [
                // Generated by the String Extraction and Translation Tool  
                // Model: DeepSeek v3  
                // Temperature: 0.1  
                // Generation Time: 2025-03-13 18:14:55  
                #region DOL
                KeyValuePair.Create("Replaces Ageless Words and Solid Reason with Wise to the World when available", "當可用時，用Wise to the World替換Ageless Words和Solid Reason。"),
                KeyValuePair.Create("Replaces Lay of the Lands or Arbor Calls with Prospect/Triangulate and Truth of Mountains/Forests if not active.", "如果未啟用，用Prospect/Triangulate和Truth of Mountains/Truth of Forests替換Lay of the Land或Arbor Call。"),
                KeyValuePair.Create("Replaces Cast with Hook when fishing", "釣魚時，用Hook替換Cast。"),
                KeyValuePair.Create("Replace fishing abilities with diving abilities when underwater", "水下時，用潛水技能替換釣魚技能。"),
                KeyValuePair.Create("Replaces Cast with Gig when diving.", "潛水時，用Gig替換Cast。"),
                KeyValuePair.Create("Replaces Surface Slap with Veteran Trade when diving.", "潛水時，用Veteran Trade替換Surface Slap。"),
                KeyValuePair.Create("Replaces Prize Catch with Nature's Bounty when diving.", "潛水時，用Nature's Bounty替換Prize Catch。"),
                KeyValuePair.Create("Replaces Snagging with Salvage when diving.", "潛水時，用Salvage替換Snagging。"),
                KeyValuePair.Create("Replaces Cast Light with Electric Current when diving.", "潛水時，用Electric Current替換Cast Light。"),
                KeyValuePair.Create("Replaces Mooch with Shark Eye when diving.", "潛水時，用Shark Eye替換Mooch。"),
                KeyValuePair.Create("Replaces Fish Eyes with Vital Sight when diving.", "潛水時，用Vital Sight替換Fish Eyes。"),
                KeyValuePair.Create("Replaces Chum with Baited Breath when diving.", "潛水時，用Baited Breath替換Chum。"),
                #endregion

                // Manually added
                KeyValuePair.Create("Locate & Truth Feature", "探查特性"),
            ];
        }
    }
}
