using System;
using System.Collections.Generic;
using WrathCombo.Combos.PvE;
using WrathCombo.Combos.PvP;
using WrathCombo.Extensions;

namespace WrathCombo.Resources.Dictionary.Chinese.Description
{
    public static class DRGDesc
    {
        public static IEnumerable<KeyValuePair<string, string>> GetDescriptions()
        {
            return
            [
                // Generated by the String Extraction and Translation Tool  
                // Model: DeepSeek v3  
                // Temperature: 0.1  
                // Generation Time: 2025-03-13 18:14:55  
                #region DRG
                KeyValuePair.Create("Replaces True Thrust with a full one-button single target rotation.", "用一鍵單體循環替換True Thrust。"),
                KeyValuePair.Create("Replaces Doom Spike with a full one-button AoE rotation.", "用一鍵AOE循環替換Doom Spike。"),
                KeyValuePair.Create("Adds various buffs to the rotation.", "在循環中新增各種增益效果。"),
                KeyValuePair.Create("Adds Battle Litany to the rotation.", "在循環中新增Battle Litany。"),
                KeyValuePair.Create("Adds Lance Charge to the rotation.", "在循環中新增Lance Charge。"),
                KeyValuePair.Create("Adds various cooldowns to the rotation.", "在循環中新增各種冷卻技能。"),
                KeyValuePair.Create("Adds Life Surge, on the proper GCD, to the rotation.", "在正確的GCD上新增Life Surge到循環中。"),
                KeyValuePair.Create("Adds Mirage Dive to the rotation.", "在循環中新增Mirage Dive。"),
                KeyValuePair.Create("Adds Dragonfire Dive to the rotation.", "在循環中新增Dragonfire Dive。"),
                KeyValuePair.Create("Adds Dragonfire Dive to the rotation when in the target ring (1 yalm) & when not moving.", "當在目標圈內（1米）且不移動時，在循環中新增Dragonfire Dive。"),
                KeyValuePair.Create("Adds Geirskogul to the rotation.", "在循環中新增Geirskogul。"),
                KeyValuePair.Create("Adds Nastrond to the rotation.", "在循環中新增Nastrond。"),
                KeyValuePair.Create("Adds Stardiver to the rotation.", "在循環中新增Stardiver。"),
                KeyValuePair.Create("Adds Stardiver to the rotation when in the target ring (1 yalm) & when not moving.", "當在目標圈內（1米）且不移動時，在循環中新增Stardiver。"),
                KeyValuePair.Create("Adds Wyrmwind Thrust to the rotation.", "在循環中新增Wyrmwind Thrust。"),
                KeyValuePair.Create("Adds Rise of the Dragon to the rotation.", "在循環中新增Rise of the Dragon。"),
                KeyValuePair.Create("Adds Starcross to the rotation.", "在循環中新增Starcross。"),
                KeyValuePair.Create("Adds True North before Chaos Thrust/Chaotic Spring, Fang And Claw and Wheeling Thrust when you are not in the correct position for the enhanced potency bonus.", "當你不處於正確位置以獲得增強威力加成時，在Chaos Thrust/Chaotic Spring、Fang And Claw和Wheeling Thrust之前新增True North。"),
                KeyValuePair.Create("Adds Piercing Talon to the rotation when you are out of melee range.", "當你超出近戰範圍時，在循環中新增Piercing Talon。"),
                KeyValuePair.Create("Replaces Doomspike with a full one-button AoE rotation.", "用一鍵AOE循環替換Doomspike。"),
                KeyValuePair.Create("Adds Lance Charge and Battle Litany to the rotation.", "在循環中新增Lance Charge和Battle Litany。"),
                KeyValuePair.Create("Adds Life Surge, onto proper GCDs, to the rotation.", "在正確的GCD上新增Life Surge到循環中。"),
                KeyValuePair.Create("Adds Disembowel combo to the rotation when you are or synced below level 62.", "當你在62級以下或同步到62級以下時，在循環中新增Disembowel連擊。"),
                KeyValuePair.Create("Standard opener", "標準起手"),
                KeyValuePair.Create("Uses Standard opener", "使用標準起手"),
                KeyValuePair.Create("Piercing Talon opener", "貫穿尖起手"),
                KeyValuePair.Create("Uses Piercing Talon opener", "使用貫穿尖起手"),
                KeyValuePair.Create("High Jump Option", "高跳選項"),
                KeyValuePair.Create("Adds (High) Jump to the rotation.", "將高跳新增到循環中。"),
                KeyValuePair.Create("(High) Jump Melee option", "高跳近戰選項"),
                KeyValuePair.Create("Adds (High) Jump to the rotation when in the target ring (1 yalm) & when not moving.", "當在目標圈內（1 米）且不移動時，將高跳新增到循環中。"),
                KeyValuePair.Create("Second Wind HP percentage threshold (0 = Disabled)", "內丹生命百分比閾值（0 = 禁用）"),
                KeyValuePair.Create("Bloodbath HP percentage threshold (0 = Disabled)", "浴血生命百分比閾值（0 = 禁用）"),
                KeyValuePair.Create("HP% to be at or under", "生命值百分比達到或低於"),
                KeyValuePair.Create("Wyrmwind Option", "天龍點睛"),
                KeyValuePair.Create("Replace Full Thrust/Heavens' Thrust with its combo chain.", "用其連擊鏈替換Full Thrust/Heavens' Thrust。"),
                KeyValuePair.Create("Replace Chaos Thrust /Chaotic Spring with its combo chain.", "用其連擊鏈替換Chaos Thrust /Chaotic Spring。"),
                KeyValuePair.Create("Turns Lance Charge into Battle Litany when the former is on cooldown.", "當Lance Charge冷卻時，將其轉換為Battle Litany。"),
                KeyValuePair.Create("Turns Drakesbane Combo into an all-in-one damage button.", "將Drakesbane連擊轉換為一個全能傷害按鈕。"),
                KeyValuePair.Create("Adds Geirskogul to Burst Mode.", "在Burst Mode中新增Geirskogul。"),
                KeyValuePair.Create("Adds Nastrond to Burst Mode.", "在Burst Mode中新增Nastrond。"),
                KeyValuePair.Create("Adds Horrid Roar to Burst Mode.", "在Burst Mode中新增Horrid Roar。"),
                KeyValuePair.Create("Sustain Chaos Spring Option", "櫻花繚亂維持"),
                KeyValuePair.Create("Execute Chaos Spring Option", "櫻花繚亂處決"),
                KeyValuePair.Create("Adds Chaos Spring to Burst Mode when below the set HP percentage.", "當HP低於設定百分比時，在Burst Mode中新增櫻花繚亂。"),
                KeyValuePair.Create("Adds Chaos Spring to Burst Mode when target is below 8k health because it goes through guard.", "當目標血量低於8000時，在Burst Mode中新增櫻花繚亂，因為它可以穿透防禦。"),
                KeyValuePair.Create("Adds Wyrmwind Thrust to Burst Mode.", "在Burst Mode中新增Wyrmwind Thrust。"),
                KeyValuePair.Create("High Jump Weave Option", "高跳穿插"),
                KeyValuePair.Create("Adds High Jump to Burst Mode.", "在Burst Mode中新增高跳。"),
                KeyValuePair.Create("Using Elusive Jump turns Drakesbane Combo into all-in-one burst damage button once all cooldowns are ready. ", "當所有冷卻技能準備就緒時，使用Elusive Jump將Drakesbane連擊轉換為全能爆發傷害按鈕。"),
                KeyValuePair.Create(" Disables Elusive Jump if Burst is not ready.", "如果Burst未準備就緒，則禁用Elusive Jump。"),
                KeyValuePair.Create("Stop Using When Target HP% is at or Below (Set to 0 to Disable This Check)", "當目標生命值百分比達到或低於此值時停止使用（設定為0以禁用此檢查）"),
                #endregion

                #region DRGPvP
                KeyValuePair.Create("Ends Life of the Dragon if HP falls below the set percentage", "當你的血量低於設定百分比時結束紅蓮龍血狀態"),
                KeyValuePair.Create("Seconds remaining of Life of the Dragon buff before using Nastrond if you are still above the set HP percentage.", "當血量高於設定百分比時，在紅蓮龍血狀態剩餘指定秒數時使用死者之岸"),
                KeyValuePair.Create("Chaotic Spring HP percentage threshold. Set to 100 to use on cd", "櫻花繚亂血量百分比閾值。設為100則冷卻完畢就使用"),
                KeyValuePair.Create("Minimum Distance to use Wyrmwind Thrust. Maximum damage at 15 or more", "使用天龍點睛的最小距離。15米及以上時傷害最大化")
                #endregion
            ];
        }
    }
}
