using System;
using System.Collections.Generic;
using WrathCombo.Combos.PvE;
using WrathCombo.Combos.PvP;
using WrathCombo.Extensions;

namespace WrathCombo.Resources.Dictionary.Chinese.Description
{
    public static class DRKDesc
    {
        public static IEnumerable<KeyValuePair<string, string>> GetDescriptions()
        {
            return
            [
                // Generated by the String Extraction and Translation Tool  
                // Model: DeepSeek v3  
                // Temperature: 0.1  
                // Generation Time: 2025-03-13 18:14:55  
                #region DRK
                KeyValuePair.Create("Replaces Hard Slash with a full one-button single target rotation.", "用一鍵完整單體循環替換Hard Slash。"),
                KeyValuePair.Create("Replaces Unleash with a full one-button AoE rotation.", "用一鍵完整AOE循環替換Unleash。"),
                KeyValuePair.Create("Tries to prevent any triple-weaving (even when it may not clip).", "儘量避免三插（即使可能不會卡GCD）。"),
                KeyValuePair.Create("Adds Unmend to the rotation when you are out of range.", "當你超出近戰範圍時，將Unmend加入循環。"),
                KeyValuePair.Create("Collection of cooldowns to add to the rotation.", "將冷卻技能集合加入循環。"),
                KeyValuePair.Create("Adds Delirium (or Blood Weapon at lower levels) to the rotation on cooldown and when Darkside is up.", "當Darkside啟用且冷卻完畢時，將Delirium（或低等級時的Blood Weapon）加入循環。"),
                KeyValuePair.Create(" Will also spend 50 blood gauge if Delirium is nearly ready to protect from overcap.", "如果Delirium即將準備就緒，還會消耗50點血槽以防止溢位。"),
                KeyValuePair.Create("Adds Living Shadow to the rotation when Darkside is up.", "當Darkside啟用時，將Living Shadow加入循環。"),
                KeyValuePair.Create("Adds Disesteem to the rotation when available.", "當可用時，將Disesteem加入循環。"),
                KeyValuePair.Create("Adds Shadowbringer to the rotation while Darkside is up. Will use all stacks on cooldown.", "當Darkside啟用時，將Shadowbringer加入循環。冷卻完畢時將使用所有層數。"),
                KeyValuePair.Create("Pools Shadowbringer to use during even minute window bursts (after Disesteem).", "在偶數分鐘的爆發視窗（Disesteem之後）集中使用Shadowbringer。"),
                KeyValuePair.Create("Adds Salted Earth to the rotation while Darkside is up, will use Salt and Darkness if unlocked.", "當Darkside啟用時，將Salted Earth加入循環，如果解鎖了Salt and Darkness也會使用。"),
                KeyValuePair.Create("Adds Salt and Darkness to the rotation in the latter half of its duration.", "在Salted Earth持續時間後半段將Salt and Darkness加入循環。"),
                KeyValuePair.Create("Adds Carve and Spit to the rotation while Darkside is up.", "當Darkside啟用時，將Carve and Spit加入循環。"),
                KeyValuePair.Create("Collection of spenders (mana and blood) to add to the rotation.", "將消耗資源（魔力和血槽）的技能集合加入循環。"),
                KeyValuePair.Create("Adds the Scarlet Delirium combo chain to the rotation when Delirium is activated.", "當Delirium啟用時，將Scarlet Delirium連擊鏈加入循環。"),
                KeyValuePair.Create("Adds Bloodspiller to the rotation when Delirium is active or well outside of burst.", "當Delirium啟用或遠離爆發期時，將Bloodspiller加入循環。"),
                KeyValuePair.Create("Adds Bloodspiller to the rotation after Syphon Strike when the blood gauge is above the chosen threshold.", "當血槽超過設定閾值時，在Syphon Strike後將Bloodspiller加入循環。"),
                KeyValuePair.Create("Uses Edge of Darkness in burst windows, and outside of that will spend to chosen MP limit.", "在爆發視窗使用Edge of Darkness，其他時候會消耗到設定的MP上限。"),
                KeyValuePair.Create("Will spend Dark Arts if your own The Blackest Night shield is active on you.", "如果你自身的The Blackest Night護盾啟用，會消耗Dark Arts。"),
                KeyValuePair.Create("Uses Edge of Darkness if Darkside is about to expire (<10s).", "如果Darkside即將結束（<10秒），使用Edge of Darkness。"),
                KeyValuePair.Create("Uses Edge of Darkness if you are above 8,500 mana.", "如果你的魔力超過8,500，使用Edge of Darkness。"),
                KeyValuePair.Create("Collection of Mitigations to add to the rotation.", "將減傷技能集合加入循環。"),
                KeyValuePair.Create("Uses Oblation based on Health Remaining.", "根據剩餘生命值使用Oblation。"),
                KeyValuePair.Create("Uses Reprisal when a raidwide is in the process of casting.", "當團隊範圍技能正在施放時，使用Reprisal。"),
                KeyValuePair.Create("Uses Dark Missionary when a raidwide is in the process of casting.", "當團隊範圍技能正在施放時，使用Dark Missionary。"),
                KeyValuePair.Create("Won't use Dark Missionary if your own Reprisal is on the target.", "如果你自身的Reprisal已在目標上，不會使用Dark Missionary。"),
                KeyValuePair.Create("Uses Shadowed Vigil based on Health Remaining.", "根據剩餘生命值使用Shadowed Vigil。"),
                KeyValuePair.Create("Uses Living Dead based on Health Remaining.", "根據剩餘生命值使用Living Dead。"),
                KeyValuePair.Create("Uses The Blackest Night based on Health Remaining.", "根據剩餘生命值使用Blackest Night。"),
                KeyValuePair.Create("(Note: makes no attempt to ensure shield will break)", "（注意：不保證護盾會被打破）"),
                KeyValuePair.Create("Adds Low Blow to the rotation when your target's cast is interruptible.", "當目標施法可打斷時，將Low Blow加入循環。"),
                KeyValuePair.Create("Adds Living Shadow to the rotation on cooldown and when Darkside is up.", "當Darkside啟用且冷卻完畢時，將Living Shadow加入循環。"),
                KeyValuePair.Create("Adds Shadowbringer to the rotation.", "將Shadowbringer加入循環。"),
                KeyValuePair.Create("Adds Salted Earth and Salt and Darkness to the rotation on cooldown and when Darkside is up.", "當Darkside啟用且冷卻完畢時，將Salted Earth和Salt and Darkness加入循環。"),
                KeyValuePair.Create("Requires to be at a stand-still and for combat to have been going on for >7 seconds to use Salted Earth, to try to make it be placed after you finish your pull.", "需要站立不動且戰鬥持續超過7秒才能使用Salted Earth，以確保在拉怪結束後放置。"),
                KeyValuePair.Create("Adds Abyssal Drain to the rotation when you fall below the chosen HP.", "當生命值低於設定閾值時，將Abyssal Drain加入循環。"),
                KeyValuePair.Create("Adds Impalement to the rotation when Delirium is active.", "當Delirium啟用時，將Impalement加入循環。"),
                KeyValuePair.Create("Adds Quietus to the rotation when Delirium is active or well outside of burst.", "當Delirium啟用或遠離爆發期時，將Quietus加入循環。"),
                KeyValuePair.Create("Adds Quietus to the rotation when the blood gauge is above the chosen threshold.", "當血槽超過設定閾值時，將Quietus加入循環。"),
                KeyValuePair.Create("Uses Flood of Shadow in burst, if Darkside is about to expire (<10s), if you have Dark Arts and use The Blackest Night, and outside of burst will spend to chosen MP limit.", "在爆發期使用Flood of Shadow，如果Darkside即將結束（<10秒），如果你有Dark Arts並使用The Blackest Night，以及在爆發期外會消耗到設定的MP上限。"),
                KeyValuePair.Create("Uses Flood of Shadow if you are above 8,500 mana.", "如果你的魔力超過8,500，使用Flood of Shadow。"),
                KeyValuePair.Create("Adds The Blackest Night to the rotation.", "將The Blackest Night加入循環。"),
                KeyValuePair.Create("Adds Reprisal to the rotation.", "將Reprisal加入循環。"),
                KeyValuePair.Create("Adds Rampart to the rotation.", "將Rampart加入循環。"),
                KeyValuePair.Create("Adds Arm's Length to the rotation.", "將Arm's Length加入循環。"),
                KeyValuePair.Create("Uses Living Dead based on your and your enemy's Remaining Health.", "根據你和敵人的剩餘生命值使用Living Dead。"),
                KeyValuePair.Create("Replaces Dark Mind with an all-in-one mitigation button.", "用一鍵減傷按鈕替換Dark Mind。"),
                KeyValuePair.Create("Gives max priority to Living Dead when the Health percentage threshold is met.", "當生命值百分比達到閾值時，優先使用Living Dead。"),
                KeyValuePair.Create("Adds The Blackest Night to the one-button mitigation.", "將The Blackest Night加入一鍵減傷。"),
                KeyValuePair.Create("Adds Oblation to the one-button mitigation.", "將Oblation加入一鍵減傷。"),
                KeyValuePair.Create("Adds Dark Missionary to the one-button mitigation.", "將Dark Missionary加入一鍵減傷。"),
                KeyValuePair.Create("Adds Shadow Wall / Vigil to the one-button mitigation.", "將Shadow Wall / Vigil加入一鍵減傷。"),
                KeyValuePair.Create("Adds selected oGCD abilities to Carve And Spit and Abyssal Drain.", "將選中的oGCD技能加入Carve and Spit和Abyssal Drain。"),
                KeyValuePair.Create("Adds Interject to the feature when your target's cast is interruptible.", "當目標施法可打斷時，將Interject加入功能。"),
                KeyValuePair.Create("Adds Delirium (or Blood Weapon) to the Feature.", "將Delirium（或Blood Weapon）加入功能。"),
                KeyValuePair.Create("Adds Living Shadow to the Feature.", "將Living Shadow加入功能。"),
                KeyValuePair.Create("Adds Disesteem to the Feature.", "將Disesteem加入功能。"),
                KeyValuePair.Create("Adds Salted Earth to the Feature.", "將Salted Earth加入功能。"),
                KeyValuePair.Create("Adds Saltand Darkness to the Feature when under the effect of Salted Earth.", "當處於Salted Earth效果下時，將Salt and Darkness加入功能。"),
                KeyValuePair.Create("Adds Shadowbringer to the Feature.", "將Shadowbringer加入功能。"),
                KeyValuePair.Create("Use Variant Spirit Dart whenever the debuff is not present or less than 3s.", "當debuff不存在或少於3秒時，使用Variant Spirit Dart。"),
                KeyValuePair.Create("Use Variant Cure when HP is below set threshold.", "當生命值低於設定閾值時，使用Variant Cure。"),
                KeyValuePair.Create("Use Variant Ultimatum on cooldown.", "冷卻完畢時使用Variant Ultimatum。"),
                KeyValuePair.Create("Turns Souleater Combo into an all-in-one damage button.", "將Souleater連擊變為一鍵傷害按鈕。"),
                KeyValuePair.Create("Adds Plunge to Burst Mode.", "將Plunge加入爆發模式。"),
                KeyValuePair.Create("Uses Plunge whilst in melee range, and not just as a gap-closer.", "在近戰範圍內使用Plunge，而不僅僅是作為接近技能。"),
                KeyValuePair.Create("Adds Salted Earth to Burst mode.", "將Salted Earth加入爆發模式。"),
                KeyValuePair.Create("Adds Salt and Darkness to Burst mode.", "將Salt and Darkness加入爆發模式。"),
                KeyValuePair.Create("Adds Impalement to Burst mode.", "將Impalement加入爆發模式。"),
                KeyValuePair.Create("Adds Shadowbringer to Burst mode.", "將Shadowbringer加入爆發模式。"),
                KeyValuePair.Create("Adds Blackest Night to Burst mode.", "將The Blackest Night加入爆發模式。"),
                KeyValuePair.Create("Adds Scorn to Burst mode.", "將Scorn加入爆發模式。"),
                KeyValuePair.Create("Over 7,000 mana", "超過7000魔力值"),
                KeyValuePair.Create("# to use at or above", "達到或高於這個值時使用"),
                KeyValuePair.Create("Mana to save for TBN", "為暗黑佈道保留的魔力值"),
                KeyValuePair.Create("Avoid Doubling up on Group Mit", "避免重複使用團隊減傷技能"),
                KeyValuePair.Create("Salt After Pull Option", "拉怪後使用Salted Earth"),
                KeyValuePair.Create("HP% to be at or Above to use ", "生命值達到或超過這個百分比時使用"),
                #endregion
            ];
        }
    }
}
