using System;
using System.Collections.Generic;
using WrathCombo.Combos.PvE;
using WrathCombo.Combos.PvP;
using WrathCombo.Data;
using WrathCombo.Extensions;

namespace WrathCombo.Resources.Dictionary.Chinese.Description
{
    public static class MCHDesc
    {
        public static IEnumerable<KeyValuePair<string, string>> GetDescriptions()
        {
            return
            [
                // Generated by the String Extraction and Translation Tool  
                // Model: DeepSeek v3  
                // Temperature: 0.1  
                // Generation Time: 2025-03-13 18:14:55  
                #region MCHPvE
                KeyValuePair.Create("Replaces Split Shot with a full one-button single target rotation.", "用完整的一鍵單目標循環替換Split Shot。"),
                KeyValuePair.Create("Replaces Spreadshot with a full one-button AoE rotation.", "用完整的一鍵AoE循環替換Spreadshot。"),
                KeyValuePair.Create("Will lock out input to keep Flamethrower going by replacing Spreadshot with Savage Blade.", "透過用Savage Blade替換Spreadshot來鎖定輸入以保持Flamethrower的持續。"),
                KeyValuePair.Create("Adds the Balance opener at lvl 90+.", "在90級以上時使用由The Balance社群推薦的起手循環。"),
                KeyValuePair.Create("Adds Barrel Stabilizer to the rotation.", "將Barrel Stabilizer新增到循環中。"),
                KeyValuePair.Create("Adds Full Metal Field to the rotation.", "將Full Metal Field新增到循環中。"),
                KeyValuePair.Create("Adds Gauss Round and Ricochet or Double Check and Checkmate to the rotation. Will prevent overcapping.", "將Gauss Round和Ricochet或Double Check和Checkmate新增到循環中。防止資源溢位。"),
                KeyValuePair.Create("Adds Wildfire to the rotation.", "將Wildfire新增到循環中。"),
                KeyValuePair.Create("Adds Hypercharge to the rotation.", "將Hypercharge新增到循環中。"),
                KeyValuePair.Create("Adds Heat Blast or Blazing Shot to the rotation", "將Heat Blast或Blazing Shot新增到循環中。"),
                KeyValuePair.Create("Adds Rook Autoturret or Automaton Queen to the rotation.", "將Rook Autoturret或Automaton Queen新增到循環中。"),
                KeyValuePair.Create("Rook / Queen Overdrive Option", "Rook Overdrive / Queen Overdrive Option"),
                KeyValuePair.Create("Adds Rook or Queen Overdrive to the rotation.", "將Rook Overdrive或Queen Overdrive新增到循環中。"),
                KeyValuePair.Create("Adds Reassemble to the rotation.", "將Reassemble新增到循環中。"),
                KeyValuePair.Create("Will be used priority based.", "將根據優先順序使用。"),
                KeyValuePair.Create("Order from highest to lowest priority :", "優先順序從高到低排序："),
                KeyValuePair.Create("Excavator - Chainsaw - Air Anchor - Drill - Clean Shot", "Excavator - Chainsaw - Air Anchor - Drill - Clean Shot"),
                KeyValuePair.Create("Adds Drill to the rotation.", "將Drill新增到循環中。"),
                KeyValuePair.Create("Adds Hot Shot/Air Anchor to the rotation.", "將Hot Shot/Air Anchor新增到循環中。"),
                KeyValuePair.Create("Adds Chain Saw to the rotation.", "將Chain Saw新增到循環中。"),
                KeyValuePair.Create("Adds Excavator to the rotation.", "將Excavator新增到循環中。"),
                KeyValuePair.Create("Uses Head Graze to interrupt during the rotation, where applicable.", "在適用的情況下，使用Head Graze在循環中打斷。"),
                KeyValuePair.Create("Use Second Wind when below the set HP percentage.", "當HP低於設定百分比時使用Second Wind。"),
                KeyValuePair.Create("Adds Flamethrower to the rotation.", "將Flamethrower新增到循環中。"),
                KeyValuePair.Create(" Changes to Savage blade when in use to prevent cancelling.", "在使用時更改為Savage Blade以防止取消。"),
                KeyValuePair.Create("Adds Gauss Round and Ricochet or Double Check and Checkmate to the rotation.", "將Gauss Round和Ricochet或Double Check和Checkmate新增到循環中。（至少選擇一個）"),
                KeyValuePair.Create("Use Blazing shot instead of Crossbow at lvl 92+", "在92級以上時使用Blazing Shot代替Crossbow。"),
                KeyValuePair.Create("Adds Bioblaster to the rotation.", "將Bioblaster新增到循環中。"),
                KeyValuePair.Create("Adds Air Anchor to the the rotation.", "將Air Anchor新增到循環中。"),
                KeyValuePair.Create("Adds Chain Saw to the the rotation.", "將Chain Saw新增到循環中。"),
                KeyValuePair.Create("Prevents the use of Dismantle when target already has the effect by replacing it with Savage Blade.", "當目標已有Dismantle效果時，透過用Savage Blade替換來防止使用Dismantle。"),
                KeyValuePair.Create("Swap dismantle with tactician when dismantle is on cooldown.", "當Dismantle冷卻時，用Tactician替換Dismantle。"),
                KeyValuePair.Create("Turns Heat Blast or Blazing Shot into Hypercharge ", "當你有50或更多熱量或獲得Hypercharge增益時，將Heat Blast或Blazing Shot轉換為Hypercharge。"),
                KeyValuePair.Create("when u have 50 or more heat or when u got Hypercharged buff.", "當你有50或更多熱量或獲得Hypercharge增益時。"),
                KeyValuePair.Create("Adds Barrel Stabilizer to the feature when off cooldown.", "冷卻結束時將Barrel Stabilizer新增到功能中。"),
                KeyValuePair.Create("Adds Wildfire to the feature when off cooldown and overheated.", "冷卻結束且過熱時將Wildfire新增到功能中。"),
                KeyValuePair.Create("Switches between Heat Blast and either Gauss Round and Ricochet or Double Check and Checkmate, depending on cooldown timers.", "根據冷卻時間在Heat Blast和Gauss Round與Ricochet或Double Check與Checkmate之間切換。"),
                KeyValuePair.Create("Turns Auto Crossbow into Hypercharge when at or above 50 heat.", "當熱量達到或超過50時，將Auto Crossbow轉換為Hypercharge。"),
                KeyValuePair.Create("Adds Barrel Stabilizer to the feature when below 50 Heat Gauge.", "當熱量低於50時，將Barrel Stabilizer新增到功能中。"),
                KeyValuePair.Create("Switches between Auto Crossbow and either Gauss Round and Ricochet or Double Check and Checkmate, depending on cooldown timers.", "根據冷卻時間在Auto Crossbow和Gauss Round與Ricochet或Double Check與Checkmate之間切換。"),
                KeyValuePair.Create("Replace Rook Autoturret and Automaton Queen with Overdrive while active.", "在啟用時用Overdrive替換Rook Autoturret和Automaton Queen。"),
                KeyValuePair.Create("Replace Hot Shot, Drill, Air Anchor, Chainsaw and Excavator depending on which is on cooldown.", "根據冷卻時間替換Hot Shot、Drill、Air Anchor、Chainsaw和Excavator。"),
                KeyValuePair.Create("Replace Gauss Round and Ricochet or Double Check and Checkmate with one or the other depending on which has more charges.", "根據剩餘次數替換Gauss Round和Ricochet或Double Check和Checkmate。"),
                KeyValuePair.Create("Number of Charges to Save for Manual Use", "保留用於手動使用的充能次數"),
                KeyValuePair.Create($"Uses {ActionWatching.GetActionName(MCH.AutomatonQueen)} at this battery threshold outside of Boss encounter.", $"在非Boss戰中，當電量達到此閾值時使用{ActionWatching.GetActionName(MCH.AutomatonQueen)}。"),
                KeyValuePair.Create("Only counts for 'Boss encounters Only setting'.", "僅適用於“僅限Boss戰”設定。"),
                KeyValuePair.Create("HP% for the target to be at or under", "目標生命百分比達到或低於此值"),
                KeyValuePair.Create($"Uses {ActionWatching.GetActionName(MCH.AutomatonQueen)} logic regardless of content.", $"無論內容如何，使用{ActionWatching.GetActionName(MCH.AutomatonQueen)}的邏輯。"),
                KeyValuePair.Create($"Uses {ActionWatching.GetActionName(MCH.Excavator)} logic regardless of content.", $"無論內容如何，使用{ActionWatching.GetActionName(MCH.Excavator)}的邏輯。"),
                KeyValuePair.Create($"Only uses {ActionWatching.GetActionName(MCH.Excavator)} logic when in Boss encounters.", $"僅在Boss戰中使用{ActionWatching.GetActionName(MCH.Excavator)}的邏輯。"),
                KeyValuePair.Create($"Only uses {ActionWatching.GetActionName(MCH.AutomatonQueen)} logic when in Boss encounters.", $"僅在Boss戰中使用{ActionWatching.GetActionName(MCH.AutomatonQueen)}的邏輯。"),
                KeyValuePair.Create("Battery threshold", "電量閾值"),
                KeyValuePair.Create("Barrel Option", "槍管加熱"),
                #endregion
                
                #region MCHPvP
                KeyValuePair.Create("Turns Blast Charge into an all-in-one damage button.", "將蓄力衝擊變為一個全能傷害按鈕。"),
                KeyValuePair.Create("Adds Air Anchor to Burst Mode.", "將Air Anchor加入Burst Mode。"),
                KeyValuePair.Create("Adds Analysis to Burst Mode.", "將Analysis加入Burst Mode。"),
                KeyValuePair.Create("Alternate Analysis Option", "保留分析"),
                KeyValuePair.Create("Uses Analysis with Air Anchor instead of Chain Saw.", "在Burst Mode中使用Analysis與Air Anchor，而非Chain Saw。"),
                KeyValuePair.Create("Adds Drill to Burst Mode.", "將Drill加入Burst Mode。"),
                KeyValuePair.Create("Saves Drill for use after Wildfire.", "保留Drill在Wildfire之後使用。"),
                KeyValuePair.Create("Bio Blaster Option", "毒化衝擊"),
                KeyValuePair.Create("Adds Bio Blaster to Burst Mode.", "將毒化衝擊加入Burst Mode。"),
                KeyValuePair.Create("Adds Chain Saw to Burst Mode.", "將Chain Saw加入Burst Mode。"),
                KeyValuePair.Create("Adds Full Metal Field to Burst Mode.", "將Full Metal Field加入Burst Mode。"),
                KeyValuePair.Create("Adds Wildfire to Burst Mode.", "將Wildfire加入Burst Mode。"),
                KeyValuePair.Create("Adds Marksmans Spite to Burst Mode when the target is below specified HP.", "當目標生命值低於指定值時，將Marksmans Spite加入Burst Mode。"),
                KeyValuePair.Create("Adds Barrel Stabilizer to Burst Mode.", "將Barrel Stabilizer加入Burst Mode。"),
                KeyValuePair.Create("Alternate Drill Option", "保留鑽頭"),
                KeyValuePair.Create("Full Metal Field Wildfire combo", "全金屬爆發野火連擊"),
                KeyValuePair.Create("Uses Full Metal Field when Wildfire is ready.", "當野火準備就緒時使用全金屬爆發"),
                KeyValuePair.Create("Full Metal Field only when Overheated", "僅在過熱時使用全金屬爆發"),
                KeyValuePair.Create("Only uses Full Metal Field while Overheated.", "只在過熱狀態下使用全金屬爆發"),
                KeyValuePair.Create("Use Marksman's Spite when the target is below set HP", "當目標血量低於設定值時使用魔彈射手"),
                #endregion
            ];
        }
    }
}
