using System;
using System.Collections.Generic;
using WrathCombo.Combos.PvE;
using WrathCombo.Combos.PvP;
using WrathCombo.Extensions;

namespace WrathCombo.Resources.Dictionary.Chinese.Description
{
    public static class MNKDesc
    {
        public static IEnumerable<KeyValuePair<string, string>> GetDescriptions()
        {
            return
            [
                // Generated by the String Extraction and Translation Tool  
                // Model: DeepSeek v3  
                // Temperature: 0.1  
                // Generation Time: 2025-03-13 18:14:55  
                #region MNK
                KeyValuePair.Create("Replaces Bootshine with a full one-button single target rotation.", "用一鍵連擊替換Bootshine，用於單體目標循環。"),
                KeyValuePair.Create("Replaces Arms of the Destroyer with a full one-button AoE rotation.", "用一鍵連擊替換Arms of the Destroyer，用於群體目標循環。"),
                KeyValuePair.Create("Adds The Forbidden Chakra to the rotation", "將The Forbidden Chakra加入循環。"),
                KeyValuePair.Create("Adds Form Shift to the rotation", "將Form Shift加入循環。"),
                KeyValuePair.Create("Uses selected opener", "使用選定的起手式。"),
                KeyValuePair.Create("Adds selected buffs to the rotation", "將選定的增益技能加入循環。"),
                KeyValuePair.Create("Adds Brotherhood to the rotation", "將Brotherhood加入循環。"),
                KeyValuePair.Create("Riddle of Fire Option", "紅蓮極意"),
                KeyValuePair.Create("Adds Riddle of Fire to the rotation", "將紅蓮極意加入循環。"),
                KeyValuePair.Create("Fire's Reply Option", "乾坤鬥氣彈"),
                KeyValuePair.Create("Adds Fire's Reply to the rotation", "將乾坤鬥氣彈加入循環。"),
                KeyValuePair.Create("Adds Riddle of Wind to the rotation", "將Riddle of Wind加入循環。"),
                KeyValuePair.Create("Adds Wind's Reply to the rotation", "將Wind's Reply加入循環。"),
                KeyValuePair.Create("Adds Perfect Balance to the rotation", "將Perfect Balance加入循環。"),
                KeyValuePair.Create("Adds Masterful Blitz to the rotation", "將Masterful Blitz加入循環。"),
                KeyValuePair.Create("Adds True North dynamically, when not in positional, to the rotation", "當不在位置要求時，動態將True North加入循環。"),
                KeyValuePair.Create("Adds Howling Fist to the rotation", "將Howling Fist加入循環。"),
                KeyValuePair.Create("Merge single target GCDs which share the same beast chakra", "合併共享相同獸脈的單體GCD技能。"),
                KeyValuePair.Create("Perfect Balance becomes Masterful Blitz while you have 3 Beast Chakra.", "當擁有3個獸脈時，Perfect Balance變為Masterful Blitz。"),
                KeyValuePair.Create("Turns Phantom Rush Combo into an all-in-one damage button.", "將Phantom Rush連擊變為一個全能的傷害按鈕。"),
                KeyValuePair.Create("Adds Meteodrive Limit break to Burst Mode when target is below 20k and guarded", "當目標血量低於20k且處於防禦狀態時，將Meteodrive極限爆發加入爆發模式。"),
                KeyValuePair.Create("Adds Thunderclap to Burst Mode when not buffed with Wind Resonance.", "當未獲得疾風神髓增益時，將輕身步法加入爆發模式。"),
                KeyValuePair.Create("Adds Riddle of Earth and Earth's Reply to Burst Mode when in combat.", "在戰鬥中，將Riddle of Earth和Earth's Reply加入爆發模式。"),
                KeyValuePair.Create("Adds Flints Reply to Burst Mode.", "將Flint's Reply加入爆發模式。"),
                KeyValuePair.Create("Adds Rising Phoenix to Burst Mode.", "將Rising Phoenix加入爆發模式。"),
                KeyValuePair.Create("Adds Wind's Reply to Burst Mode.", "將Wind's Reply加入爆發模式。"),
                KeyValuePair.Create("Beast Chakra Handlers", "象形拳處理"),
                KeyValuePair.Create("Meditation Option", "鬥氣"),
                KeyValuePair.Create("Adds Meditation to the rotation", "將鬥氣新增到循環中"),
                KeyValuePair.Create("Double Lunar", "雙陰"),
                KeyValuePair.Create("Uses Lunar/Lunar opener", "使用雙陰鬥氣起手"),
                KeyValuePair.Create("Solar Lunar", "陽陰"),
                KeyValuePair.Create("Uses Solar/Lunar opener", "使用陽陰鬥氣起手"),
                KeyValuePair.Create($"Stop Using {MNK.Brotherhood.ActionName()} When Target HP% is at or Below (Set to 0 to Disable This Check)", $"當目標生命百分比達到或低於此值時停止使用 {MNK.Brotherhood.ActionName()}（設定為0以禁用此檢查）"),
                KeyValuePair.Create("Riddle of Fire/Brotherhood Feature", "紅蓮極意/義結金蘭"),
                KeyValuePair.Create("Replaces Riddle of Fire with Brotherhood when Riddle of Fire is on cooldown.", "如果紅蓮極意進入冷卻時，用義結金蘭代替。"),
                KeyValuePair.Create("Replaces Brotherhood with Riddle of Fire when Brotherhood is on cooldown.", "如果義結金蘭進入冷卻時，用紅蓮極意代替。"),
                KeyValuePair.Create($"Stop Using {MNK.RiddleOfFire.ActionName()} When Target HP% is at or Below (Set to 0 to Disable This Check)", $"當目標生命百分比達到或低於此值時停止使用{MNK.RiddleOfFire.ActionName()}（設定為0以禁用此檢查）"),
                KeyValuePair.Create($"Stop Using {MNK.RiddleOfWind.ActionName()} When Target HP% is at or Below (Set to 0 to Disable This Check)", $"當目標生命百分比達到此值時停止使用{MNK.RiddleOfWind.ActionName()}（設定為0以禁用此檢查）"),
                KeyValuePair.Create("Opo-opo Option", "魔猿"),
                KeyValuePair.Create("Replace Bootshine/Leaping Opo with Dragon Kick.", "將連擊/猿舞連擊新增到雙龍腳。"),
                KeyValuePair.Create("Raptor Option", "猛禽選項"),
                KeyValuePair.Create("Replace True Strike/Rising Raptor with Twin Snakes.", "將正拳/龍顎正拳新增到雙掌打。"),
                KeyValuePair.Create("Coeurl Option", "豹選項"),
                KeyValuePair.Create("Replace Snap Punch/Pouncing Coeurl with Demolish.", "將崩拳/虎襲崩拳新增到破碎拳。"),
                KeyValuePair.Create("Replaces Perfect Balance with Savage Blade when you already have Perfect Balance active.", "當震腳啟用時，將震腳替換為狂怒劍"),
                                #endregion
            ];
        }
    }
}
