using System;
using System.Collections.Generic;
using WrathCombo.Combos.PvE;
using WrathCombo.Combos.PvP;
using WrathCombo.Extensions;

namespace WrathCombo.Resources.Dictionary.Chinese.Description
{
    public static class PCTDesc
    {
        public static IEnumerable<KeyValuePair<string, string>> GetDescriptions()
        {
            return
            [
                // Generated by the String Extraction and Translation Tool  
                // Model: DeepSeek v3  
                // Temperature: 0.1  
                // Generation Time: 2025-03-13 18:14:55  
                #region PCTPvE
                KeyValuePair.Create("Replaces Fire in Red with a full one-button single target rotation.", "將火焰之紅替換為完整的一鍵單體循環。"),
                KeyValuePair.Create("Replaces Fire in Red II with a full one-button AoE rotation.", "將中火焰之紅替換為完整的一鍵群體循環。"),
                KeyValuePair.Create("Adds missing Motifs to the combo while out of combat.", "在戰鬥外時向連擊新增缺失的彩繪。"),
                KeyValuePair.Create("Adds missing Motifs to the combo while no target is present in combat.", "在戰鬥中無目標時向連擊新增缺失的彩繪。"),
                KeyValuePair.Create("Adds selected spells below to the burst phase.", "向爆發階段新增下方選定的法術。"),
                KeyValuePair.Create("Adds Comet in Black to the burst phase.", "向爆發階段新增Comet in Black。"),
                KeyValuePair.Create("Adds Star Prism to the burst phase.", "向爆發階段新增Star Prism。"),
                KeyValuePair.Create("Adds Rainbow Drip to the burst phase.", "向爆發階段新增Rainbow Drip。"),
                KeyValuePair.Create("Adds Hammer Stamp Combo to the burst phase.", "向爆發階段新增Hammer Stamp Combo。"),
                KeyValuePair.Create("Adds Blizzard in Cyan to the burst phase.", "向爆發階段新增暴雪之藍青。"),
                KeyValuePair.Create("Add Selected Motifs to the combo.", "向連擊新增選定的彩繪。"),
                KeyValuePair.Create("Adds Landscape Motif.", "新增Landscape Motif。"),
                KeyValuePair.Create("Adds Weapon Motif.", "新增Weapon Motif。"),
                KeyValuePair.Create("Adds Selected Muses to the combo.", "向連擊新增選定的構想。"),
                KeyValuePair.Create("Adds Scenic Muse.", "新增Scenic Muse。"),
                KeyValuePair.Create("Adds Living Muse.", "新增Living Muse。"),
                KeyValuePair.Create("Adds Steel Muse.", "新增Steel Muse。"),
                KeyValuePair.Create("Adds Mog/Madeen to the combo.", "向連擊新增莫古利激流/馬蒂恩懲罰。"),
                KeyValuePair.Create("Adds Subtractive Palette to the combo.", "向連擊新增Subtractive Palette。"),
                KeyValuePair.Create("Adds Comet in Black to the combo.", "向連擊新增Comet in Black。"),
                KeyValuePair.Create("Adds Hammer Stamp combo.", "新增Hammer Stamp連擊。"),
                KeyValuePair.Create("Adds selected features to the combo while moving.", "在移動時向連擊新增選定的功能。"),
                KeyValuePair.Create("Adds Hammer Stamp Combo to the combo while moving.", "在移動時向連擊新增Hammer Stamp Combo。"),
                KeyValuePair.Create("Adds Holy in White to the combo while moving.", "在移動時向連擊新增神聖之白。"),
                KeyValuePair.Create("Adds Comet in Black to the combo while moving.", "在移動時向連擊新增Comet in Black。"),
                KeyValuePair.Create("Adds Swiftcast to the combo while moving.", "在移動時向連擊新增Swiftcast。"),
                KeyValuePair.Create("Use swiftcast for motifs.", "使用Swiftcast來施放彩繪。"),
                KeyValuePair.Create("Adds Blizzard in Cyan to the combo.", "向連擊新增暴雪之藍青。"),
                KeyValuePair.Create("Adds Lucid Dreaming to the combo.", "向連擊新增Lucid Dreaming。"),
                KeyValuePair.Create("Adds Holy in White to the combo.", "向連擊新增Holy in White。"),
                KeyValuePair.Create("Merges aetherhue actions for specific target types into a single button.", "將特定目標型別的乙太色調技能合併為一個按鈕。"),
                KeyValuePair.Create("Merges Motifs and Muses into a single button.", "將彩繪和構想合併為一個按鈕。"),
                KeyValuePair.Create("Consolidates paint-consuming actions into one button.", "將消耗顏料的技能整合為一個按鈕。"),
                KeyValuePair.Create("Health % to stop Drawing Motif", "目標生命值百分比達到此值時停止彩繪"),
                KeyValuePair.Create("Prepull Motifs Feature", "戰鬥外彩繪"),
                KeyValuePair.Create("Downtime Motifs Option", "戰鬥中沒有目標時補充彩繪"),
                KeyValuePair.Create("Blizzard in Cyan Option", "暴雪之藍青"),
                KeyValuePair.Create("Motif Selection Feature", "彩繪選擇"),
                KeyValuePair.Create("Muse Selection Feature", "構想選擇"),
                KeyValuePair.Create("Mog/Madeen Feature", "莫古利激流/馬蒂恩懲罰"),
                KeyValuePair.Create("Holy in White Option", "神聖之白"),
                KeyValuePair.Create("Swiftcast Motifs Option", "即刻彩繪"),
                KeyValuePair.Create("Combined Aetherhues Feature", "整合乙太色調"),
                KeyValuePair.Create("One Button Motifs", "一鍵構想"),
                KeyValuePair.Create("One Button Paint", "合併消耗顏料的技能為一個按鈕"),
                #endregion
                
                #region PCTPvP
                KeyValuePair.Create("Turns Fire in Red into an all-in-one damage button.", "將紅色狀態下的Fire轉化為一個全能傷害按鈕。"),
                KeyValuePair.Create("Saves high-damaging actions until the target's HP falls below the threshold.", "在目標HP低於閾值前保留高傷害技能。"),
                KeyValuePair.Create("Uses Tempera Coat when HP falls below the threshold during combat.", "在戰鬥中HP低於閾值時使用Tempera Coat。"),
                KeyValuePair.Create("Uses Subtractive Palette when standing still and releases it when moving.", "站立不動時使用Subtractive Palette，移動時釋放。"),
                KeyValuePair.Create("Adds Creature Motif to Burst Mode.", "在Burst Mode中新增Creature Motif。"),
                KeyValuePair.Create("Adds Living Muse to Burst Mode.", "在Burst Mode中新增Living Muse。"),
                KeyValuePair.Create("Adds Mog Of The Ages to Burst Mode.", "在Burst Mode中新增Mog Of The Ages。"),
                KeyValuePair.Create("Adds Holy In White to Burst Mode.", "將神聖之白加入爆發模式"),
                KeyValuePair.Create("Adds Star Prism to Burst Mode.", "在Burst Mode中新增Star Prism。"),
                KeyValuePair.Create("Burst Control Option", "爆發控制選項"),
                KeyValuePair.Create("Smart Palette Option", "智慧調色選項"),
                KeyValuePair.Create("Holy In White Option", "神聖之白選項"),
                #endregion

                // Maunally added
                KeyValuePair.Create($"Add {PCT.MogoftheAges.ActionName()} when fully drawn and off cooldown.", $"當 {PCT.MogoftheAges.ActionName()} 完全繪製且冷卻完成時新增。"),
                KeyValuePair.Create($"Add {PCT.RetributionoftheMadeen.ActionName()} when fully drawn and off cooldown.", $"當 {PCT.RetributionoftheMadeen.ActionName()} 完全繪製且冷卻完成時新增。"),
                KeyValuePair.Create($"Add {PCT.HammerStamp.ActionName()} when under the effect of {PCT.Buffs.HammerTime.StatusName()}.", $"當受到{PCT.Buffs.HammerTime.StatusName()}效果時新增{PCT.HammerStamp.ActionName()}。"),
                KeyValuePair.Create($"Add {PCT.StarPrism.ActionName()} when under the effect of {PCT.Buffs.Starstruck.StatusName()}.", $"當受到{PCT.Buffs.Starstruck.StatusName()}效果時新增{PCT.StarPrism.ActionName()}。"),
                KeyValuePair.Create("Add Lucid Dreaming when below this MP", "當MP低於此值時新增醒夢"),
                KeyValuePair.Create("Both Single Target & AoE", "同時替換單體與群體技能"),
                KeyValuePair.Create($"Replaces both {PCT.FireInRed.ActionName()} & {PCT.FireIIinRed.ActionName()}", $"同時替換{PCT.FireInRed.ActionName()}和{PCT.FireIIinRed.ActionName()}"),
                KeyValuePair.Create("Single Target Only", "僅替換單體技能"),
                KeyValuePair.Create($"Replace only {PCT.FireInRed.ActionName()}", $"僅替換{PCT.FireInRed.ActionName()}"),
                KeyValuePair.Create("AoE Only", "僅替換群體技能"),
                KeyValuePair.Create($"Replace only {PCT.FireIIinRed.ActionName()}", $"僅替換{PCT.FireIIinRed.ActionName()}"),
                KeyValuePair.Create($"2nd GCD {PCT.StarryMuse.ActionName()}", $"第二個GCD使用{PCT.StarryMuse.ActionName()}"),
                KeyValuePair.Create($"3rd GCD {PCT.StarryMuse.ActionName()}", $"第三個GCD使用{PCT.StarryMuse.ActionName()}"),
            ];
        }
    }
}
