using System;
using System.Collections.Generic;
using WrathCombo.Combos.PvE;
using WrathCombo.Combos.PvP;
using WrathCombo.Extensions;

namespace WrathCombo.Resources.Dictionary.Chinese.Description
{
    public static class PLDDesc
    {
        public static IEnumerable<KeyValuePair<string, string>> GetDescriptions()
        {
            return
            [
                // Generated by the String Extraction and Translation Tool  
                // Model: DeepSeek v3  
                // Temperature: 0.1  
                // Generation Time: 2025-03-13 18:14:55  
                #region PLD
                KeyValuePair.Create("- Requires Requiescat to be ready.", "- 需要安魂祈禱準備就緒。"),
                KeyValuePair.Create("Replaces Fast Blade with a full one-button single target rotation.", "用一鍵式單體循環替換Fast Blade。"),
                KeyValuePair.Create("Replaces Total Eclipse with a full one-button AoE rotation.", "用一鍵式AOE循環替換Total Eclipse。"),
                KeyValuePair.Create("Adds Fight or Flight to Advanced Mode.", "將Fight or Flight新增到高階模式。"),
                KeyValuePair.Create("- Uses after Royal Authority during opener.", "- 在起手式中，在Royal Authority之後使用。"),
                KeyValuePair.Create("- Afterward, on cooldown alongside Requiescat.", "- 之後，與Requiescat一起在冷卻時使用。"),
                KeyValuePair.Create("- Target HP must be at or above:", "- 目標HP必須達到或超過："),
                KeyValuePair.Create("Adds Shield Lob to Advanced Mode.", "將Shield Lob新增到高階模式。"),
                KeyValuePair.Create("- Uses only while out of melee range.", "- 僅在近戰範圍外使用。"),
                KeyValuePair.Create("- Will not override better actions.", "- 不會覆蓋更好的技能。"),
                KeyValuePair.Create("Adds Circle of Scorn to Advanced Mode.", "將厄運流轉新增到高階模式。"),
                KeyValuePair.Create("- Uses only when in range of the target.", "- 僅在目標範圍內使用。"),
                KeyValuePair.Create("- Prefers to use during Fight or Flight.", "- 優先在Fight or Flight期間使用。"),
                KeyValuePair.Create("Adds Spirits Within to Advanced Mode.", "將Spirits Within新增到高階模式。"),
                KeyValuePair.Create("Adds Goring Blade to Advanced Mode.", "將Goring Blade新增到高階模式。"),
                KeyValuePair.Create("- Prefers to use after Requiescat.", "- 優先在Requiescat之後使用。"),
                KeyValuePair.Create("Adds Holy Spirit to Advanced Mode.", "將Holy Spirit新增到高階模式。"),
                KeyValuePair.Create("- Uses only when under Divine Might.", "- 僅在Divine Might效果下使用。"),
                KeyValuePair.Create("- Will be prioritized if buff is expiring.", "- 如果增益即將結束，將優先使用。"),
                KeyValuePair.Create("Adds Requiescat to Advanced Mode.", "將Requiescat新增到高階模式。"),
                KeyValuePair.Create("- Uses after Fight or Flight.", "- 在Fight or Flight之後使用。"),
                KeyValuePair.Create("Adds Intervene to Advanced Mode.", "將Intervene新增到高階模式。"),
                KeyValuePair.Create("- Will not use during movement.", "- 不會在移動時使用。"),
                KeyValuePair.Create("- Amount of charges to keep:", "- 保留的充能次數："),
                KeyValuePair.Create("Adds the Atonement chain to Advanced Mode.", "將Atonement連擊新增到高階模式。"),
                KeyValuePair.Create("Adds Confiteor to Advanced Mode.", "將Confiteor新增到高階模式。"),
                KeyValuePair.Create("- At lower levels, uses Holy Spirit instead.", "- 在較低等級時，使用Holy Spirit代替。"),
                KeyValuePair.Create("Adds Blade of Faith/Truth/Valor to Advanced Mode.", "將Blade of Faith/Blade of Truth/Blade of Valor新增到高階模式。"),
                KeyValuePair.Create("Adds Blade of Honor to Advanced Mode.", "將Blade of Honor新增到高階模式。"),
                KeyValuePair.Create("- Uses after Blade of Valor.", "- 在Blade of Valor之後使用。"),
                KeyValuePair.Create("Adds a minimum MP limit to Advanced Mode.", "為高階模式新增最低MP限制。"),
                KeyValuePair.Create("MP Reservation Option", "魔力保留選項"),
                KeyValuePair.Create("- This is not recommended in most cases.", "- 在大多數情況下不推薦使用。"),
                KeyValuePair.Create("- Player MP must remain at or above:", "- 玩家MP必須保持在或高於："),
                KeyValuePair.Create("Adds defensive actions to Advanced Mode.", "將防禦技能新增到高階模式。"),
                KeyValuePair.Create("- Will not override offensive actions.", "- 不會覆蓋進攻技能。"),
                KeyValuePair.Create("- Uses only when being targeted.", "- 僅在成為目標時使用。"),
                KeyValuePair.Create("Adds Sheltron.", "新增Sheltron。"),
                KeyValuePair.Create("- Required gauge threshold:", "- 所需量譜閾值："),
                KeyValuePair.Create("Adds Rampart.", "新增Rampart。"),
                KeyValuePair.Create("- Player HP must be under:", "- 玩家HP必須低於："),
                KeyValuePair.Create("Adds Sentinel.", "新增Sentinel。"),
                KeyValuePair.Create("Adds Hallowed Ground.", "新增Hallowed Ground。"),
                KeyValuePair.Create("Adds Low Blow or Shield Bash to the rotation when your target is casting, interruptible or not.", "當目標施法時，無論是否可打斷，將Low Blow或Shield Bash加入循環。"),
                KeyValuePair.Create("- Uses on cooldown alongside Requiescat.", "- 與Requiescat一起在冷卻時使用。"),
                KeyValuePair.Create("Adds Holy Circle to Advanced Mode.", "將Holy Circle新增到高階模式。"),
                KeyValuePair.Create("- At lower levels, uses Holy Circle instead.", "- 在較低等級時，使用Holy Circle代替。"),
                KeyValuePair.Create("Replaces Bulwark with an all-in-one mitigation button.", "用一鍵式減傷按鈕替換Bulwark。"),
                KeyValuePair.Create("Gives max priority to Hallowed Ground when the Health percentage threshold is met.", "當HP百分比達到閾值時，優先使用Hallowed Ground。"),
                KeyValuePair.Create("Adds Sheltron to the one-button mitigation.", "將Sheltron新增到一鍵式減傷按鈕。"),
                KeyValuePair.Create("Adds Divine Veil to the one-button mitigation.", "將Divine Veil新增到一鍵式減傷按鈕。"),
                KeyValuePair.Create("Adds Sentinel / Guardian to the one-button mitigation.", "將Sentinel / Guardian新增到一鍵式減傷按鈕。"),
                KeyValuePair.Create("Adds Hallowed Ground to the one-button mitigation.", "將Hallowed Ground新增到一鍵式減傷按鈕。"),
                KeyValuePair.Create("Adds Clemency to the one-button mitigation.", "將Clemency新增到一鍵式減傷按鈕。"),
                KeyValuePair.Create("Replaces Requiescat with all Requiescat-related actions.", "用所有與Requiescat相關的技能替換Requiescat。"),
                KeyValuePair.Create("- Prioritizes Confiteor and Blade actions when available.", "- 優先使用Confiteor和Blade技能。"),
                KeyValuePair.Create("- Uses Holy Spirit or Holy Circle when appropriate.", "- 在適當時使用Holy Spirit或Holy Circle。"),
                KeyValuePair.Create("Spirits Within / Circle of Scorn Feature", "Spirits Within/厄運流轉特性"),
                KeyValuePair.Create("Replaces Spirits Within with Circle of Scorn when available.", "當可用時，用厄運流轉替換Spirits Within。"),
                KeyValuePair.Create("Replaces Shield Lob with Holy Spirit when available.", "當可用時，用Holy Spirit替換Shield Lob。"),
                KeyValuePair.Create("- Must be under the effect of Divine Might or not moving.", "- 必須在Divine Might效果下或不移動時使用。"),
                KeyValuePair.Create("Uses Variant Spirit Dart whenever the debuff is not present on the target or about to expire.", "當目標沒有debuff或debuff即將結束時，使用Variant Spirit Dart。"),
                KeyValuePair.Create("Uses Variant Cure when the player's HP falls below the set threshold.", "當玩家HP低於設定閾值時，使用Variant Cure。"),
                KeyValuePair.Create("Uses Variant Ultimatum on cooldown as long as the target is within range.", "只要目標在範圍內，冷卻時使用Variant Ultimatum。"),
                KeyValuePair.Create("Turns Royal Authority Combo into an all-in-one damage button.", "將Royal Authority連擊變為一鍵式傷害按鈕。"),
                KeyValuePair.Create("Adds Shield Smite to Burst Mode.", "將Shield Smite新增到爆發模式。"),
                KeyValuePair.Create("Adds Imperator to Burst Mode.", "將Imperator新增到爆發模式。"),
                KeyValuePair.Create("Adds Confiteor to Burst Mode.", "將Confiteor新增到爆發模式。"),
                KeyValuePair.Create("Adds Holy Spirit to Burst Mode.", "將Holy Spirit新增到爆發模式。"),
                KeyValuePair.Create("Adds Intervene to Burst Mode.", "將Intervene新增到爆發模式。"),
                KeyValuePair.Create("Adds Intervene to Burst Mode when in melee range.", "在近戰範圍內時，將Intervene新增到爆發模式。"),
                KeyValuePair.Create("Adds Phalanx Combo to Burst Mode.", "將Phalanx連擊新增到爆發模式。"),
                KeyValuePair.Create("Adds Holy Sheltron to Burst Mode in melee range.", "在近戰範圍內時，將Holy Sheltron新增到爆發模式。"),
                KeyValuePair.Create("Attempts to hardcast Holy Spirit when not moving.", "在未移動時嘗試硬讀Holy Spirit"),
                KeyValuePair.Create("- Requires sufficient MP to cast.", "-需要足夠的MP來施放。"),
                KeyValuePair.Create("Uses Intervene while within melee range.", "在近戰範圍內使用Intervene"),
                KeyValuePair.Create("- May result in minor movement.", "-可能會導致輕微移動。"),
                KeyValuePair.Create("Adds Spirits Within to the rotation.", "將Spirits Within新增到循環。"),
                KeyValuePair.Create("Adds Fight or Flight to the normal logic.", "將戰逃反應新增到正常邏輯中。"),
                KeyValuePair.Create("Requires Requiescat to be ready.", "需要安魂祈禱準備就緒。"),
                KeyValuePair.Create("Normal Behavior", "普通模式"),
                KeyValuePair.Create("Add Drift Prevention", "預防循環軸偏移"),
                KeyValuePair.Create("Prevents Spirits Within and Circle of Scorn from drifting.", "防止深奧之靈和厄運流轉在循環軸中產生偏移。"),
                KeyValuePair.Create("Actions must be used within 5 seconds of each other.", "技能必須在彼此 5 秒內使用。"),
                KeyValuePair.Create("Melee Range", "近戰範圍"),
                KeyValuePair.Create("Only uses Intervene when it would not result in movement.", "僅在不會導致移動時使用Intervene。"),
                KeyValuePair.Create("- Requires target to be within zero distance.", "-需要目標在零距離內。"),
                KeyValuePair.Create("No Movement", "無移動"),
                KeyValuePair.Create("Blade Chain", "信念之劍連擊"),
                KeyValuePair.Create("Minimum MP", "最低魔力值"),
                KeyValuePair.Create("Shield Lob Only", "僅新增Shield Lob"),
                KeyValuePair.Create("Add Holy Spirit", "加入Holy Spirit"),
                KeyValuePair.Create("Circle of Scorn Option", "厄運流轉"),
                KeyValuePair.Create("Oath Gauge", "忠義量譜"),
                #endregion
            ];
        }
    }
}
