using System;
using System.Collections.Generic;
using WrathCombo.Combos.PvE;
using WrathCombo.Combos.PvP;
using WrathCombo.Extensions;

namespace WrathCombo.Resources.Dictionary.Chinese.Description
{
    public static class RDMDesc
    {
        public static IEnumerable<KeyValuePair<string, string>> GetDescriptions()
        {
            return
            [
                // Generated by the String Extraction and Translation Tool  
                // Model: DeepSeek v3  
                // Temperature: 0.1  
                // Generation Time: 2025-03-13 18:14:55  
                #region RDMPvE
                KeyValuePair.Create("Use Swiftcast for movement only.", "僅為了移動而使用即刻詠唱。"),
                KeyValuePair.Create("Replaces Jolt with a full one-button single target rotation.", "用一鍵單體循環替換Jolt。"),
                KeyValuePair.Create("To start the melee combo, you must be within melee range.", "要開始近戰連擊，你必須處於近戰範圍內。"),
                KeyValuePair.Create("Replaces Scatter with a full one-button AoE rotation.", "用一鍵AOE循環替換Scatter。"),
                KeyValuePair.Create("**Must move into melee range before melee combo**", "**必須在近戰連擊前進入近戰範圍**"),
                KeyValuePair.Create("Replace Jolt with Verthunder and Veraero.", "用Verthunder和Veraero替換Jolt。"),
                KeyValuePair.Create("Add Acceleration when no Verfire/Verstone proc is available.", "在沒有Verfire/Verstone觸發時新增Acceleration。"),
                KeyValuePair.Create("Add Acceleration when moving.", "在移動時新增Acceleration。"),
                KeyValuePair.Create("Add Swiftcast when all Acceleration charges are used.", "在所有Acceleration充能用完後新增Swiftcast。"),
                KeyValuePair.Create("Replace Jolt with Verfire and Verstone.", "用Verfire和Verstone替換Jolt。"),
                KeyValuePair.Create("Weave the following oGCD actions.", "插入以下oGCD技能。"),
                KeyValuePair.Create("Add the Reposte combo.", "新增回刺連擊。"),
                KeyValuePair.Create("**Must be in melee range or have Gap close with Corps-a-corps enabled**", "**必須處於近戰範圍或啟用Corps-a-corps進行接近**"),
                KeyValuePair.Create("Add Manafication and Embolden.", "新增Manafication和Embolden。"),
                KeyValuePair.Create("Hold both actions until you can perform a double melee combo.", "保留這兩個技能直到你可以執行雙近戰連擊。"),
                KeyValuePair.Create("Use Corp-a-corps when out of melee range and you have enough mana to start the melee combo.", "當你在近戰範圍外且有足夠的魔力開始近戰連擊時，使用Corps-a-corps。"),
                KeyValuePair.Create("Use Acceleration to unbalance mana prior to starting melee combo.", "在開始近戰連擊前使用Acceleration來平衡魔力。"),
                KeyValuePair.Create("Add Verflare/Verholy and other finishing moves.", "新增Verflare/Verholy和其他終結技。"),
                KeyValuePair.Create("Adds melee combo to the rotation when mana is at a certain threshold.", "當魔力達到一定閾值時，將近戰連擊新增到循環中。"),
                KeyValuePair.Create("Add Acceleration into the AoE rotation.", "在AOE循環中新增Acceleration。"),
                KeyValuePair.Create("Add Swiftcast when all Acceleration charges are used or when below level 50.", "在所有Acceleration充能用完或低於50級時新增Swiftcast。"),
                KeyValuePair.Create("Only use acceleration during weave windows.", "僅在插入視窗中使用Acceleration。"),
                KeyValuePair.Create("Weave the following oGCD actions:", "插入以下oGCD技能："),
                KeyValuePair.Create("Use Moulinet when over 50/50 mana", "當魔力超過50/50時使用Moulinet。"),
                KeyValuePair.Create("**Must be in range of Moulinet**", "**必須在Moulinet的範圍內**"),
                KeyValuePair.Create("Changes Swiftcast to Verraise when under the effect of Swiftcast or Dualcast.", "在Swiftcast或連續魔法效果下將Swiftcast改為Verraise。"),
                KeyValuePair.Create("If Swiftcast is on cooldown, change to Vercure to proc Dualcast.", "如果Swiftcast在冷卻中，改為Vercure以觸發連續魔法。"),
                KeyValuePair.Create("Replace Displacement with Corps-a-corps when out of range.", "當超出範圍時用Corps-a-corps替換Displacement。"),
                KeyValuePair.Create("Changes Embolden to Manafication when on cooldown.", "當Embolden在冷卻中時改為Manafication。"),
                KeyValuePair.Create("Changes Magick Barrier to Addle when on cooldown.", "當Magick Barrier在冷卻中時改為Addle。"),
                KeyValuePair.Create("Disables Embolden when buffed by another Red Mage's Embolden by replacing it with Savage Blade.", "當受到另一個赤魔道士的Embolden增益時，禁用Embolden並用Savage Blade替換。"),
                KeyValuePair.Create("Disables Magick Barrier when buffed by another Red Mage's Magick Barrier by replacing it with Savage Blade.", "當受到另一個赤魔道士的Magick Barrier增益時，禁用Magick Barrier並用Savage Blade替換。"),
                KeyValuePair.Create("Replaces Jolts.", "替換Jolts。"),
                KeyValuePair.Create("Turn Swiftcast into Variant Raise whenever you have the Swiftcast or Dualcast buffs.", "當你有Swiftcast或連續魔法增益時，將Swiftcast改為Variant Raise。"),
                KeyValuePair.Create("Replaces Vercure with Variant Cure.", "用Variant Cure替換Vercure。"),
                #endregion
                
                #region RDMPvP
                KeyValuePair.Create("Turns Jolt III into an all-in-one button.", "將Jolt III變為一個多功能按鈕。"),
                KeyValuePair.Create("- Will not attempt to cast Jolt III while moving by replacing it with Savage Blade.", "- 移動時不會嘗試施放Jolt III，而是用Savage Blade替換。"),
                KeyValuePair.Create("Uses Riposte and Scorch when available.", "在可用時使用Riposte和Scorch。"),
                KeyValuePair.Create("- Requires melee range for Riposte Combo.", "- 需要近戰範圍以使用Riposte連擊。"),
                KeyValuePair.Create("Uses Resolution when available.", "在可用時使用Resolution。"),
                KeyValuePair.Create("- Requires target's HP to be under:", "- 需要目標的生命值低於："),
                KeyValuePair.Create("Uses Embolden when available.", "在可用時使用Embolden。"),
                KeyValuePair.Create("- Requires Enchanted Riposte to be available.", "- 需要Enchanted Riposte可用。"),
                KeyValuePair.Create("- Will use alongside Corps-a-corps if enabled.", "- 如果啟用，將與Corps-a-corps一起使用。"),
                KeyValuePair.Create("Uses Corps-a-corps when available.", "在可用時使用Corps-a-corps。"),
                KeyValuePair.Create("Uses Displacement when available.", "在可用時使用Displacement。"),
                KeyValuePair.Create("- Will use when Scorch becomes available.", "- 當Scorch可用時使用。"),
                KeyValuePair.Create("- Requires target to be within melee range.", "- 需要目標在近戰範圍內。"),
                KeyValuePair.Create("Uses Forte when available.", "在可用時使用Forte。"),
                KeyValuePair.Create("- Requires player's HP to be under:", "- 需要玩家的生命值低於："),
                KeyValuePair.Create("Adds Purify when affected by crowd control.", "當受到群體控制影響時新增Purify。"),
                KeyValuePair.Create("- Requires Purify to be available.", "- 需要Purify可用。"),
                #endregion

                // Manually added
                KeyValuePair.Create("Melee combo overcap protection", "近戰連擊資源溢位保護"),
                KeyValuePair.Create("Gap close with Corps-a-corps Option", "使用Corps-a-corps接近敵人"),
                KeyValuePair.Create("Hold for Double Melee Combo Option [Lv.90]", "保留雙近戰連擊選項 [Lv.90]"),
                KeyValuePair.Create("Unbalance Mana Option", "魔元失衡"),
                KeyValuePair.Create("Include Swiftcast Option", "即刻詠唱"),
                KeyValuePair.Create("Weave oGCD Damage Option", "插入能力技傷害"),
                KeyValuePair.Create("Changes which action this option will replace.", "更改此選項將替換的技能。"),
                KeyValuePair.Create("Pool one charge for manual use.", "保留一次充能以供手動使用。"),
                KeyValuePair.Create("Use only in melee range.", "僅在近戰範圍內使用。"),
                KeyValuePair.Create("Enforced Melee Check", "強制近戰檢測"),
                KeyValuePair.Create("Once the melee combo has started, don't switch away even if target is out of range.", "一旦近戰連擊開始，即使目標超出範圍也不會切換。"),
                KeyValuePair.Create("Auto-Mode is enabled for this option.", "此選項已啟用自動模式。"),
                KeyValuePair.Create($"{RDM.Zwerchhau.ActionName()} & {RDM.Redoublement.ActionName()} will be placed on {RDM.Jolt.ActionName()}", $"{RDM.Zwerchhau.ActionName()}和{RDM.Redoublement.ActionName()}將被放置在 {RDM.Jolt.ActionName()}上。"),
                KeyValuePair.Create("Uses Prefulgence when available.", "當光芒四射可用時自動使用"),
                KeyValuePair.Create("Uses Displacement only when not moving.", "僅在未移動時使用移轉。"),
                KeyValuePair.Create("Uses Vice of Thorns when available.", "可用時使用荊棘環繞。"),
            ];
        }
    }
}
