using System;
using System.Collections.Generic;
using WrathCombo.Combos.PvE;
using WrathCombo.Combos.PvP;
using WrathCombo.Extensions;

namespace WrathCombo.Resources.Dictionary.Chinese.Description
{
    public static class RPRDesc
    {
        public static IEnumerable<KeyValuePair<string, string>> GetDescriptions()
        {
            return
            [
                // Generated by the String Extraction and Translation Tool  
                // Model: DeepSeek v3  
                // Temperature: 0.1  
                // Generation Time: 2025-03-13 18:14:55  
                #region RPR
                KeyValuePair.Create("Replaces Slice with a full one-button single target rotation.", "用一鍵單體循環替換Slice。"),
                KeyValuePair.Create("Replaces Spinning Scythe with a full one-button AoE rotation.", "用一鍵AOE循環替換Spinning Scythe。"),
                KeyValuePair.Create("Adds Arcane Circle to the rotation.", "將Arcane Circle加入循環。"),
                KeyValuePair.Create("Adds Plentiful Harvest to the rotation.", "將Plentiful Harvest加入循環。"),
                KeyValuePair.Create("Adds Shadow of Death to the rotation.", "將Shadow of Death加入循環。"),
                KeyValuePair.Create("Adds Soulsow to the rotation when out of combat and u dont have the buff.", "在戰鬥外且沒有增益時，將Soulsow加入循環。"),
                KeyValuePair.Create("Adds Soul Slice to the rotation.", "將Soul Slice加入循環。"),
                KeyValuePair.Create("Adds Bloodstalk to the rotation.", "將Bloodstalk加入循環。"),
                KeyValuePair.Create("Adds Gluttony to the rotation.", "將Gluttony加入循環。"),
                KeyValuePair.Create("Adds Gibbet and Gallows to the rotation.", "將Gibbet和Gallows加入循環。"),
                KeyValuePair.Create("Adds Enshroud to the rotation.", "將Enshroud加入循環。"),
                KeyValuePair.Create("Adds Void Reaping and Cross Reaping to the rotation.", "將Void Reaping和Cross Reaping加入循環。"),
                KeyValuePair.Create("(Disabling this may stop the one-button combo working during enshroud)", "（禁用此選項可能會停止在Enshroud期間的一鍵連擊功能）"),
                KeyValuePair.Create("Adds Lemure's Slice to the rotation.", "將Lemure's Slice加入循環。"),
                KeyValuePair.Create("Adds Communio to the rotation.", "將Communio加入循環。"),
                KeyValuePair.Create("Adds Sacrificium to the rotation.", "將Sacrificium加入循環。"),
                KeyValuePair.Create("Adds Perfectio to the rotation.", "將Perfectio加入循環。"),
                KeyValuePair.Create("Adds True North before Gibbet/Gallows when you are not in the correct position.", "當你不處於正確位置時，在Gibbet/Gallows前新增True North。"),
                KeyValuePair.Create("Hold True North for Gluttony Option", "為暴食保留真北"),
                KeyValuePair.Create("Will hold the last charge of True North for use with Gluttony, even when out of position for Gibbet/Gallows.", "即使不在Gibbet/Gallows的正確位置，也會保留True North的最後一層用於Gluttony。"),
                KeyValuePair.Create("Replaces the combo chain with Harpe when outside of melee range. Will not override Communio.", "在近戰範圍外時，用Harpe替換連擊鏈。不會覆蓋Communio。"),
                KeyValuePair.Create("Adds Harvest Moon if available, when outside of melee range. Will not override Communio.", "在近戰範圍外時，如果可用，新增Harvest Moon。不會覆蓋Communio。"),
                KeyValuePair.Create("Adds Whorl of Death to the rotation.", "將Whorl of Death加入循環。"),
                KeyValuePair.Create("Adds Soul Scythe to the rotation.", "將Soul Scythe加入循環。"),
                KeyValuePair.Create("Adds Grim Swathe to the rotation.", "將Grim Swathe加入循環。"),
                KeyValuePair.Create("Adds Guillotine to the rotation.", "將Guillotine加入循環。"),
                KeyValuePair.Create("Adds Grim Reaping to the rotation.", "將Grim Reaping加入循環。"),
                KeyValuePair.Create("Adds Lemure's Scythe to the rotation.", "將Lemure's Scythe加入循環。"),
                KeyValuePair.Create("Blood Stalk and Grim Swathe will turn into Gluttony when it is available.", "當Gluttony可用時，Blood Stalk和Grim Swathe會轉變為Gluttony。"),
                KeyValuePair.Create("Adds (Executioner's) Gibbet and Gallows on Blood Stalk.", "在Blood Stalk上新增Executioner's Gibbet（Gibbet）和Executioner's Gallows（Gallows）。"),
                KeyValuePair.Create("Adds (Executioner's) Guillotine on Grim Swathe.", "在Grim Swathe上新增Executioner's Guillotine（Guillotine）。"),
                KeyValuePair.Create("Adds Enshroud combo (Void/Cross Reaping, Communio, Lemure's Slice, Sacrificium and Perfectio) on Blood Stalk and Grim Swathe.", "在Blood Stalk和Grim Swathe上新增Enshroud連擊（Void Reaping/Cross Reaping、Communio、Lemure's Slice、Sacrificium和Perfectio）。"),
                KeyValuePair.Create("Adds Enshroud, Lemure's Slice and Sacrificium.", "新增Enshroud、Lemure's Slice和Sacrificium。"),
                KeyValuePair.Create("Adds only Sacrificium on Blood Stalk and Grim Swathe while enshrouded.", "在Enshroud期間，僅在Blood Stalk和Grim Swathe上新增Sacrificium。"),
                KeyValuePair.Create("Adds True North when under Gluttony and if Gibbet/Gallows options are selected to replace those skills.", "在Gluttony下且選擇了替換Gibbet/Gallows的選項時，新增True North。"),
                KeyValuePair.Create("Adds Soulsow to the skills selected below when out of combat. ", "在戰鬥外時，將Soulsow新增到下方選擇的技能中。"),
                KeyValuePair.Create("Will also add Soulsow to Harpe when in combat and no target is selected.", "在戰鬥中且沒有選擇目標時，也會將Soulsow新增到Harpe。"),
                KeyValuePair.Create("Adds Soulsow to Harpe during combat when no target is selected.", "在戰鬥中且沒有選擇目標時，將Soulsow新增到Harpe。"),
                KeyValuePair.Create("Replaces Arcane Circle with Plentiful Harvest when you have stacks of Immortal Sacrifice.", "當你有Immortal Sacrifice層數時，用Plentiful Harvest替換Arcane Circle。"),
                KeyValuePair.Create("Changes both Hell's Ingress and Hell's Egress turn into Regress when Threshold is active.", "當Threshold啟用時，將Hell's Ingress和Hell's Egress都轉變為Regress。"),
                KeyValuePair.Create("Turns Enshroud into Gibbet/Gallows to protect Soul Reaver waste.", "將Enshroud轉變為Gibbet/Gallows以防止Soul Reaver浪費。"),
                KeyValuePair.Create("Turns Enshroud to Communio and Perfectio when available to use.", "當可用時，將Enshroud轉變為Communio和Perfectio。"),
                KeyValuePair.Create("Adds Communio to Gibbet/Gallows and Guillotine.", "將Communio新增到Gibbet/Gallows和Guillotine。"),
                KeyValuePair.Create("Adds Lemure's Slice to Gibbet/Gallows and Lemure's Scythe to Guillotine.", "將Lemure's Slice新增到Gibbet/Gallows，將Lemure's Scythe新增到Guillotine。"),
                KeyValuePair.Create("Turns Slice Combo into an all-in-one damage button.", "將Slice連擊轉變為全合一傷害按鈕。"),
                KeyValuePair.Create("Adds Soul Slice to the main combo.", "將Soul Slice加入主連擊。"),
                KeyValuePair.Create("Add's Grim Swathe onto the main combo on cd", "將Grim Swathe加入主連擊並在冷卻時使用。"),
                KeyValuePair.Create("Adds Death Warrant onto the main combo when Plentiful Harvest is ready to use, or when Plentiful Harvest's cooldown is longer than Death Warrant's.", "當Plentiful Harvest準備就緒時，或當Plentiful Harvest的冷卻時間比Death Warrant長時，將Death Warrant加入主連擊。"),
                KeyValuePair.Create("Respects Immortal Sacrifice Pooling Option.", "尊重Immortal Sacrifice的積攢選項。"),
                KeyValuePair.Create("Pools stacks of Immortal Sacrifice before using Plentiful Harvest.", "在使用Plentiful Harvest之前積攢Immortal Sacrifice層數。"),
                KeyValuePair.Create("Also holds Plentiful Harvest if Death Warrant is on cooldown.", "如果Death Warrant在冷卻中，也會保留Plentiful Harvest。"),
                KeyValuePair.Create("Set the value to 3 or below to use Plentiful Harvest as soon as it's available.", "將值設定為3或以下以在Plentiful Harvest可用時立即使用。"),
                KeyValuePair.Create("Adds Lemure's Slice to the main combo during the Enshroud burst phase.", "在Enshroud爆發階段將夜遊魂收割加入主連擊。"),
                KeyValuePair.Create("Contains burst options.", "包含爆發選項。"),
                KeyValuePair.Create("Enshrouded Death Warrant Option", $"{RPRPvP.Buffs.Enshrouded.StatusName()}Death Warrant"),
                KeyValuePair.Create("Enshrouded Burst Option", $"{RPRPvP.Buffs.Enshrouded.StatusName()}爆發"),
                KeyValuePair.Create("Adds Death Warrant onto the main combo during the Enshroud burst when available.", "在Enshroud爆發期間，當可用時將Death Warrant加入主連擊。"),
                KeyValuePair.Create("Adds Communio onto the main combo when you have 1 stack of Enshroud remaining.", "當你剩餘1層Enshroud時，將Communio加入主連擊。"),
                KeyValuePair.Create("Will not trigger if you are moving.", "如果你在移動，則不會觸發。"),
                KeyValuePair.Create("Adds Harvest Moon onto the main combo when you're out of melee range, the GCD is not rolling and it's available for use. Will also throw it when the enemy is under 12k health for execute", "當你在近戰範圍外、GCD未滾動且可用時，將Harvest Moon加入主連擊。當敵人血量低於12k時也會投擲以執行斬殺。"),
                KeyValuePair.Create("Adds Arcane Crest to the main combo when under the set HP perecentage.", "當HP低於設定百分比時，將Arcane Crest加入主連擊。"),
                KeyValuePair.Create("Set a HP% Threshold for when SoD will not be automatically applied to the target.", "目標生命百分比達到此值時不會自動使用死亡之影。"),
                KeyValuePair.Create("Set a HP% Threshold for when WoD will not be automatically applied to the target.", "目標生命百分比達到此值不會自動使用死亡之渦。"),
                #endregion
                
                // Manually added
                KeyValuePair.Create("Lemure's Slice/Scythe Option", "Lemure's Slice/Lemure's Scythe"),
                KeyValuePair.Create("Void/Cross Reaping Option", "Void Reaping/Cross Reaping"),
                KeyValuePair.Create("Arcane Circle Harvest Feature", "Arcane Circle大豐收特性"),

                #region RPR
                KeyValuePair.Create("Set a value of Immortal Sacrifice Stacks to hold for burst.", "設定保留的死亡祭品層數以用於爆發"),
                KeyValuePair.Create("Set a HP percentage value.", "設定血量百分比閾值。"),
                KeyValuePair.Create("Caps at 90 to prevent waste.", "最高90%以避免浪費")
                #endregion
            ];
        }
    }
}
