using System;
using System.Collections.Generic;
using WrathCombo.Combos.PvE;
using WrathCombo.Combos.PvP;
using WrathCombo.Extensions;

namespace WrathCombo.Resources.Dictionary.Chinese.Description
{
    public static class SAMDesc
    {
        public static IEnumerable<KeyValuePair<string, string>> GetDescriptions()
        {
            return
            [
                // Generated by the String Extraction and Translation Tool  
                // Model: DeepSeek v3  
                // Temperature: 0.1  
                // Generation Time: 2025-03-13 18:14:55  
                #region SAMPvE
                KeyValuePair.Create("Replaces Hakaze with a full one-button single target rotation.", "用一鍵單體連擊替換Hakaze。"),
                KeyValuePair.Create("Replaces Fuga with a full one-button AoE rotation.", "用一鍵AOE連擊替換Fuga。"),
                KeyValuePair.Create("Adds Yukikaze combo to the rotation.", "將Yukikaze連擊新增到連擊中。"),
                KeyValuePair.Create("Adds Kasha combo to the rotation.", "將Kasha連擊新增到連擊中。"),
                KeyValuePair.Create("Adds Shinten to the rotation", "將Shinten新增到連擊中。"),
                KeyValuePair.Create("CDs on Main Combo", "有冷卻時間的技能"),
                KeyValuePair.Create("Collection of CD features on main combo.", "主連擊上的CD功能集合。"),
                KeyValuePair.Create("Adds Meikyo Shisui to the rotation.", "將Meikyo Shisui新增到連擊中。"),
                KeyValuePair.Create(" Dynamically changes usage for 2.14 or 2.08 GCD", "動態調整2.14或2.08GCD的使用。"),
                KeyValuePair.Create("Adds Ikishoten when at or below 50 Kenki.", "當Kenki為50或以下時新增Ikishoten。"),
                KeyValuePair.Create("Will dump Kenki at 10 seconds left to allow Ikishoten to be used.", "在剩餘10秒時消耗Kenki以允許使用Ikishoten。"),
                KeyValuePair.Create("Adds Shoha when you have three meditation stacks.", "當你有三層劍壓時新增Shoha。"),
                KeyValuePair.Create("Adds Senei to the rotation.", "將Senei新增到連擊中。"),
                KeyValuePair.Create("Adds Guren to the rotation if Senei is not unlocked.", "如果Senei未解鎖，則新增Guren到連擊中。"),
                KeyValuePair.Create("Adds Midare: Setsugekka, Higanbana, and Kaeshi: Setsugekka to the rotation.", "將Midare: Setsugekka、Higanbana和Kaeshi: Setsugekka新增到連擊中。"),
                KeyValuePair.Create("Adds Midare: Setsugekka, Higanbana, and Kaeshi: Setsugekka when you're not moving.", "當你不移動時新增Midare: Setsugekka、Higanbana和Kaeshi: Setsugekka。"),
                KeyValuePair.Create("Adds Ogi Namikiri and Kaeshi: Namikiri to the rotation.", "將Ogi Namikiri和Kaeshi: Namikiri新增到連擊中。"),
                KeyValuePair.Create("Adds Ogi Namikiri and Kaeshi: Namikiri when you're not moving.", "當你不移動時新增Ogi Namikiri和Kaeshi:Namikiri。"),
                KeyValuePair.Create("Adds Zanshin when ready to the rotation.", "當準備好時將Zanshin新增到連擊中。"),
                KeyValuePair.Create("Adds True North if Meikyo Shisui's buff is on you.", "如果Meikyo Shisui的buff在你身上，則新增True North。"),
                KeyValuePair.Create("Adds Enpi to the rotation when you are out of range.", "當你超出近戰範圍時將Enpi新增到連擊中。"),
                KeyValuePair.Create("Adds Bloodbath and Second Wind to the combo, using them when below the HP Percentage threshold.", "將Bloodbath和Second Wind新增到連擊中，在HP百分比低於閾值時使用它們。"),
                KeyValuePair.Create("Adds Oka combo to the rotation.", "將Oka連擊新增到連擊中。"),
                KeyValuePair.Create("Adds Kyuten to the rotation.", "將Kyuten新增到連擊中。"),
                KeyValuePair.Create("Adds Shoha when you have 3 meditation stacks.", "當你有三層劍壓時新增Shoha。"),
                KeyValuePair.Create("Adds Guren to the rotation.", "將Guren新增到連擊中。"),
                KeyValuePair.Create("Adds Hagakure to the rotation when there are three Sen.", "當集齊三閃時將Hagakure新增到連擊中。"),
                KeyValuePair.Create("Adds Tenka Goken, Midare: Setsugekka, and Kaeshi: Goken when ready and when you're not moving to the rotation.", "當準備好且不移動時將Tenka Goken、Midare: Setsugekka和Kaeshi: Goken新增到連擊中。"),
                KeyValuePair.Create("Adds Ogi Namikiri and Kaeshi: Namikiri when ready and when you're not moving to the rotation.", "當準備好且不移動時將Ogi Namikiri和Kaeshi: Namikiri新增到連擊中。"),
                KeyValuePair.Create("Adds Zanshin to the rotation.", "將Zanshin新增到連擊中。"),
                KeyValuePair.Create("Replace Yukikaze with its combo chain.", "用其連擊鏈替換Yukikaze。"),
                KeyValuePair.Create("Replace Kasha with its combo chain.", "用其連擊鏈替換Kasha。"),
                KeyValuePair.Create("Replace Gekko with its combo chain.", "用其連擊鏈替換Gekko。"),
                KeyValuePair.Create("Replace Oka with its combo chain.", "用其連擊鏈替換Oka。"),
                KeyValuePair.Create("Replace Mangetsu with its combo chain.", "用其連擊鏈替換Mangetsu。"),
                KeyValuePair.Create("Replace Meikyo Shisui with Gekko, Kasha, and Yukikaze depending on what is needed.", "根據需要將Meikyo Shisui替換為Gekko、Kasha和Yukikaze。"),
                KeyValuePair.Create("Replaces Meikyo Shisui with Savage Blade when you already have Meikyo Shisui active.", "當你已經啟用Meikyo Shisui時，用Savage Blade替換Meikyo Shisui。"),
                KeyValuePair.Create("Collection of Iaijutsu Features.", "Iaijutsu功能集合。"),
                KeyValuePair.Create("Replace Iaijutsu with Tsubame-gaeshi when appropriate.", "在適當時用Tsubame-gaeshi替換Iaijutsu。"),
                KeyValuePair.Create("Replace Iaijutsu with Shoha when meditation is 3.", "當劍壓滿時用Shoha替換Iaijutsu。"),
                KeyValuePair.Create("Replace Iaijutsu with Ogi Namikiri and Kaeshi: Namikiri when buffed with Ogi Namikiri Ready.", "當有Ogi Namikiri預備時用Ogi Namikiri和Kaeshi: Namikiri替換Iaijutsu。"),
                KeyValuePair.Create("Collection of Hissatsu: Shinten Features.", "Hissatsu: Shinten功能集合。"),
                KeyValuePair.Create("Replace Hissatsu: Shinten with Shoha when Meditation is full.", "當劍壓滿時用Shoha替換Hissatsu: Shinten。"),
                KeyValuePair.Create("Replace Hissatsu: Shinten with Senei when its cooldown is up.", "當冷卻結束時用Senei替換Hissatsu: Shinten。"),
                KeyValuePair.Create("Replace Hissatsu: Shinten with Zanshin when usable.", "當可用時用Zanshin替換Hissatsu: Shinten。"),
                KeyValuePair.Create("Collection of Hissatsu: Kyuten Features.", "Hissatsu: Kyuten功能集合。"),
                KeyValuePair.Create("Replace Hissatsu: Kyuten with Shoha when Meditation is full.", "當劍壓滿時用Shoha替換Hissatsu: Kyuten。"),
                KeyValuePair.Create("Replace Hissatsu: Kyuten with Guren when its cooldown is up.", "當冷卻結束時用Guren替換Hissatsu: Kyuten。"),
                KeyValuePair.Create("Replace Hissatsu: Kyuten with Zanshin when usable.", "當可用時用Zanshin替換Hissatsu: Kyuten。"),
                KeyValuePair.Create("Collection of Ikishoten Features.", "Ikishoten功能集合。"),
                KeyValuePair.Create("Replace Ikishoten with Ogi Namikiri & Kaeshi Namikiri when available.", "當可用時用Ogi Namikiri和Kaeshi Namikiri替換Ikishoten。"),
                KeyValuePair.Create("Replace Ikishoten with Shoha when Meditation is full before Ogi Namikiri.", "在Ogi Namikiri之前當劍壓滿時用Shoha替換Ikishoten。"),
                KeyValuePair.Create("Hissatsu: Gyoten becomes Yaten/Gyoten depending on the distance from your target.", "Hissatsu: Gyoten根據與目標的距離變為Yaten/Gyoten。"),
                // Ohter Descriptions
                KeyValuePair.Create("Set the Kenki overcap amount for ST combos.", "設定單目標連擊的劍氣溢位量。"),
                KeyValuePair.Create("Set the Kenki overcap amount for AOE combos.", "設定多目標連擊的劍氣溢位量。"),
                KeyValuePair.Create("Spends Kenki when at the set value or above.", "在劍氣達到設定值或以上時消耗劍氣。"),
                KeyValuePair.Create("Sens Feature", "三閃特性"),
                KeyValuePair.Create("Delay from first 明鏡止水 to next step. (seconds)", "從第一次明鏡止水到下一步的延遲時間（秒）"),
                KeyValuePair.Create("HP percent threshold to not save Kenki", "生命值百分比閾值低於此值時不保留劍氣"),
                KeyValuePair.Create("Delay is enforced by replacing your button with Savage Blade.", "透過將你的按鈕替換為Savage Blade來強制執行延遲。"),
                KeyValuePair.Create("Stop using Higanbana on targets below this HP % (0% = always use).", "目標生命值百分比低於此值時停用彼岸花（0 = 總是使用）"),
                #endregion
                
                #region SAMPvP
                KeyValuePair.Create("Turns Kasha Combo into an all-in-one button.", "將Kasha連擊整合為一個按鈕。"),
                KeyValuePair.Create("- Will not use actions with cast time while moving.", "- 移動時不會使用有施法時間的技能。"),
                KeyValuePair.Create("Uses Meikyo Shisui when available.", "在可用時使用Meikyo Shisui。"),
                KeyValuePair.Create("- Requires target to be in melee range.", "- 需要目標在近戰範圍內。"),
                KeyValuePair.Create("Uses Chiten when available.", "在可用時使用Chiten。"),
                KeyValuePair.Create("- Will not use outside combat.", "- 不會在戰鬥外使用。"),
                KeyValuePair.Create("Uses Mineuchi when available.", "在可用時使用Mineuchi。"),
                KeyValuePair.Create("Uses Soten when available.", "在可用時使用Soten。"),
                KeyValuePair.Create("- Will not use if already under Kaiten's effect.", "- 如果已經處於Kaiten效果下則不會使用。"),
                KeyValuePair.Create("Uses Zantetsuken when available.", "在可用時使用Zantetsuken。"),
                KeyValuePair.Create("- Will not use if target is invulnerable.", "- 如果目標處於無敵狀態則不會使用。"),
                KeyValuePair.Create("- Requires target to have player's Kuzushi.", "- 需要目標帶有玩家的Kuzushi效果。"),
                KeyValuePair.Create("Burst Preparation", "爆發準備"),
                KeyValuePair.Create("Also uses Mineuchi before Tendo Setsugekka.", "在天道雪月花前額外使用刀背擊打"),
                KeyValuePair.Create("Yukikaze Only", "僅限雪風"),
                KeyValuePair.Create("Also requires next weaponskill to be Yukikaze.", "同時要求下一個戰技必須是雪風")
                #endregion                
            ];
        }
    }
}
