using System;
using System.Collections.Generic;
using WrathCombo.Combos.PvE;
using WrathCombo.Combos.PvP;
using WrathCombo.Extensions;

namespace WrathCombo.Resources.Dictionary.Chinese.Description
{
    public static class SCHDesc
    {
        public static IEnumerable<KeyValuePair<string, string>> GetDescriptions()
        {
            return
            [
                // Generated by the String Extraction and Translation Tool  
                // Model: DeepSeek v3  
                // Temperature: 0.1  
                // Generation Time: 2025-03-13 18:14:55  
                #region SCH
                KeyValuePair.Create("Replaces Ruin I / Broils with options below", "用下方選項替換Ruin / Broil"),
                KeyValuePair.Create("Adds Summon Eos whenever you've not summoned your fairy.", "當你未召喚小仙女時新增Summon Eos。"),
                KeyValuePair.Create("Adds Chain Stratagem & Baneful Impact on cooldown with overlap protection", "新增Chain Stratagem & Baneful Impact，並在冷卻時使用，帶有重疊保護。"),
                KeyValuePair.Create("Use Aetherflow when out of Aetherflow stacks.", "當Aetherflow層數耗盡時使用Aetherflow。"),
                KeyValuePair.Create("Use Energy Drain to consume remaining Aetherflow stacks when Aetherflow is about to come off cooldown.", "當Aetherflow即將冷卻完畢時，使用Energy Drain消耗剩餘的Aetherflow層數。"),
                KeyValuePair.Create("Holds Energy Drain when Chain Stratagem is ready or has less than 10 seconds cooldown remaining.", "當Chain Stratagem準備就緒或剩餘冷卻時間少於10秒時，保留Energy Drain。"),
                KeyValuePair.Create("Use Ruin II when you have to move.", "當你需要移動時使用Ruin II。"),
                KeyValuePair.Create("Automatic DoT uptime.", "自動續DoT。"),
                KeyValuePair.Create("Replaces Art of War with options below.", "用下方選項替換Art of War。"),
                KeyValuePair.Create("Change Fey Blessing into Consolation when Seraph is out.", "當熾天使在場時，將Fey Blessing替換為Consolation。"),
                KeyValuePair.Create("Change Lustrate into Excogitation when Excogitation is ready.", "當Excogitation準備就緒時，將Lustrate替換為Excogitation。"),
                KeyValuePair.Create("Change Recitation into either Adloquium, Succor, Indomitability, or Excogitation when used.", "當使用Recitation時，將其替換為Adloquium、Succor、Indomitability或Excogitation。"),
                KeyValuePair.Create("Change Whispering Dawn into Fey Illumination, Fey Blessing, then Whispering Dawn when used.", "當使用Whispering Dawn時，將其替換為Fey Illumination、Fey Blessing，然後Whispering Dawn。"),
                KeyValuePair.Create("Adds Consolation during Seraph.", "在熾天使期間新增Consolation。"),
                KeyValuePair.Create("Consolation During Seraph Option", "熾天使Consolation"),
                KeyValuePair.Create("Replaces Succor with options below:", "用下方選項替換Succor："),
                KeyValuePair.Create("Adds Lucid Dreaming when MP isn't high enough to cast Succor.", "當MP不足以施放Succor時新增Lucid Dreaming。"),
                KeyValuePair.Create("Only uses Aetherflow is Indomitability is ready to use.", "僅在Indomitability準備就緒時使用Aetherflow。"),
                KeyValuePair.Create("Indomitability Ready Only Option", "僅在Indomitability就緒時"),
                KeyValuePair.Create("Use Dissipation when out of Aetherflow stacks.", "當Aetherflow層數耗盡時使用Dissipation。"),
                KeyValuePair.Create("Use Indomitability before using Succor.", "在使用Succor之前使用Indomitability。"),
                KeyValuePair.Create("Use Fey Illumination before using Succor.", "在使用Succor之前使用Fey Illumination。"),
                KeyValuePair.Create("Use Whispering Dawn before using Succor.", "在使用Succor之前使用Whispering Dawn。"),
                KeyValuePair.Create("Use Seraphism before using Succor.", "在使用Succor之前使用Seraphism。"),
                KeyValuePair.Create("Use Fey Blessing before using Succor.", "在使用Succor之前使用Fey Blessing。"),
                KeyValuePair.Create("Use Consolation before using Succor.", "在使用Succor之前使用Consolation。"),
                KeyValuePair.Create("Change Physick into Adloquium, Lustrate, then Physick with below options:", "將Physick替換為Adloquium、Lustrate，然後Physick，使用下方選項："),
                KeyValuePair.Create("Use Adloquium when missing Galvanize or target HP%% below:", "當目標缺少Galvanize或目標HP%%低於以下值時使用Adloquium："),
                KeyValuePair.Create("Use Lustrate when target HP%% below:", "當目標HP%%低於以下值時使用Lustrate："),
                KeyValuePair.Create("Use Excogitation when target HP%% below:", "當目標HP%%低於以下值時使用Excogitation："),
                KeyValuePair.Create("Use Protraction when target HP%% below:", "當目標HP%%低於以下值時使用Protraction："),
                KeyValuePair.Create("Use Aetherpact when target HP%% below:", "當目標HP%%低於以下值時使用Aetherpact："),
                KeyValuePair.Create("Aetherflow Helper Feature", "乙太超流輔助功能"),
                KeyValuePair.Create("Change Aetherflow-using skills to Aetherflow, Recitation, or Dissipation as selected.", "將使用Aetherflow的技能替換為Aetherflow、Recitation或Dissipation，根據選擇。"),
                KeyValuePair.Create("Prioritizes Recitation usage on Excogitation or Indomitability.", "優先在Excogitation或Indomitability上使用Recitation。"),
                KeyValuePair.Create("If Aetherflow is on cooldown, show Dissipation instead.", "如果Aetherflow在冷卻中，則顯示Dissipation。"),
                KeyValuePair.Create("Changes Swiftcast to Resurrection while Swiftcast is on cooldown.", "當Swiftcast在冷卻中時，將Swiftcast替換為Resurrection。"),
                KeyValuePair.Create("Change all fairy actions into Summon Eos when the Fairy is not summoned.", "當未召喚小仙女時，將所有小仙女技能替換為Summon Eos。"),
                KeyValuePair.Create("Changes Deployment Tactics to Adloquium until a party member has the Galvanize buff.", "將Deployment Tactics替換為Adloquium，直到隊伍成員獲得Galvanize增益。"),
                KeyValuePair.Create("Adds Recitation when off cooldown to force a critical Galvanize buff on a party member.", "當Recitation冷卻完畢時新增Recitation，以強制為隊伍成員施加暴擊Galvanize增益。"),
                KeyValuePair.Create("Turns Broil IV into all-in-one damage button.", "將Broil IV變為全能傷害按鈕。"),
                KeyValuePair.Create("Adds Expedient to Burst Mode to empower Biolysis.", "在爆發模式中新增Expedient以增強Biolysis。"),
                KeyValuePair.Create("Adds Biolysis use on cooldown to Burst Mode.", "在爆發模式中新增Biolysis，並在冷卻時使用。"),
                KeyValuePair.Create("Adds Deployment Tactics to Burst Mode when available.", "在爆發模式中新增Deployment Tactics，當可用時。"),
                KeyValuePair.Create("Adds Chain Stratagem to Burst Mode when available.", "在爆發模式中新增Chain Stratagem，當可用時。"),
                KeyValuePair.Create("Warning, will force the use of Adloquium, and normal Physick maybe unavailable.", "警告：將強制使用鼓舞激勵之策，且可能無法使用普通的醫術。"),
                KeyValuePair.Create("Sage Shield Check", "賢者護盾檢查"),
                KeyValuePair.Create("Dissipation First", "先使用轉化"),
                KeyValuePair.Create("Uses Dissipation first, then Aetherflow", "先使用轉化，再使用乙太超流"),
                KeyValuePair.Create("Aetherflow First", "先使用乙太超流"),
                KeyValuePair.Create("Uses Aetherflow first, then Dissipation", "先使用乙太超流，再使用轉化"),
                KeyValuePair.Create("Aetherflow remaining cooldown:", "乙太超流剩餘冷卻時間："),
                KeyValuePair.Create($"Warning, will force the use of {SCH.Adloquium.ActionName()}, and normal {SCH.Physick.ActionName()} maybe unavailable.", $"警告，將強制使用{SCH.Adloquium.ActionName()}，而正常的{SCH.Physick.ActionName()}可能不可用。"),
                KeyValuePair.Create("Enable to not override an existing Sage's shield.", "啟用以避免覆蓋現有賢者的護盾。"),
                KeyValuePair.Create($"{SCH.EmergencyTactics.ActionName()}", $"{SCH.EmergencyTactics.ActionName()}"),
                KeyValuePair.Create($"Use {SCH.EmergencyTactics.ActionName()} before {SCH.Adloquium.ActionName()}", $"在{SCH.Adloquium.ActionName()}之前使用{SCH.EmergencyTactics.ActionName()}"),
                KeyValuePair.Create("Start using when below HP %. Set to 100 to disable this check", "當生命值低於此百分比時開始使用。設定為100以禁用此檢查。"),
                KeyValuePair.Create("Stop using when above HP %.", "當生命值高於此百分比時停止使用。"),
                KeyValuePair.Create("Minimal Fairy Gauge to start using Aetherpact", "開始使用乙太契約所需的最低異想以太"),
                KeyValuePair.Create("Show Aetherflow On Energy Drain Only", "僅在吸取能量上顯示乙太超流"),
                KeyValuePair.Create("Show Aetherflow On All Aetherflow Skills", "在所有乙太超流技能上顯示乙太超流"),
                KeyValuePair.Create("Only when out of Aetherflow Stacks", "僅在乙太超流層數用盡時"),
                KeyValuePair.Create("Always when available", "只要可用就使用"),
                KeyValuePair.Create("On Indominability", "不屈不撓之策"),
                #endregion

                // Manually added
                KeyValuePair.Create("On Ruin/Broils", "應用於毀滅/死炎法"),
                KeyValuePair.Create("Apply options to Ruin and all Broils.", "將選項應用於毀滅及所有死炎法。"),
                KeyValuePair.Create("On Bio/Bio II/Biolysis", "應用於毒化/中度毒化/蠱毒法"),
                KeyValuePair.Create("Apply options to Bio and Biolysis.", "將選項應用於毒化及蠱毒法。"),
                KeyValuePair.Create("On Ruin II", "應用於毀壞"),
                KeyValuePair.Create("Apply options to Ruin II.", "將選項應用於毀壞。"),
            ];
        }
    }
}
