using System;
using System.Collections.Generic;
using WrathCombo.Combos.PvE;
using WrathCombo.Combos.PvP;
using WrathCombo.Extensions;

namespace WrathCombo.Resources.Dictionary.Chinese.Description
{
    public static class SGEDesc
    {
        public static IEnumerable<KeyValuePair<string, string>> GetDescriptions()
        {
            return
            [
                // Generated by the String Extraction and Translation Tool  
                // Model: DeepSeek v3  
                // Temperature: 0.1  
                // Generation Time: 2025-03-13 18:14:55  
                #region SGE
                KeyValuePair.Create("Adds various options to Dosis I/II/III.", "為Dosis I/II/III新增各種選項。"),
                KeyValuePair.Create("Use the Balance opener from level 92 onwards.", "從92級開始使用由The Balance社群建議的開場輸出循環。"),
                KeyValuePair.Create("Weaves Lucid Dreaming when your MP drops below the specified value.", "當你的MP低於指定值時插入Lucid Dreaming。"),
                KeyValuePair.Create("Eukrasian Dosis Option", "均衡注藥"),
                KeyValuePair.Create("Automatic DoT Uptime.", "自動續DoT。"),
                KeyValuePair.Create("Use selected instant cast actions while moving.", "在移動時使用選定的瞬發技能。"),
                KeyValuePair.Create("Use Phlegma if available and within range.", "如果Phlegma可用且在範圍內，則使用。"),
                KeyValuePair.Create("Adds Kardia when not under the effect.", "當沒有Kardia效果時新增Kardia。"),
                KeyValuePair.Create("Weaves Rhizomata when Addersgall gauge falls below the specified value.", "當Addersgall量譜低於指定值時插入Rhizomata。"),
                KeyValuePair.Create("Weaves Soteria if you have the Kardia buff.", "如果你有Kardia增益，則插入Soteria。"),
                KeyValuePair.Create("Weaves Psyche when available.", "當Psyche可用時插入。"),
                KeyValuePair.Create("Weaves Druochole when Addersgall gauge is greater than or equal to the specified value.", "當Addersgall量譜大於或等於指定值時插入Druochole。"),
                // 譯文原本漏了空白（"為DyskrasiaII"），技能名比對不到就會留著英文。
                KeyValuePair.Create("Adds various options to Dyskrasia I & II. Requires a target.", "為Dyskrasia I & 為Dyskrasia II新增各種選項。需要目標。"),
                KeyValuePair.Create("Uses Phlegma if available.", "如果Phlegma可用，則使用。"),
                KeyValuePair.Create("Use Toxikon if available.", "如果Toxikon可用，則使用。"),
                KeyValuePair.Create("Adds Pneuma if available.", "如果Pneuma可用，則新增。"),
                KeyValuePair.Create("Weaves Psyche if available.", "如果Psyche可用，則插入。"),
                KeyValuePair.Create("Uses Eukrasia for Eukrasia Dyskrasia.", "使用Eukrasia來施放Eukrasia Dyskrasia。"),
                KeyValuePair.Create("Weaves Lucid Dreaming when your MP falls below the specified value.", "當你的MP低於指定值時插入Lucid Dreaming。"),
                KeyValuePair.Create("Supports soft-targeting.", "支援軟目標選擇。"),
                KeyValuePair.Create("Options below are in priority order.", "下方選項按優先順序排序。"),
                KeyValuePair.Create("Applies Kardia to your target if it's not applied to anyone else.", "如果Kardia沒有施放在其他人身上，則對目標施放Kardia。"),
                KeyValuePair.Create("Diagnosis becomes Eukrasian Diagnosis if the shield is not applied to the target.", "如果目標沒有護盾，則將Diagnosis變為Eukrasian Diagnosis。"),
                KeyValuePair.Create("Applies Soteria.", "施放Soteria。"),
                KeyValuePair.Create("Applies Zoe.", "施放Zoe。"),
                KeyValuePair.Create("Triggers Pepsis if a shield is present.", "如果有護盾，則觸發Pepsis。"),
                KeyValuePair.Create("Adds Taurochole.", "新增Taurochole。"),
                KeyValuePair.Create("Applies Haima.", "施放Haima。"),
                KeyValuePair.Create("Adds Rhizomata when Addersgall is 0.", "當Addersgall為0時新增Rhizomata。"),
                KeyValuePair.Create("Applies Krasis.", "施放Krasis。"),
                KeyValuePair.Create("Applies Druochole.", "施放Druochole。"),
                KeyValuePair.Create("Adds Kerachole.", "新增Kerachole。"),
                KeyValuePair.Create("Adds Ixochole.", "新增Ixochole。"),
                KeyValuePair.Create("Adds Physis.", "新增Physis。"),
                KeyValuePair.Create("Adds Holos.", "新增Holos。"),
                KeyValuePair.Create("Adds Panhaima.", "新增Panhaima。"),
                KeyValuePair.Create("Adds Philosophia.", "新增Philosophia。"),
                KeyValuePair.Create("Adds Zoe.", "新增Zoe。"),
                KeyValuePair.Create("Chain to Pneuma After.", "在Pneuma之後連鎖。"),
                KeyValuePair.Create("Prognosis becomes Eukrasian Prognosis if the shield is not applied.", "如果沒有護盾，則將Prognosis變為Eukrasia Prognosis。"),
                KeyValuePair.Create("Replaces Addersgall skills with Rhizomata when empty.", "當Addersgall技能為空時，用Rhizomata替換。"),
                KeyValuePair.Create("Turns Taurochole to Druochole when Taurochole is on cooldown.", "當Taurochole在冷卻時，將其變為Druochole。"),
                KeyValuePair.Create("Places Zoe on top of Pneuma when both actions are on cooldown.", "當Pneuma和Zoe都在冷卻時，將Zoe放在Pneuma之上。"),
                KeyValuePair.Create("Changes Swiftcast to Egeiro while Swiftcast is on cooldown.", "當Swiftcast在冷卻時，將其變為Egeiro。"),
                KeyValuePair.Create("Soteria turns into Kardia when not active or Soteria is on-cooldown.", "當Soteria未啟用或在冷卻時，Soteria變為Kardia。"),
                KeyValuePair.Create("Eukrasia turns into the selected Eukrasian-type action when active.", "當Eukrasia啟用時，將其變為選定的Eukrasia型別技能。"),
                KeyValuePair.Create("Prevents you from wasting actions if under the effect of someone else's actions", "防止你在他人技能效果下浪費技能。"),
                KeyValuePair.Create("Don't use Kerachole when under the effect of someone's Kerachole", "在他人的Kerachole效果下不要使用Kerachole。"),
                KeyValuePair.Create("Don't use Kerachole when under the effect of someone's Sacred Soil", "在他人的Sacred Soil效果下不要使用Kerachole。"),
                KeyValuePair.Create("Don't use Panhaima when under the effect of someone's Panhaima", "在他人的Panhaima效果下不要使用Panhaima。"),
                KeyValuePair.Create("Don't use Philosophia when under the effect of someone's Philosophia", "在他人的Philosophia效果下不要使用Philosophia。"),
                KeyValuePair.Create("Turns Dosis III into an all-in-one damage button.", "將Dosis III變為一個全能傷害按鈕。"),
                KeyValuePair.Create("Adds Pneuma to Burst Mode.", "將Pneuma新增到爆發模式。"),
                KeyValuePair.Create("Adds Eukrasia to Burst Mode.", "將Eukrasia新增到爆發模式。"),
                KeyValuePair.Create("Adds Phlegma to Burst Mode.", "將Phlegma新增到爆發模式。"),
                KeyValuePair.Create("Adds Psyche to Burst Mode.", "將Psyche新增到爆發模式。"),
                KeyValuePair.Create("Adds Toxikon to Burst Mode.", "將Toxikon新增到爆發模式。"),
                KeyValuePair.Create("Adds Toxikon II to Burst Mode.", "將Toxikon II新增到爆發模式。"),
                KeyValuePair.Create("Adds Kardia to Burst Mode.", "將Kardia新增到爆發模式。"),
                KeyValuePair.Create("Customize your AoE healing to your liking.", "根據你的喜好自定義範圍治療技能。"),
                KeyValuePair.Create("Enable to not override an existing Scholar's shield.", "啟用以避免覆蓋學者的護盾。"),
                KeyValuePair.Create("Shield Check: Percentage of Party Members without shields to check for.", "護盾檢查：檢查沒有護盾的小隊成員的百分比。"),
                KeyValuePair.Create("Ignore Shield Check", "忽略護盾檢查"),
                KeyValuePair.Create("Overflow Protection", "溢位保護"),
                #endregion

                // Manually added                
                KeyValuePair.Create("Warning, will force the use of 均衡診斷, and normal 診斷 will be unavailable.", "警告：將強制使用均衡診斷，且無法使用普通的診斷。"),
                KeyValuePair.Create("Apply all selected options to 注藥II", "應用所有選項到注藥II"),
                KeyValuePair.Create("注藥 & 注藥III will behave normally.", "注藥 & 注藥III保留原樣不被替換。"),
                KeyValuePair.Create("Addersgall", "蛇膽"),
                KeyValuePair.Create($"Use {SGE.Toxikon.ActionName()} when Addersting == available.", $"當{SGEPvP.Buffs.Addersting.StatusName()}可用時使用{SGE.Toxikon.ActionName()}。"),
                KeyValuePair.Create($"Use {SGE.Dyskrasia.ActionName()} when in range of a selected enemy target.", $"當在選中敵方目標的範圍內時使用{SGE.Dyskrasia.ActionName()}。"),
                KeyValuePair.Create($"Use {SGE.Eukrasia.ActionName()}.", $"使用{SGE.Eukrasia.ActionName()}。"),
            ];
        }
    }
}
