using ECommons.ExcelServices;
using System;
using System.Collections.Generic;
using WrathCombo.Combos.PvE;
using WrathCombo.Combos.PvP;
using WrathCombo.Extensions;

namespace WrathCombo.Resources.Dictionary.Chinese.Description
{
    public static class SMNDesc
    {
        public static IEnumerable<KeyValuePair<string, string>> GetDescriptions()
        {
            return
            [
                // Generated by the String Extraction and Translation Tool  
                // Model: DeepSeek v3  
                // Temperature: 0.1  
                // Generation Time: 2025-03-13 18:14:55  
                #region SMNPvE
                KeyValuePair.Create("Replaces Ruin with a full one-button single target rotation.", "用一鍵單目標循環替換Ruin。"),
                KeyValuePair.Create("Replaces Outburst with a full one-button AoE rotation.", "用一鍵AoE循環替換Outburst。"),
                KeyValuePair.Create("Replaces Emerald Ruin III with Ruin III in the rotation when standing still and Ruin Mastery III is not active.", "當站立不動且Ruin Mastery III未啟用時，在循環中用Ruin III替換Emerald Ruin III。"),
                KeyValuePair.Create("Demi Attacks Combo Option", "亞靈神攻擊連擊選項"),
                KeyValuePair.Create("Adds Demi Summon oGCDs to the single target combo.", "將亞靈神召喚獸的能力技新增到單體連擊中。"),
                KeyValuePair.Create("Adds Rekindle to the single target combo.", "將Rekindle新增到單目標連擊中。"),
                KeyValuePair.Create("Egi Attacks Combo Option", "三神攻擊連擊選項"),
                KeyValuePair.Create("Adds Lux Solaris to the single target combo.", "將Lux Solaris新增到單目標連擊中。"),
                KeyValuePair.Create("Adds Gemshine to the single target combo.", "將Gemshine新增到單目標連擊中。"),
                KeyValuePair.Create("Adds Lucid Dreaming to the single target combo when MP falls below the set value.", "當MP低於設定值時，將Lucid Dreaming新增到單目標連擊中。"),
                KeyValuePair.Create("Add Egi Astralflow", "新增三神星極超流"),
                KeyValuePair.Create("Choose which Egi Astralflows to add to the rotation.", "選擇將哪些三神星極超流新增到循環中。"),
                KeyValuePair.Create("Adds Ruin IV to the single target combo.", "將Ruin IV新增到單目標連擊中。"),
                KeyValuePair.Create("Uses when moving during Garuda Phase and you have no attunement, when moving during Ifrit phase, or when you have no active Egi or Demi summon.", "在風神階段移動且沒有共鳴時使用，或在火神階段移動時使用，或當沒有啟用的三神或亞靈神召喚時使用。"),
                KeyValuePair.Create("Energy Attacks Combo Option", "能量攻擊連擊"),
                KeyValuePair.Create("Adds Energy Drain and Fester to the single target combo.", "將Energy Drain和Fester新增到單目標連擊中。"),
                KeyValuePair.Create("Will be used on cooldown.", "將在冷卻時使用。"),
                KeyValuePair.Create("Pools damage oGCDs for use inside the selected Demi phase while under the Searing Light buff.", "在Searing Light增益下，將傷害能力技集中用於選定的亞靈神階段內。"),
                KeyValuePair.Create("Bahamut Burst becomes Solar Bahamut Burst at Lv100.", "在100級時，Bahamut Burst變為Solar Bahamut Burst。"),
                KeyValuePair.Create("Checks for any Searing Light for bursting rather than just your own.", "檢查任何Searing Light以進行爆發，而不僅僅是你自己的。"),
                KeyValuePair.Create("Use this option if partied with multiple SMN and are worried about your Searing Light being wasted.", "如果與多個召喚士組隊並擔心你的Searing Light被浪費，請使用此選項。"),
                KeyValuePair.Create("Adds Searing Light to the single target combo.", "將Searing Light新增到單目標連擊中。"),
                KeyValuePair.Create("Casts Searing Light only during Demi phases.", "僅在亞靈神階段施放Searing Light。"),
                KeyValuePair.Create("Reflects Demi choice selected under 'Pooled oGCDs Option'.", "反映在“Pooled oGCDs Option”下選擇的亞靈神階段。"),
                KeyValuePair.Create("Not recommended for SpS Builds.", "不推薦用於靈活詠速構建。"),
                KeyValuePair.Create("Adds Searing Flash to the single target combo.", "將Searing Flash新增到單目標連擊中。"),
                KeyValuePair.Create("Demi Summons Combo Option", "亞靈神召喚連擊"),
                KeyValuePair.Create("Adds Demi summons to the single target combo.", "將亞靈神召喚新增到單目標連擊中。"),
                KeyValuePair.Create("Swiftcast Egi Ability Option", "即刻詠唱三神技能"),
                KeyValuePair.Create("Uses Swiftcast during the selected Egi summon.", "在選定的三神召喚期間使用Swiftcast。"),
                KeyValuePair.Create("Egi Summons Combo Option", "三神召喚連擊"),
                KeyValuePair.Create("Adds Egi summons to the single target combo.", "將三神召喚新增到單目標連擊中。"),
                KeyValuePair.Create("Will prioritise the Egi selected below.", "將優先選擇下面選定的三神。"),
                KeyValuePair.Create("Adds Energy Siphon and Painflare to the AoE combo.", "將Energy Siphon和Painflare新增到AoE連擊中。"),
                KeyValuePair.Create("Adds Searing Light to the AoE combo.", "將Searing Light新增到AoE連擊中。"),
                KeyValuePair.Create("Adds Demi Summon oGCDs to the AoE combo.", "將亞靈神召喚獸能力技新增到AoE連擊中。"),
                KeyValuePair.Create("Adds Rekindle to the AoE combo.", "將Rekindle新增到AoE連擊中。"),
                KeyValuePair.Create("Any Searing Burst Option", "任意灼熱之光爆發"),
                KeyValuePair.Create("Checks for any Searing light for bursting rather than just your own.", "檢查任何Searing Light以進行爆發，而不僅僅是你自己的。"),
                KeyValuePair.Create("Use this option if partied with multiple SMN and are worried about your Searing being overwritten.", "如果與多個召喚士組隊並擔心你的Searing被覆蓋，請使用此選項。"),
                KeyValuePair.Create("Adds Searing Flash to the AoE combo.", "將Searing Flash新增到AoE連擊中。"),
                KeyValuePair.Create("Adds Lux Solaris to the AoE combo.", "將Lux Solaris新增到AoE連擊中。"),
                KeyValuePair.Create("Adds Lucid Dreaming to the AoE combo when MP falls below the set value.", "當MP低於設定值時，將Lucid Dreaming新增到AoE連擊中。"),
                KeyValuePair.Create("Adds Demi summons to the AoE combo.", "將亞靈神召喚新增到AoE連擊中。"),
                KeyValuePair.Create("Adds Ruin IV to the AoE combo.", "將Ruin IV新增到AoE連擊中。"),
                KeyValuePair.Create("Adds Precious Brilliance to the AoE combo.", "將Precious Brilliance新增到AoE連擊中。"),
                KeyValuePair.Create("Adds Egi summons to the AoE combo.", "將三神召喚新增到AoE連擊中。"),
                KeyValuePair.Create("Change Fester into Energy Drain when out of Aetherflow stacks.", "當Aetherflow層數耗盡時，將Fester更改為Energy Drain。"),
                KeyValuePair.Create("Changes Fester to Ruin IV when out of Aetherflow stacks, Energy Drain is on cooldown, and Ruin IV is available.", "當Aetherflow層數耗盡、Energy Drain在冷卻中且Ruin IV可用時，將Fester更改為Ruin IV。"),
                KeyValuePair.Create("Change Painflare into Energy Siphon when out of Aetherflow stacks.", "當Aetherflow層數耗盡時，將Painflare更改為Energy Siphon。"),
                KeyValuePair.Create("Carbuncle Reminder Feature", "寶石獸提醒"),
                KeyValuePair.Create("Replaces most offensive actions with Summon Carbuncle when it is not summoned.", "當Summon Carbuncle未召喚時，用Summon Carbuncle替換大多數攻擊技能。"),
                KeyValuePair.Create("Astral Flow/Enkindle on Demis Feature", "星極超流/迸發新增到亞靈神召喚"),
                KeyValuePair.Create("Adds Enkindle Bahamut, Enkindle Phoenix and Astral Flow to their relevant summons.", "將Enkindle Bahamut、Enkindle Phoenix和Astral Flow新增到它們相關的召喚中。"),
                KeyValuePair.Create("Changes Swiftcast to Raise when on cooldown.", "當Swiftcast在冷卻中時，將其更改為Raise。"),
                KeyValuePair.Create("Ruin III Mobility Feature", "大毀滅機動性功能"),
                KeyValuePair.Create("Puts Ruin III on Ruin IV when you don't have Further Ruin.", "當你沒有毀絕預備時，將Ruin III放在Ruin IV上。"),
                KeyValuePair.Create("Egi Abilities on Summons Feature", "三神技能新增到三神召喚"),
                KeyValuePair.Create("Adds Egi Abilities (Astral Flow) to Egi summons when ready.", "當準備好時，將三神技能（星極超流）新增到三神召喚中。"),
                KeyValuePair.Create("Egi abilities will appear on their respective Egi summon ability, as well as Titan.", "三神技能將出現在它們各自的三神召喚上。"),
                KeyValuePair.Create("Changes Painflare to Ruin IV when out of Aetherflow stacks, Energy Siphon is on cooldown, and Ruin IV is up.", "當Aetherflow層數耗盡、Energy Siphon在冷卻中且Ruin IV可用時，將Painflare更改為Ruin IV。"),
                KeyValuePair.Create("Turn Swiftcast into Variant Raise whenever you have the Swiftcast buff.", "當你有Swiftcast增益時，將Swiftcast更改為Variant Raise。"),
                KeyValuePair.Create("Solar Bahamut/Bahamut", "烈日龍神/龍神"),
                KeyValuePair.Create("Bursts during Bahamut phase.", "在龍神爆發。"),
                KeyValuePair.Create("Bahamut burst phase becomes Solar Bahamut at Lv100.", "在等級 100 時，龍神爆發階段改為烈日龍神。"),
                KeyValuePair.Create("Bursts during Phoenix phase.", "在不死鳥階段爆發。"),
                KeyValuePair.Create("Any Demi Phase", "任意亞靈神階段"),
                KeyValuePair.Create("Bursts during any Demi Summon phase.", "在任何亞靈神召喚階段爆發。"),
                KeyValuePair.Create("Flexible (SpS) Option", "靈活（詠速）選項"),
                KeyValuePair.Create("Bursts when Searing Light is ready, regardless of phase.", "當灼熱之光準備就緒時爆發，無論處於哪個階段。"),
                KeyValuePair.Create("Sets the amount of GCDs under Demi summon to wait for oGCD use.", "設定在亞靈神召喚下等待使用能力技的GCD數量。"),
                KeyValuePair.Create($"Do not use when under another {Job.SMN.GetData().Abbreviation}'s {SMN.Buffs.SearingLight.StatusName()} buff.", $"當處於其他召喚士的{SMN.Buffs.SearingLight.StatusName()}增益下時不要使用。"),
                KeyValuePair.Create($"Do not user when under another {Job.SMN.GetData().Abbreviation}'s {SMN.Buffs.SearingLight.StatusName()} buff.", $"當處於其他召喚士的{SMN.Buffs.SearingLight.StatusName()}增益下時不要使用。"),
                KeyValuePair.Create($"Saves your {SMN.SearingLight.ActionName()} if you already have the buff from another {Job.SMN.GetData().Abbreviation}.", $"如果你已經擁有其他召喚士的增益，則保留你的 {SMN.SearingLight.ActionName()}。"),
                KeyValuePair.Create("Enforced Crimson Cyclone Melee Check", "強制深紅旋風近戰範圍檢查"),
                KeyValuePair.Create("Only uses Crimson Cyclone within melee range.", "僅在近戰範圍內使用深紅旋風。"),
                KeyValuePair.Create("Pooled oGCDs Option", "儲備能力技"),
                KeyValuePair.Create("Enforced ", "儲備能力技"),
                #endregion

                #region SMNPvP
                KeyValuePair.Create("Turns Ruin III into an all-in-one damage button.", "將Ruin III變為一個全能傷害技能按鈕。"),
                KeyValuePair.Create("Only uses Crimson Cyclone when in melee range.", "僅在近戰範圍內使用Crimson Cyclone。"),
                KeyValuePair.Create("Adds Radiant Aegis to Burst Mode when available, and your HP is at or below the set percentage.", "當可用且你的HP低於或等於設定百分比時，將Radiant Aegis加入Burst Mode。"),
                KeyValuePair.Create("Adds Crimson Cyclone to Burst Mode.", "將Crimson Cyclone加入Burst Mode。"),
                KeyValuePair.Create("Adds Crimson Strike to Burst Mode.", "將Crimson Strike加入Burst Mode。"),
                KeyValuePair.Create("Adds Mountain Buster to Burst Mode.", "將Mountain Buster加入Burst Mode。"),
                KeyValuePair.Create("Adds Slipstream to Burst Mode.", "將Slipstream加入Burst Mode。"),
                KeyValuePair.Create("Adds Necrotize to Burst Mode.", "將Necrotize加入Burst Mode。"),
                KeyValuePair.Create("Adds DeathFlare to Burst Mode.", "將DeathFlare加入Burst Mode。"),
                KeyValuePair.Create("Adds Brand of Purgatory to Burst Mode.", "將Brand of Purgatory加入Burst Mode。"),
                #endregion

                // Manually added
                KeyValuePair.Create("Use Ruin III instead of Emerald Ruin III when standing still", "站立不動時使用大毀滅代替綠寶石大毀滅"),
                KeyValuePair.Create("Swiftcasts the first available Egi when Swiftcast is ready.", "即刻詠唱冷卻即用，不管是哪個蠻神"),
                KeyValuePair.Create("Swiftcasts Slipstream", "即刻詠唱螺旋氣流"),
                KeyValuePair.Create("Swiftcasts Ruby Ruin/Ruby Rite", "即刻詠唱紅寶石毀滅（大毀滅/毀壞）/紅寶石之儀"),
                KeyValuePair.Create("Summons Titan, Garuda then Ifrit.", "召喚順序：土神->風神->火神"),
                KeyValuePair.Create("Summons Garuda, Titan then Ifrit.", "召喚順序：風土神->土神->火神"),
                KeyValuePair.Create("Garuda", "風神"),
                KeyValuePair.Create("Ifrit", "火神"),
                KeyValuePair.Create("Titan", "土神"),
            ];
        }
    }
}
