using System;
using System.Collections.Generic;
using WrathCombo.Combos.PvE;
using WrathCombo.Combos.PvP;
using WrathCombo.Extensions;

namespace WrathCombo.Resources.Dictionary.Chinese.Description
{
    public static class VPRDesc
    {
        public static IEnumerable<KeyValuePair<string, string>> GetDescriptions()
        {
            return
            [
                // Generated by the String Extraction and Translation Tool  
                // Model: DeepSeek v3  
                // Temperature: 0.1  
                // Generation Time: 2025-03-13 18:14:55  
                #region VPRPvE
                KeyValuePair.Create("Replaces Steel Fangs with a full one-button single target rotation.", "用一鍵完整單體循環替換Steel Fangs。"),
                KeyValuePair.Create("Replaces Steel Maw with a full one-button AoE rotation.", "用一鍵完整AOE循環替換Steel Maw。"),
                KeyValuePair.Create("These features are ideal if you want to customize the rotation.", "適合想要自定義循環的玩家。"),
                KeyValuePair.Create(" Does not check positional choice.", "不檢查位置選擇。"),
                KeyValuePair.Create(" Always does Hunter's Coil first (FLANK)", "總是先使用貳之蛇【猛襲】（側方身位）。"),
                KeyValuePair.Create("Adds Serpents Ire to the rotation.", "將Serpents Ire加入循環。"),
                KeyValuePair.Create("Adds Vicewinder to the rotation.", "將Vicewinder加入循環。"),
                KeyValuePair.Create("Adds Swiftskin's Coil and Hunter's Coil to the rotation.", "將Swiftskin's Coil和Hunter's Coil加入循環。"),
                KeyValuePair.Create("Will automatically swap depending on your position.", "會根據你的身位自動切換。"),
                KeyValuePair.Create("Adds Twinfang and Bloodfang to the rotation.", "將飛蛇連尾擊和飛蛇亂尾擊加入循環。"),
                KeyValuePair.Create("Adds Serpents Tail to the rotation.", "將Serpents Tail加入循環。"),
                KeyValuePair.Create("Adds Uncoiled Fury to the rotation.", "將Uncoiled Fury加入循環。"),
                KeyValuePair.Create("Adds Uncoiled Twinfang and Uncoiled Twinblood to the rotation.", "將Uncoiled Twinfang和Uncoiled Twinblood加入循環。"),
                KeyValuePair.Create("Adds Reawaken to the rotation.", "將Reawaken加入循環。"),
                KeyValuePair.Create("Adds Generation and Legacy to the rotation.", "將祖靈之牙和祖靈之蛇加入循環。"),
                KeyValuePair.Create("Adds True North when you are not in the correct position for the enhanced potency bonus.", "當你不處於正確位置以獲得增強威力加成時，新增True North。"),
                KeyValuePair.Create("Adds Writhing Snap to the rotation when you are out of melee range.", "當你處於近戰範圍外時，將Writhing Snap加入循環。"),
                KeyValuePair.Create("Adds Uncoiled Fury to the rotation when you are out of melee range and have Rattling Coil charges.", "當你處於近戰範圍外且擁有Rattling Coil充能時，將Uncoiled Fury加入循環。"),
                KeyValuePair.Create("Adds Bloodbath and Second Wind to the rotation.", "將Bloodbath和Second Wind加入循環。"),
                KeyValuePair.Create("Adds Vicepit to the rotation.", "將Vicepit加入循環。"),
                KeyValuePair.Create("Disables the range check for Vicepit, so it will be used even without a target selected.", "禁用Vicepit的範圍檢查，即使沒有選擇目標也會使用。"),
                KeyValuePair.Create("Adds Swiftskin's Den and Hunter's Den to the rotation.", "將Swiftskin's Den和Hunter's Den加入循環。"),
                KeyValuePair.Create("Disables the range check for Swiftskin's Den and Hunter's Den, so they will be used even without a target selected.", "禁用Swiftskin's Den和Hunter's Den的範圍檢查，即使沒有選擇目標也會使用。"),
                KeyValuePair.Create("Adds Twinfang and Twinblood to the rotation.", "將Twinfang和Twinblood加入循環。"),
                KeyValuePair.Create("Disables the range check for Reawaken, so it will be used even without a target selected.", "禁用Reawaken的範圍檢查，即使沒有選擇目標也會使用。"),
                KeyValuePair.Create("Replaces Vicewinder with Hunter's/Swiftskin's Coils.", "用Hunter's Coils/Swiftskin's Coils替換Vicewinder。"),
                // 譯文原本誤植成 Hunter's Coils（複製上一行忘了改），會顯示成錯誤的技能。
                KeyValuePair.Create("Replaces Vicepit with Hunter's/Swiftskin's Dens.", "用Hunter's Dens/Swiftskin's Dens替換Vicepit。"),
                KeyValuePair.Create("Replaces Uncoiled Fury with Uncoiled Twinfang and Uncoiled Twinblood.", "用Uncoiled Twinfang和Uncoiled Twinblood替換Uncoiled Fury。"),
                KeyValuePair.Create("Replaces Option with the Generations.", "用祖靈之牙替換。"),
                KeyValuePair.Create("Replaces Option with the Legacys.", "用祖靈之蛇替換。"),
                KeyValuePair.Create("Combines Serpent's Tail, Twinfang, and Twinblood to one button.", "將Serpent's Tail、Twinfang和Twinblood合併為一個按鈕。"),
                KeyValuePair.Create("Adds Twinfang and Twinblood to the button.", "將Twinfang和Twinblood新增到按鈕。"),
                KeyValuePair.Create("Legacy Buttons", "祖靈之蛇"),
                KeyValuePair.Create("Replaces Generations with the Legacys.", "用祖靈之蛇替換祖靈之牙。"),
                KeyValuePair.Create("Replaces basic combo with Death Rattle or Last Lash when applicable.", "在適用時用Death Rattle或Last Lash替換基礎連擊。"),
                KeyValuePair.Create("Set a HP% Threshold to use all charges.", "設定生命百分比閾值以使用所有充能。"),
                KeyValuePair.Create("Disable Range Check", "禁用範圍檢查"),
                KeyValuePair.Create("Include Twin Combo Actions", "包含雙牙連擊技能"),
                KeyValuePair.Create("Vicewinder - Coils", "參之蛇【強碎】 - 盤蛇"),
                KeyValuePair.Create("Uncoiled - Twins", "飛蛇連擊"),
                KeyValuePair.Create("Vicepit - Dens", "壹之大蛇【強碎】 - 盤蝰"),
                KeyValuePair.Create("Reawaken - Generation", "祖靈降臨 - 祖靈之牙"),
                KeyValuePair.Create("Reawaken - Legacy", "祖靈降臨 - 祖靈之蛇"),
                KeyValuePair.Create("Combined Combo Ability Feature", "組合連擊技"),
                KeyValuePair.Create($"Stop using {VPR.Reawaken.ActionName()} at Enemy HP %. Set to Zero to disable this check.", $"當敵人生命百分比達到此值時停止使用{VPR.Reawaken.ActionName()}。設定為零以禁用此檢查。"),
                KeyValuePair.Create($"Replaces {VPR.Reawaken.ActionName()} with Full Generation - Legacy combo.", $"將{VPR.Reawaken.ActionName()}替換為祖靈之牙-祖靈之蛇連擊。"),
                #endregion
                
                #region VPRPvP
                KeyValuePair.Create("Turns Dual Fang Combo into an all-in-one button.", "將壹之牙【咬創】和壹之牙【切割】連擊整合為一個按鈕。"),
                KeyValuePair.Create("Uses Bloodcoil when available.", "在可用時使用Bloodcoil。"),
                KeyValuePair.Create("- Requires target's or player's HP to be under:", "- 需要目標或玩家的HP低於："),
                KeyValuePair.Create("Uses Uncoiled Fury when available.", "在可用時使用Uncoiled Fury。"),
                KeyValuePair.Create("Uses Backlash when available.", "在可用時使用Backlash。"),
                KeyValuePair.Create("Uses Rattling Coil when any condition is met.", "當滿足任何條件時使用Rattling Coil。"),
                KeyValuePair.Create("Uses Slither when outside melee.", "在近戰範圍外時使用Slither。"),
                KeyValuePair.Create("- Must remain within maximum range.", "- 必須保持在最大範圍內。"),
                KeyValuePair.Create("- Will not use if already under Slither's effect.", "- 如果已經處於Slither效果下則不會使用。"),
                KeyValuePair.Create("Adds Rattling Coil to Snake Scales when available.", "在可用時將Rattling Coil新增到Snake Scales中。"),
                KeyValuePair.Create("- Requires Snake Scales to be on cooldown.", "- 需要Snake Scales處於冷卻中。"),
                KeyValuePair.Create("Empowered Only", "僅強化狀態"),
                KeyValuePair.Create("Also requires Snake's Bane to be present.", "需要蛇血狀態存在"),
                KeyValuePair.Create("No Uncoiled Fury", "飛蛇之尾冷卻中"),
                KeyValuePair.Create("Must not have charges of Uncoiled Fury.", "必須沒有飛蛇之尾的充能次數"),
                KeyValuePair.Create("No Snake Scales", "蛇鱗術冷卻中"),
                KeyValuePair.Create("Snake Scales must be on cooldown.", "蛇鱗術必須處於未冷卻好的狀態"),
                KeyValuePair.Create("Charges to Keep", "保留的充能次數"),
                KeyValuePair.Create("Maximum Range", "最大距離"),
                #endregion
            ];
        }
    }
}
