using Lumina.Data.Parsing;
using System;
using System.Collections.Generic;
using WrathCombo.Combos.PvE;
using WrathCombo.Combos.PvP;
using WrathCombo.Extensions;

namespace WrathCombo.Resources.Dictionary.Chinese.Description
{
    public static class WARDesc
    {
        public static IEnumerable<KeyValuePair<string, string>> GetDescriptions()
        {
            return
            [
                // Generated by the String Extraction and Translation Tool  
                // Model: DeepSeek v3  
                // Temperature: 0.1  
                // Generation Time: 2025-03-13 18:14:55  
                #region WARPvE
                KeyValuePair.Create("Replaces Heavy Swing with a full one-button single target rotation.", "用一鍵完整單體循環替換Heavy Swing。"),
                KeyValuePair.Create("This is the ideal option for newcomers to the job.", "這是新手玩家的理想選擇。"),
                KeyValuePair.Create("Replaces Overpower with a full one-button AoE rotation.", "用一鍵完整AOE循環替換Overpower。"),
                KeyValuePair.Create("Adds Interject to the rotation when your target's cast is interruptible.", "當目標施法可打斷時，將Interject加入循環。"),
                KeyValuePair.Create("Adds Storms Eye into the rotation.", "將Storms Eye加入循環。"),
                KeyValuePair.Create("Adds Tomahawk into the rotation when you are out of range.", "當你超出近戰範圍時，將Tomahawk加入循環。"),
                KeyValuePair.Create("Adds Berserk / Inner Release into the rotation.", "將Berserk / Inner Release加入循環。"),
                KeyValuePair.Create("Adds Inner Beast / Fell Cleave into the rotation.", "將Inner Beast / Fell Cleave加入循環。"),
                KeyValuePair.Create("Will use when you have the set minimum gauge, or under Inner Release buff.", "當你有設定的最低量譜或在Inner Release增益下時使用。"),
                KeyValuePair.Create("Will also use Nascent Chaos.", "同時也會使用原初的混沌。"),
                KeyValuePair.Create("Adds Infuriate into the rotation.", "將Infuriate加入循環。"),
                KeyValuePair.Create("Adds Onslaught into the rotation.", "將Onslaught加入循環。"),
                KeyValuePair.Create("Uses Onslaught when in the Target's target ring (or within 1 yalm) & when not moving.", "在目標的環形範圍內（或1碼內）且不移動時使用Onslaught。"),
                KeyValuePair.Create("Will use as many stacks as selected in the above slider.", "將使用上述滑塊中選擇的儘可能多的層數。"),
                KeyValuePair.Create("Adds Upheaval into the rotation.", "將Upheaval加入循環。"),
                KeyValuePair.Create("Adds Primal Rend into the rotation.", "將Primal Rend加入循環。"),
                KeyValuePair.Create("Only uses when in the Target's target ring (or within 1 yalm) & when not moving.", "僅在目標的環形範圍內（或1碼內）且不移動時使用。"),
                KeyValuePair.Create("Adds Primal Wrath into the rotation.", "將Primal Wrath加入循環。"),
                KeyValuePair.Create("Adds Primal Ruination into the rotation.", "將Primal Ruination加入循環。"),
                KeyValuePair.Create("Adds Orogeny into the rotation.", "將Orogeny加入循環。"),
                KeyValuePair.Create("Uses Primal Rend after you consume 3 stacks of Inner Release & after Primal Wrath.", "在你消耗3層Inner Release後及Primal Wrath後使用Primal Rend。"),
                KeyValuePair.Create("Adds defensive actions into the rotation based on Health percentage remaining.", "根據剩餘生命值百分比將防禦技能加入循環。"),
                KeyValuePair.Create("Adds Raw Intuition / Bloodwhetting into the rotation based on Health percentage remaining.", "根據剩餘生命值百分比將Raw Intuition / Bloodwhetting加入循環。"),
                KeyValuePair.Create("Adds Equilibrium into the rotation based on Health percentage remaining.", "根據剩餘生命值百分比將Equilibrium加入循環。"),
                KeyValuePair.Create("Adds Rampart into the rotation based on Health percentage remaining.", "根據剩餘生命值百分比將Rampart加入循環。"),
                KeyValuePair.Create("Adds Thrill of Battle into the rotation based on Health percentage remaining.", "根據剩餘生命值百分比將Thrill of Battle加入循環。"),
                KeyValuePair.Create("Adds Vengeance / Damnation into the rotation based on Health percentage remaining.", "根據剩餘生命值百分比將Vengeance / Damnation加入循環。"),
                KeyValuePair.Create("Adds Holmgang into the rotation based on Health percentage remaining.", "根據剩餘生命值百分比將Holmgang加入循環。"),
                KeyValuePair.Create("Adds Reprisal into the rotation based on Health percentage remaining.", "根據剩餘生命值百分比將Reprisal加入循環。"),
                KeyValuePair.Create("Adds Arm's Length into the rotation based on Health percentage remaining.", "根據剩餘生命值百分比將Arm's Length加入循環。"),
                KeyValuePair.Create("Adds Low Blow to the rotation when your target is casting, interruptible or not.", "當目標施法時，無論是否可打斷，將Low Blow加入循環。"),
                KeyValuePair.Create("Replace Nascent Flash with Raw intuition when level synced below 76.", "當等級同步低於76級時，用Raw Intuition替換Nascent Flash。"),
                KeyValuePair.Create("Adds Infuriate into the rotation when gauge is below 50 and not under Inner Release.", "當量譜低於50且不在Inner Release下時，將Infuriate加入循環。"),
                KeyValuePair.Create("Adds Steel Cyclone / Decimate into the rotation.", "將Steel Cyclone / Decimate加入循環。"),
                KeyValuePair.Create("Replaces Thrill Of Battle with an all-in-one mitigation button.", "用一鍵減傷按鈕替換Thrill of Battle。"),
                KeyValuePair.Create("Gives max priority to Holmgang when the Health percentage threshold is met.", "當生命值百分比達到閾值時，優先使用Holmgang。"),
                KeyValuePair.Create("Adds Raw Intuition / Bloodwhetting to the one-button mitigation.", "將Raw Intuition / Bloodwhetting加入一鍵減傷。"),
                KeyValuePair.Create("Adds Equilibrium to the one-button mitigation.", "將Equilibrium加入一鍵減傷。"),
                KeyValuePair.Create("Adds Reprisal to the one-button mitigation.", "將Reprisal加入一鍵減傷。"),
                KeyValuePair.Create("NOTE: Will not use unless there is a target within range to prevent waste", "注意：除非範圍內有目標，否則不會使用，以防止浪費。"),
                KeyValuePair.Create("Adds Rampart to the one-button mitigation.", "將Rampart加入一鍵減傷。"),
                KeyValuePair.Create("Adds Shake It Off to the one-button mitigation.", "將Shake It Off加入一鍵減傷。"),
                KeyValuePair.Create("Adds Arm's Length to the one-button mitigation.", "將Arm's Length加入一鍵減傷。"),
                KeyValuePair.Create("Adds Vengeance to the one-button mitigation.", "將Vengeance加入一鍵減傷。"),
                KeyValuePair.Create("Turns Fell Cleave and Decimate into Infuriate if at or under set gauge value.", "當量譜值等於或低於設定值時，將Fell Cleave和Decimate轉換為Infuriate。"),
                KeyValuePair.Create("Inner Release Priority Option", "原初的解放優先順序"),
                KeyValuePair.Create("Prevents the use of Infuriate while you have Inner Release stacks available.", "當你有原初的解放層數時，阻止使用戰嚎。"),
                KeyValuePair.Create("Replace Storm's Eye with its combo chain.", "用其連擊鏈替換Storm's Eye。"),
                KeyValuePair.Create("Replaces Storm's Path with Storm's Eye when Surging Tempest buff needs refreshing.", "當戰場風暴增益需要重新整理時，用Storm's Eye替換Storm's Path。"),
                KeyValuePair.Create("Replaces Thrill Of Battle with Equilibrium when used.", "使用時用Equilibrium替換Thrill of Battle。"),
                KeyValuePair.Create("Replaces Thrill Of Battle with Equilibrium only when under its buff.", "僅在Thrill of Battle增益下時用Equilibrium替換Thrill of Battle。"),
                KeyValuePair.Create("Buffed Equilibrium Only", "僅在有增益狀態時使用Equilibrium"),
                #endregion

                #region WARPvP
                KeyValuePair.Create("Turns Heavy Swing into an all-in-one damage button.", "將Heavy Swing變為一個全能傷害技能按鈕。"),
                KeyValuePair.Create("Allows use of Bloodwhetting any time, not just between GCDs.", "允許隨時使用Bloodwhetting，而不僅限於GCD之間。"),
                KeyValuePair.Create("Adds Blota to Burst Mode when not in melee range.", "當不在近戰範圍內時，將Blota加入Burst Mode。"),
                KeyValuePair.Create("Adds Primal Rend to Burst Mode.", "將Primal Rend加入Burst Mode。"),
                KeyValuePair.Create("Adds Inner Chaos to Burst Mode.", "將Inner Chaos加入Burst Mode。"),
                KeyValuePair.Create("Adds Orogeny to Burst Mode.", "將Orogeny加入Burst Mode。"),
                KeyValuePair.Create("Adds Onslaught to Burst Mode.", "將Onslaught加入Burst Mode。"),
                KeyValuePair.Create("Adds Primal Scream to Burst Mode.", "將Primal Scream加入Burst Mode。"),
                #endregion

                // Manually added
                KeyValuePair.Create("Use when gauge is less than or equal to:", "當怒氣槽小於或等於以下此值時使用："),
                KeyValuePair.Create("Minimum gauge required to spend", "使用技能所需的最低怒氣槽值"),
                KeyValuePair.Create("Use when gauge is under or equal to", "當怒氣槽小於或等於此值時使用"),
                KeyValuePair.Create("Primal Combo Feature", "原初連擊"),
            ];
        }
    }
}
