using System;
using System.Collections.Generic;
using WrathCombo.Combos.PvE;
using WrathCombo.Combos.PvP;
using WrathCombo.Extensions;

namespace WrathCombo.Resources.Dictionary.Chinese.Description
{
    public static class WHMDesc
    {
        public static IEnumerable<KeyValuePair<string, string>> GetDescriptions()
        {
            return
            [
                // Generated by the String Extraction and Translation Tool  
                // Model: DeepSeek v3  
                // Temperature: 0.1  
                // Generation Time: 2025-03-13 18:14:55  
                #region WHM                                
                KeyValuePair.Create("Advanced Action", "高階技能"),
                KeyValuePair.Create("Change how actions are handled", "更改技能的處理方式"),
                KeyValuePair.Create("Balance Opener (Level 92)", "平衡起手式（等級92）"),
                KeyValuePair.Create("Adds a Swiftcast->Holy at the beginning of your AoE rotation.", "在AoE循環開始時新增一個Swiftcast->Holy。"),
                KeyValuePair.Create("Swift Holy Pull 'Opener' Option", "即刻神聖起手"),
                KeyValuePair.Create("Requires you to already be in combat, to have stopped moving, and to not have used Assize yet.", "需要你已經進入戰鬥狀態，停止移動，並且尚未使用Assize。"),
                KeyValuePair.Create("Collection of cooldowns and spell features on Glares/Stones/Aeros/Dia.", "巨岩/閃耀/勁風/天輝替換為冷卻技和法術集合。"),
                KeyValuePair.Create("Adds Aero/Dia to the single target combo if the debuff is not present on current target, or is about to expire.", "如果當前目標沒有Aero/Dia的減益效果，或者即將消失，則在單體連擊中新增Aero/Dia。"),
                KeyValuePair.Create("Adds Assize to the single target combo.", "在單體連擊中新增Assize。"),
                KeyValuePair.Create("Adds Glare IV to the single target combo when under Sacred Sight", "在Sacred Sight狀態下，在單體連擊中新增Glare IV。"),
                KeyValuePair.Create("Adds Afflatus Misery to the single target combo when it is ready to be used.", "當Afflatus Misery準備就緒時，在單體連擊中新增Afflatus Misery。"),
                KeyValuePair.Create("Adds Afflatus Rapture to the single target combo when at three Lilies.", "當擁有三個血百合時，在單體連擊中新增Afflatus Rapture。"),
                KeyValuePair.Create("Adds Presence of Mind to the single target combo.", "在單體連擊中新增Presence of Mind。"),
                KeyValuePair.Create("Adds Lucid Dreaming to the single target combo when below set MP value.", "當魔力值低於設定值時，在單體連擊中新增Lucid Dreaming。"),
                KeyValuePair.Create("Collection of cooldowns and spell features on Holy/Holy III.", "神聖/豪聖替換為冷卻技和法術集合。"),
                KeyValuePair.Create("Adds Assize to the AoE combo.", "在AoE連擊中新增Assize。"),
                KeyValuePair.Create("Adds Glare IV to the AoE combo when under Sacred Sight", "在Sacred Sight狀態下，在AoE連擊中新增Glare IV。"),
                KeyValuePair.Create("Adds Afflatus Misery to the AoE combo when it is ready to be used.", "當Afflatus Misery準備就緒時，在AoE連擊中新增Afflatus Misery。"),
                KeyValuePair.Create("Adds Afflatus Rapture to the AoE combo when at three Lilies.", "當擁有三個血百合時，在AoE連擊中新增Afflatus Rapture。"),
                KeyValuePair.Create("Adds Presence of Mind to the AoE combo, this will delay your GCD by default.", "在AoE連擊中新增Presence of Mind，預設情況下會延遲你的GCD。"),
                KeyValuePair.Create("Adds Lucid Dreaming to the AoE combo when below the set MP value if you are moving or it can be weaved without GCD delay.", "當MP低於設定值時，如果你在移動或可以在不延遲GCD的情況下插入，則在AoE連擊中新增Lucid Dreaming。"),
                KeyValuePair.Create("Replaces Afflatus Solace with Afflatus Misery when it is ready to be used.", "當Afflatus Misery準備就緒時，用Afflatus Misery替換Afflatus Solace。"),
                KeyValuePair.Create("Replaces Afflatus Rapture with Afflatus Misery when it is ready to be used.", "當Afflatus Misery準備就緒時，用Afflatus Misery替換Afflatus Rapture。"),
                KeyValuePair.Create("Replaces Medica with a one button AoE healing setup.", "用一個按鈕的AoE治療設定替換Medica。"),
                KeyValuePair.Create("Uses Afflatus Rapture when available.", "當Afflatus Rapture可用時使用。"),
                KeyValuePair.Create("Uses Afflatus Misery when available.", "當Afflatus Misery可用時使用。"),
                KeyValuePair.Create("Uses Thin Air when available.", "當Thin Air可用時使用。"),
                KeyValuePair.Create("Replaces Medica with Cure III when available.", "當Cure III可用時，用Cure III替換Medica。"),
                KeyValuePair.Create("Uses Assize when available.", "當Assize可用時使用。"),
                KeyValuePair.Create("Uses Plenary Indulgence when available.", "當Plenary Indulgence可用時使用。"),
                KeyValuePair.Create("Uses Lucid Dreaming when available.", "當Lucid Dreaming可用時使用。"),
                KeyValuePair.Create("Uses Divine Caress when Divine Grace from Temperance is active.", "當節制的Divine Caress預備啟用時使用Divine Caress。"),
                KeyValuePair.Create("Replaces Cure with a one button single target healing setup.", "用一個按鈕的單體治療設定替換Cure。"),
                KeyValuePair.Create("Applies Regen to the target if missing.", "如果目標缺少Regen，則應用Regen。"),
                KeyValuePair.Create("Uses Benediction when target is below HP threshold.", "當目標HP低於閾值時使用Benediction。"),
                KeyValuePair.Create("Uses Afflatus Solace when available.", "當Afflatus Solace可用時使用。"),
                KeyValuePair.Create("Uses Tetragrammaton when available.", "當Tetragrammaton可用時使用。"),
                KeyValuePair.Create("Uses Divine Benison when available.", "當Divine Benison可用時使用。"),
                KeyValuePair.Create("Uses Aquaveil when available.", "當Aquaveil可用時使用。"),
                KeyValuePair.Create("Applies Esuna to your target if there is a cleansable debuff.", "如果目標有可清除的減益效果，則對目標使用Esuna。"),
                KeyValuePair.Create("Changes Cure II to Cure when synced below Lv.30.", "當同步到30級以下時，將Cure II更改為Cure。"),
                KeyValuePair.Create("Changes Swiftcast to Raise.", "將Swiftcast更改為Raise。"),
                KeyValuePair.Create("Adds Thin Air to the Global Raise Feature/Alternative Raise Feature.", "將Thin Air新增到全域復活功能/備用復活功能。"),
                KeyValuePair.Create("Use Variant Rampart on cooldown.", "冷卻即用Variant Rampart。"),
                KeyValuePair.Create("Turns Glare into an all-in-one damage button.", "將Glare變成一個全能傷害按鈕。"),
                KeyValuePair.Create("Adds Afflatus Misery to Burst Mode.", "將Afflatus Misery新增到爆發模式。"),
                KeyValuePair.Create("Adds Miracle of Nature to Burst Mode.", "將Miracle of Nature新增到爆發模式。"),
                KeyValuePair.Create("Adds Seraph Strike to Burst Mode.", "將Seraph Strike新增到爆發模式。"),
                KeyValuePair.Create("Adds Afflatus Purgation (Limit Break) to Burst Mode.", "將Afflatus Purgation（極限爆發）新增到爆發模式。"),
                KeyValuePair.Create("Adds the below options onto Cure II.", "將以下選項新增到Cure II。"),
                KeyValuePair.Create("Adds Cure III to Cure II when available.", "當Cure III可用時，將其新增到Cure II。"),
                KeyValuePair.Create("Adds Aquaviel to Cure II when available.", "當Aquaveil可用時，將其新增到Cure II。"),
                KeyValuePair.Create("Uses Medica II when heal target doesn't have Medica II buff.", "噹噹前目標沒有Medica II增益時，使用Medica II。"),
                KeyValuePair.Create("Upgrades to Medica III when level allows.", "當等級允許時，升級為Medica III。"),
                KeyValuePair.Create("Only Weave or Use Whilst Moving.", "僅在移動時插入或使用。"),
                KeyValuePair.Create("Use when MP is above", "當MP高於此值時使用"),
                KeyValuePair.Create("Time Remaining on Buff to Renew", "重新整理增益的剩餘時間"),
                KeyValuePair.Create("Party UI Mousover Checking", "小隊UI滑鼠懸停檢查"),
                KeyValuePair.Create("Check your mouseover target for the Medica II/III buff.", "檢查你的滑鼠懸停目標是否有醫濟/醫養增益。"),
                KeyValuePair.Create("Time Remaining Before Refreshing", "重新整理前的剩餘時間"),
                KeyValuePair.Create("Use when target HP% is at or below.", "當目標生命值百分比等於或低於此值時使用。"),
                #endregion

                // Manually added
                KeyValuePair.Create("Apply options to all Stones and Glares.", "將選項應用於所有巨岩及閃耀。"),
                KeyValuePair.Create("Apply options to Aeros and Dia.", "將選項應用於所有勁風及天輝。"),
                KeyValuePair.Create($"Apply options to On 中巨岩.", $"將選項應用於中巨岩。"),
                KeyValuePair.Create($"If Both {WHMPvP.Aquaveil.ActionName()} & {WHMPvP.Cure3.ActionName()} are ready, prioritise {WHMPvP.Aquaveil.ActionName()}", "如果水流幕和大療傷都準備就緒，優先使用水流幕"),
                KeyValuePair.Create($"If Both {WHMPvP.Aquaveil.ActionName()} & {WHMPvP.Cure3.ActionName()} are ready, prioritise {WHMPvP.Cure3.ActionName()}", "如果水流幕和大療傷都準備就緒，優先使用大療傷"),
                KeyValuePair.Create("Replaces Stone with a full one-button single target rotation.", "將巨岩替換為完整的一鍵單體循環。"),
                KeyValuePair.Create("Replaces Holy with a full one-button AoE rotation.", "將神聖替換為完整的一鍵多目標循環。"),
                KeyValuePair.Create("Will reapply DoT early to all enemies within range while moving.", "移動時會對範圍內所有敵人提前補上DoT。"),
                KeyValuePair.Create("Multitarget Dot Option", "多目標DOT選項"),
                KeyValuePair.Create("Maintains dots on multiple targets.", "保持DOT在多個目標上。"),
                
            ];
        }
    }
}
